// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// FrontPort front port
//
// swagger:model FrontPort
type FrontPort struct {

	//  occupied
	// Read Only: true
	Occupied *bool `json:"_occupied,omitempty"`

	// cable
	Cable *BriefCable `json:"cable,omitempty"`

	// * `A` - A
	// * `B` - B
	// Read Only: true
	// Enum: ["A","B"]
	CableEnd *string `json:"cable_end,omitempty"`

	// color
	// Max Length: 6
	// Pattern: ^[0-9a-f]{6}$
	Color string `json:"color,omitempty"`

	// created
	// Read Only: true
	// Format: date-time
	Created *strfmt.DateTime `json:"created,omitempty"`

	// custom fields
	CustomFields map[string]any `json:"custom_fields,omitempty"`

	// description
	// Max Length: 200
	Description string `json:"description,omitempty"`

	// device
	// Required: true
	Device *BriefDevice `json:"device"`

	// display
	// Read Only: true
	Display string `json:"display,omitempty"`

	// display url
	// Read Only: true
	// Format: uri
	DisplayURL strfmt.URI `json:"display_url,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// Physical label
	// Max Length: 64
	Label string `json:"label,omitempty"`

	// last updated
	// Read Only: true
	// Format: date-time
	LastUpdated *strfmt.DateTime `json:"last_updated,omitempty"`

	// link peers
	// Read Only: true
	LinkPeers []any `json:"link_peers"`

	// Return the type of the peer link terminations, or None.
	// Read Only: true
	LinkPeersType *string `json:"link_peers_type,omitempty"`

	// Treat as if a cable is connected
	MarkConnected bool `json:"mark_connected,omitempty"`

	// module
	Module *BriefModule `json:"module,omitempty"`

	// name
	// Required: true
	// Max Length: 64
	Name *string `json:"name"`

	// owner
	Owner *BriefOwner `json:"owner,omitempty"`

	// positions
	// Maximum: 1024
	// Minimum: 1
	Positions int64 `json:"positions,omitempty"`

	// rear ports
	RearPorts []*FrontPortMapping `json:"rear_ports"`

	// tags
	Tags []*NestedTag `json:"tags"`

	// type
	// Required: true
	Type *FrontPortType `json:"type"`

	// url
	// Read Only: true
	// Format: uri
	URL strfmt.URI `json:"url,omitempty"`
}

// Validate validates this front port
func (m *FrontPort) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCable(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCableEnd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateColor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDevice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDisplayURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastUpdated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModule(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOwner(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePositions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRearPorts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTags(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FrontPort) validateCable(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Cable) { // not required
		return nil
	}

	if m.Cable != nil {
		if err := m.Cable.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cable")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cable")
			}

			return err
		}
	}

	return nil
}

var frontPortTypeCableEndPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["A","B"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontPortTypeCableEndPropEnum = append(frontPortTypeCableEndPropEnum, v)
	}
}

const (

	// FrontPortCableEndA captures enum value "A"
	FrontPortCableEndA string = "A"

	// FrontPortCableEndB captures enum value "B"
	FrontPortCableEndB string = "B"
)

// prop value enum
func (m *FrontPort) validateCableEndEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, frontPortTypeCableEndPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FrontPort) validateCableEnd(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CableEnd) { // not required
		return nil
	}

	// value enum
	if err := m.validateCableEndEnum("cable_end", "body", *m.CableEnd); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) validateColor(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Color) { // not required
		return nil
	}

	if err := validate.MaxLength("color", "body", m.Color, 6); err != nil {
		return err
	}

	if err := validate.Pattern("color", "body", m.Color, `^[0-9a-f]{6}$`); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) validateCreated(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) validateDescription(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", m.Description, 200); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) validateDevice(formats strfmt.Registry) error {

	if err := validate.Required("device", "body", m.Device); err != nil {
		return err
	}

	if m.Device != nil {
		if err := m.Device.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("device")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("device")
			}

			return err
		}
	}

	return nil
}

func (m *FrontPort) validateDisplayURL(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DisplayURL) { // not required
		return nil
	}

	if err := validate.FormatOf("display_url", "body", "uri", m.DisplayURL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) validateLabel(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Label) { // not required
		return nil
	}

	if err := validate.MaxLength("label", "body", m.Label, 64); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) validateLastUpdated(formats strfmt.Registry) error {
	if typeutils.IsZero(m.LastUpdated) { // not required
		return nil
	}

	if err := validate.FormatOf("last_updated", "body", "date-time", m.LastUpdated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) validateModule(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Module) { // not required
		return nil
	}

	if m.Module != nil {
		if err := m.Module.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("module")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("module")
			}

			return err
		}
	}

	return nil
}

func (m *FrontPort) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name, 64); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) validateOwner(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Owner) { // not required
		return nil
	}

	if m.Owner != nil {
		if err := m.Owner.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("owner")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("owner")
			}

			return err
		}
	}

	return nil
}

func (m *FrontPort) validatePositions(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Positions) { // not required
		return nil
	}

	if err := validate.MinimumInt("positions", "body", m.Positions, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("positions", "body", m.Positions, 1024, false); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) validateRearPorts(formats strfmt.Registry) error {
	if typeutils.IsZero(m.RearPorts) { // not required
		return nil
	}

	for i := 0; i < len(m.RearPorts); i++ {
		if typeutils.IsZero(m.RearPorts[i]) { // not required
			continue
		}

		if m.RearPorts[i] != nil {
			if err := m.RearPorts[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("rear_ports" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("rear_ports" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *FrontPort) validateTags(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Tags) { // not required
		return nil
	}

	for i := 0; i < len(m.Tags); i++ {
		if typeutils.IsZero(m.Tags[i]) { // not required
			continue
		}

		if m.Tags[i] != nil {
			if err := m.Tags[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("tags" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("tags" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *FrontPort) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	if m.Type != nil {
		if err := m.Type.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("type")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("type")
			}

			return err
		}
	}

	return nil
}

func (m *FrontPort) validateURL(formats strfmt.Registry) error {
	if typeutils.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.FormatOf("url", "body", "uri", m.URL.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this front port based on the context it is used
func (m *FrontPort) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOccupied(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCable(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCableEnd(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDevice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDisplay(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDisplayURL(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLastUpdated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLinkPeers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLinkPeersType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateModule(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOwner(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRearPorts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTags(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateURL(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FrontPort) contextValidateOccupied(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "_occupied", "body", m.Occupied); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) contextValidateCable(ctx context.Context, formats strfmt.Registry) error {

	if m.Cable != nil {

		if typeutils.IsZero(m.Cable) { // not required
			return nil
		}

		if err := m.Cable.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cable")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cable")
			}

			return err
		}
	}

	return nil
}

func (m *FrontPort) contextValidateCableEnd(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "cable_end", "body", m.CableEnd); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) contextValidateCreated(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "created", "body", m.Created); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) contextValidateDevice(ctx context.Context, formats strfmt.Registry) error {

	if m.Device != nil {

		if err := m.Device.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("device")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("device")
			}

			return err
		}
	}

	return nil
}

func (m *FrontPort) contextValidateDisplay(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "display", "body", m.Display); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) contextValidateDisplayURL(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "display_url", "body", m.DisplayURL); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) contextValidateLastUpdated(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "last_updated", "body", m.LastUpdated); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) contextValidateLinkPeers(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "link_peers", "body", m.LinkPeers); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) contextValidateLinkPeersType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "link_peers_type", "body", m.LinkPeersType); err != nil {
		return err
	}

	return nil
}

func (m *FrontPort) contextValidateModule(ctx context.Context, formats strfmt.Registry) error {

	if m.Module != nil {

		if typeutils.IsZero(m.Module) { // not required
			return nil
		}

		if err := m.Module.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("module")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("module")
			}

			return err
		}
	}

	return nil
}

func (m *FrontPort) contextValidateOwner(ctx context.Context, formats strfmt.Registry) error {

	if m.Owner != nil {

		if typeutils.IsZero(m.Owner) { // not required
			return nil
		}

		if err := m.Owner.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("owner")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("owner")
			}

			return err
		}
	}

	return nil
}

func (m *FrontPort) contextValidateRearPorts(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RearPorts); i++ {

		if m.RearPorts[i] != nil {

			if typeutils.IsZero(m.RearPorts[i]) { // not required
				return nil
			}

			if err := m.RearPorts[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("rear_ports" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("rear_ports" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *FrontPort) contextValidateTags(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Tags); i++ {

		if m.Tags[i] != nil {

			if typeutils.IsZero(m.Tags[i]) { // not required
				return nil
			}

			if err := m.Tags[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("tags" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("tags" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *FrontPort) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if m.Type != nil {

		if err := m.Type.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("type")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("type")
			}

			return err
		}
	}

	return nil
}

func (m *FrontPort) contextValidateURL(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "url", "body", m.URL); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FrontPort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FrontPort) UnmarshalBinary(b []byte) error {
	var res FrontPort
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// FrontPortType front port type
//
// swagger:model FrontPortType
type FrontPortType struct {

	// label
	// Enum: ["8P8C","8P6C","8P4C","8P2C","6P6C","6P4C","6P2C","4P4C","4P2C","GG45","TERA 4P","TERA 2P","TERA 1P","110 Punch","BNC","F Connector","N Connector","MRJ21","FC","FC/PC","FC/UPC","FC/APC","LC","LC/PC","LC/UPC","LC/APC","MU","MU/PC","MU/UPC","MU/APC","LSH","LSH/PC","LSH/UPC","LSH/APC","LX.5","LX.5/PC","LX.5/UPC","LX.5/APC","MPO","MTRJ","SC","SC/PC","SC/UPC","SC/APC","ST","CS","SN","MDC","SMA 905","SMA 906","URM-P2","URM-P4","URM-P8","Splice","USB Type A","USB Type B","USB Type C","USB Mini A","USB Mini B","USB Micro A","USB Micro B","USB Micro AB","Other"]
	Label string `json:"label,omitempty"`

	// * `8p8c` - 8P8C
	// * `8p6c` - 8P6C
	// * `8p4c` - 8P4C
	// * `8p2c` - 8P2C
	// * `6p6c` - 6P6C
	// * `6p4c` - 6P4C
	// * `6p2c` - 6P2C
	// * `4p4c` - 4P4C
	// * `4p2c` - 4P2C
	// * `gg45` - GG45
	// * `tera-4p` - TERA 4P
	// * `tera-2p` - TERA 2P
	// * `tera-1p` - TERA 1P
	// * `110-punch` - 110 Punch
	// * `bnc` - BNC
	// * `f` - F Connector
	// * `n` - N Connector
	// * `mrj21` - MRJ21
	// * `fc` - FC
	// * `fc-pc` - FC/PC
	// * `fc-upc` - FC/UPC
	// * `fc-apc` - FC/APC
	// * `lc` - LC
	// * `lc-pc` - LC/PC
	// * `lc-upc` - LC/UPC
	// * `lc-apc` - LC/APC
	// * `mu` - MU
	// * `mu-pc` - MU/PC
	// * `mu-upc` - MU/UPC
	// * `mu-apc` - MU/APC
	// * `lsh` - LSH
	// * `lsh-pc` - LSH/PC
	// * `lsh-upc` - LSH/UPC
	// * `lsh-apc` - LSH/APC
	// * `lx5` - LX.5
	// * `lx5-pc` - LX.5/PC
	// * `lx5-upc` - LX.5/UPC
	// * `lx5-apc` - LX.5/APC
	// * `mpo` - MPO
	// * `mtrj` - MTRJ
	// * `sc` - SC
	// * `sc-pc` - SC/PC
	// * `sc-upc` - SC/UPC
	// * `sc-apc` - SC/APC
	// * `st` - ST
	// * `cs` - CS
	// * `sn` - SN
	// * `mdc` - MDC
	// * `sma-905` - SMA 905
	// * `sma-906` - SMA 906
	// * `urm-p2` - URM-P2
	// * `urm-p4` - URM-P4
	// * `urm-p8` - URM-P8
	// * `splice` - Splice
	// * `usb-a` - USB Type A
	// * `usb-b` - USB Type B
	// * `usb-c` - USB Type C
	// * `usb-mini-a` - USB Mini A
	// * `usb-mini-b` - USB Mini B
	// * `usb-micro-a` - USB Micro A
	// * `usb-micro-b` - USB Micro B
	// * `usb-micro-ab` - USB Micro AB
	// * `other` - Other
	// Enum: ["8p8c","8p6c","8p4c","8p2c","6p6c","6p4c","6p2c","4p4c","4p2c","gg45","tera-4p","tera-2p","tera-1p","110-punch","bnc","f","n","mrj21","fc","fc-pc","fc-upc","fc-apc","lc","lc-pc","lc-upc","lc-apc","mu","mu-pc","mu-upc","mu-apc","lsh","lsh-pc","lsh-upc","lsh-apc","lx5","lx5-pc","lx5-upc","lx5-apc","mpo","mtrj","sc","sc-pc","sc-upc","sc-apc","st","cs","sn","mdc","sma-905","sma-906","urm-p2","urm-p4","urm-p8","splice","usb-a","usb-b","usb-c","usb-mini-a","usb-mini-b","usb-micro-a","usb-micro-b","usb-micro-ab","other"]
	Value string `json:"value,omitempty"`
}

// Validate validates this front port type
func (m *FrontPortType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var frontPortTypeTypeLabelPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["8P8C","8P6C","8P4C","8P2C","6P6C","6P4C","6P2C","4P4C","4P2C","GG45","TERA 4P","TERA 2P","TERA 1P","110 Punch","BNC","F Connector","N Connector","MRJ21","FC","FC/PC","FC/UPC","FC/APC","LC","LC/PC","LC/UPC","LC/APC","MU","MU/PC","MU/UPC","MU/APC","LSH","LSH/PC","LSH/UPC","LSH/APC","LX.5","LX.5/PC","LX.5/UPC","LX.5/APC","MPO","MTRJ","SC","SC/PC","SC/UPC","SC/APC","ST","CS","SN","MDC","SMA 905","SMA 906","URM-P2","URM-P4","URM-P8","Splice","USB Type A","USB Type B","USB Type C","USB Mini A","USB Mini B","USB Micro A","USB Micro B","USB Micro AB","Other"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontPortTypeTypeLabelPropEnum = append(frontPortTypeTypeLabelPropEnum, v)
	}
}

const (

	// FrontPortTypeLabelNr8P8C captures enum value "8P8C"
	FrontPortTypeLabelNr8P8C string = "8P8C"

	// FrontPortTypeLabelNr8P6C captures enum value "8P6C"
	FrontPortTypeLabelNr8P6C string = "8P6C"

	// FrontPortTypeLabelNr8P4C captures enum value "8P4C"
	FrontPortTypeLabelNr8P4C string = "8P4C"

	// FrontPortTypeLabelNr8P2C captures enum value "8P2C"
	FrontPortTypeLabelNr8P2C string = "8P2C"

	// FrontPortTypeLabelNr6P6C captures enum value "6P6C"
	FrontPortTypeLabelNr6P6C string = "6P6C"

	// FrontPortTypeLabelNr6P4C captures enum value "6P4C"
	FrontPortTypeLabelNr6P4C string = "6P4C"

	// FrontPortTypeLabelNr6P2C captures enum value "6P2C"
	FrontPortTypeLabelNr6P2C string = "6P2C"

	// FrontPortTypeLabelNr4P4C captures enum value "4P4C"
	FrontPortTypeLabelNr4P4C string = "4P4C"

	// FrontPortTypeLabelNr4P2C captures enum value "4P2C"
	FrontPortTypeLabelNr4P2C string = "4P2C"

	// FrontPortTypeLabelGG45 captures enum value "GG45"
	FrontPortTypeLabelGG45 string = "GG45"

	// FrontPortTypeLabelTERA4P captures enum value "TERA 4P"
	FrontPortTypeLabelTERA4P string = "TERA 4P"

	// FrontPortTypeLabelTERA2P captures enum value "TERA 2P"
	FrontPortTypeLabelTERA2P string = "TERA 2P"

	// FrontPortTypeLabelTERA1P captures enum value "TERA 1P"
	FrontPortTypeLabelTERA1P string = "TERA 1P"

	// FrontPortTypeLabelNr110Punch captures enum value "110 Punch"
	FrontPortTypeLabelNr110Punch string = "110 Punch"

	// FrontPortTypeLabelBNC captures enum value "BNC"
	FrontPortTypeLabelBNC string = "BNC"

	// FrontPortTypeLabelFConnector captures enum value "F Connector"
	FrontPortTypeLabelFConnector string = "F Connector"

	// FrontPortTypeLabelNConnector captures enum value "N Connector"
	FrontPortTypeLabelNConnector string = "N Connector"

	// FrontPortTypeLabelMRJ21 captures enum value "MRJ21"
	FrontPortTypeLabelMRJ21 string = "MRJ21"

	// FrontPortTypeLabelFC captures enum value "FC"
	FrontPortTypeLabelFC string = "FC"

	// FrontPortTypeLabelFCSlashPC captures enum value "FC/PC"
	FrontPortTypeLabelFCSlashPC string = "FC/PC"

	// FrontPortTypeLabelFCSlashUPC captures enum value "FC/UPC"
	FrontPortTypeLabelFCSlashUPC string = "FC/UPC"

	// FrontPortTypeLabelFCSlashAPC captures enum value "FC/APC"
	FrontPortTypeLabelFCSlashAPC string = "FC/APC"

	// FrontPortTypeLabelLC captures enum value "LC"
	FrontPortTypeLabelLC string = "LC"

	// FrontPortTypeLabelLCSlashPC captures enum value "LC/PC"
	FrontPortTypeLabelLCSlashPC string = "LC/PC"

	// FrontPortTypeLabelLCSlashUPC captures enum value "LC/UPC"
	FrontPortTypeLabelLCSlashUPC string = "LC/UPC"

	// FrontPortTypeLabelLCSlashAPC captures enum value "LC/APC"
	FrontPortTypeLabelLCSlashAPC string = "LC/APC"

	// FrontPortTypeLabelMU captures enum value "MU"
	FrontPortTypeLabelMU string = "MU"

	// FrontPortTypeLabelMUSlashPC captures enum value "MU/PC"
	FrontPortTypeLabelMUSlashPC string = "MU/PC"

	// FrontPortTypeLabelMUSlashUPC captures enum value "MU/UPC"
	FrontPortTypeLabelMUSlashUPC string = "MU/UPC"

	// FrontPortTypeLabelMUSlashAPC captures enum value "MU/APC"
	FrontPortTypeLabelMUSlashAPC string = "MU/APC"

	// FrontPortTypeLabelLSH captures enum value "LSH"
	FrontPortTypeLabelLSH string = "LSH"

	// FrontPortTypeLabelLSHSlashPC captures enum value "LSH/PC"
	FrontPortTypeLabelLSHSlashPC string = "LSH/PC"

	// FrontPortTypeLabelLSHSlashUPC captures enum value "LSH/UPC"
	FrontPortTypeLabelLSHSlashUPC string = "LSH/UPC"

	// FrontPortTypeLabelLSHSlashAPC captures enum value "LSH/APC"
	FrontPortTypeLabelLSHSlashAPC string = "LSH/APC"

	// FrontPortTypeLabelLXDot5 captures enum value "LX.5"
	FrontPortTypeLabelLXDot5 string = "LX.5"

	// FrontPortTypeLabelLXDot5SlashPC captures enum value "LX.5/PC"
	FrontPortTypeLabelLXDot5SlashPC string = "LX.5/PC"

	// FrontPortTypeLabelLXDot5SlashUPC captures enum value "LX.5/UPC"
	FrontPortTypeLabelLXDot5SlashUPC string = "LX.5/UPC"

	// FrontPortTypeLabelLXDot5SlashAPC captures enum value "LX.5/APC"
	FrontPortTypeLabelLXDot5SlashAPC string = "LX.5/APC"

	// FrontPortTypeLabelMPO captures enum value "MPO"
	FrontPortTypeLabelMPO string = "MPO"

	// FrontPortTypeLabelMTRJ captures enum value "MTRJ"
	FrontPortTypeLabelMTRJ string = "MTRJ"

	// FrontPortTypeLabelSC captures enum value "SC"
	FrontPortTypeLabelSC string = "SC"

	// FrontPortTypeLabelSCSlashPC captures enum value "SC/PC"
	FrontPortTypeLabelSCSlashPC string = "SC/PC"

	// FrontPortTypeLabelSCSlashUPC captures enum value "SC/UPC"
	FrontPortTypeLabelSCSlashUPC string = "SC/UPC"

	// FrontPortTypeLabelSCSlashAPC captures enum value "SC/APC"
	FrontPortTypeLabelSCSlashAPC string = "SC/APC"

	// FrontPortTypeLabelST captures enum value "ST"
	FrontPortTypeLabelST string = "ST"

	// FrontPortTypeLabelCS captures enum value "CS"
	FrontPortTypeLabelCS string = "CS"

	// FrontPortTypeLabelSN captures enum value "SN"
	FrontPortTypeLabelSN string = "SN"

	// FrontPortTypeLabelMDC captures enum value "MDC"
	FrontPortTypeLabelMDC string = "MDC"

	// FrontPortTypeLabelSMA905 captures enum value "SMA 905"
	FrontPortTypeLabelSMA905 string = "SMA 905"

	// FrontPortTypeLabelSMA906 captures enum value "SMA 906"
	FrontPortTypeLabelSMA906 string = "SMA 906"

	// FrontPortTypeLabelURMDashP2 captures enum value "URM-P2"
	FrontPortTypeLabelURMDashP2 string = "URM-P2"

	// FrontPortTypeLabelURMDashP4 captures enum value "URM-P4"
	FrontPortTypeLabelURMDashP4 string = "URM-P4"

	// FrontPortTypeLabelURMDashP8 captures enum value "URM-P8"
	FrontPortTypeLabelURMDashP8 string = "URM-P8"

	// FrontPortTypeLabelSplice captures enum value "Splice"
	FrontPortTypeLabelSplice string = "Splice"

	// FrontPortTypeLabelUSBTypeA captures enum value "USB Type A"
	FrontPortTypeLabelUSBTypeA string = "USB Type A"

	// FrontPortTypeLabelUSBTypeB captures enum value "USB Type B"
	FrontPortTypeLabelUSBTypeB string = "USB Type B"

	// FrontPortTypeLabelUSBTypeC captures enum value "USB Type C"
	FrontPortTypeLabelUSBTypeC string = "USB Type C"

	// FrontPortTypeLabelUSBMiniA captures enum value "USB Mini A"
	FrontPortTypeLabelUSBMiniA string = "USB Mini A"

	// FrontPortTypeLabelUSBMiniB captures enum value "USB Mini B"
	FrontPortTypeLabelUSBMiniB string = "USB Mini B"

	// FrontPortTypeLabelUSBMicroA captures enum value "USB Micro A"
	FrontPortTypeLabelUSBMicroA string = "USB Micro A"

	// FrontPortTypeLabelUSBMicroB captures enum value "USB Micro B"
	FrontPortTypeLabelUSBMicroB string = "USB Micro B"

	// FrontPortTypeLabelUSBMicroAB captures enum value "USB Micro AB"
	FrontPortTypeLabelUSBMicroAB string = "USB Micro AB"

	// FrontPortTypeLabelOther captures enum value "Other"
	FrontPortTypeLabelOther string = "Other"
)

// prop value enum
func (m *FrontPortType) validateLabelEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, frontPortTypeTypeLabelPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FrontPortType) validateLabel(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Label) { // not required
		return nil
	}

	// value enum
	if err := m.validateLabelEnum("type"+"."+"label", "body", m.Label); err != nil {
		return err
	}

	return nil
}

var frontPortTypeTypeValuePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["8p8c","8p6c","8p4c","8p2c","6p6c","6p4c","6p2c","4p4c","4p2c","gg45","tera-4p","tera-2p","tera-1p","110-punch","bnc","f","n","mrj21","fc","fc-pc","fc-upc","fc-apc","lc","lc-pc","lc-upc","lc-apc","mu","mu-pc","mu-upc","mu-apc","lsh","lsh-pc","lsh-upc","lsh-apc","lx5","lx5-pc","lx5-upc","lx5-apc","mpo","mtrj","sc","sc-pc","sc-upc","sc-apc","st","cs","sn","mdc","sma-905","sma-906","urm-p2","urm-p4","urm-p8","splice","usb-a","usb-b","usb-c","usb-mini-a","usb-mini-b","usb-micro-a","usb-micro-b","usb-micro-ab","other"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		frontPortTypeTypeValuePropEnum = append(frontPortTypeTypeValuePropEnum, v)
	}
}

const (

	// FrontPortTypeValueNr8p8c captures enum value "8p8c"
	FrontPortTypeValueNr8p8c string = "8p8c"

	// FrontPortTypeValueNr8p6c captures enum value "8p6c"
	FrontPortTypeValueNr8p6c string = "8p6c"

	// FrontPortTypeValueNr8p4c captures enum value "8p4c"
	FrontPortTypeValueNr8p4c string = "8p4c"

	// FrontPortTypeValueNr8p2c captures enum value "8p2c"
	FrontPortTypeValueNr8p2c string = "8p2c"

	// FrontPortTypeValueNr6p6c captures enum value "6p6c"
	FrontPortTypeValueNr6p6c string = "6p6c"

	// FrontPortTypeValueNr6p4c captures enum value "6p4c"
	FrontPortTypeValueNr6p4c string = "6p4c"

	// FrontPortTypeValueNr6p2c captures enum value "6p2c"
	FrontPortTypeValueNr6p2c string = "6p2c"

	// FrontPortTypeValueNr4p4c captures enum value "4p4c"
	FrontPortTypeValueNr4p4c string = "4p4c"

	// FrontPortTypeValueNr4p2c captures enum value "4p2c"
	FrontPortTypeValueNr4p2c string = "4p2c"

	// FrontPortTypeValueGg45 captures enum value "gg45"
	FrontPortTypeValueGg45 string = "gg45"

	// FrontPortTypeValueTeraDash4p captures enum value "tera-4p"
	FrontPortTypeValueTeraDash4p string = "tera-4p"

	// FrontPortTypeValueTeraDash2p captures enum value "tera-2p"
	FrontPortTypeValueTeraDash2p string = "tera-2p"

	// FrontPortTypeValueTeraDash1p captures enum value "tera-1p"
	FrontPortTypeValueTeraDash1p string = "tera-1p"

	// FrontPortTypeValueNr110DashPunch captures enum value "110-punch"
	FrontPortTypeValueNr110DashPunch string = "110-punch"

	// FrontPortTypeValueBnc captures enum value "bnc"
	FrontPortTypeValueBnc string = "bnc"

	// FrontPortTypeValueF captures enum value "f"
	FrontPortTypeValueF string = "f"

	// FrontPortTypeValueN captures enum value "n"
	FrontPortTypeValueN string = "n"

	// FrontPortTypeValueMrj21 captures enum value "mrj21"
	FrontPortTypeValueMrj21 string = "mrj21"

	// FrontPortTypeValueFc captures enum value "fc"
	FrontPortTypeValueFc string = "fc"

	// FrontPortTypeValueFcDashPc captures enum value "fc-pc"
	FrontPortTypeValueFcDashPc string = "fc-pc"

	// FrontPortTypeValueFcDashUpc captures enum value "fc-upc"
	FrontPortTypeValueFcDashUpc string = "fc-upc"

	// FrontPortTypeValueFcDashApc captures enum value "fc-apc"
	FrontPortTypeValueFcDashApc string = "fc-apc"

	// FrontPortTypeValueLc captures enum value "lc"
	FrontPortTypeValueLc string = "lc"

	// FrontPortTypeValueLcDashPc captures enum value "lc-pc"
	FrontPortTypeValueLcDashPc string = "lc-pc"

	// FrontPortTypeValueLcDashUpc captures enum value "lc-upc"
	FrontPortTypeValueLcDashUpc string = "lc-upc"

	// FrontPortTypeValueLcDashApc captures enum value "lc-apc"
	FrontPortTypeValueLcDashApc string = "lc-apc"

	// FrontPortTypeValueMu captures enum value "mu"
	FrontPortTypeValueMu string = "mu"

	// FrontPortTypeValueMuDashPc captures enum value "mu-pc"
	FrontPortTypeValueMuDashPc string = "mu-pc"

	// FrontPortTypeValueMuDashUpc captures enum value "mu-upc"
	FrontPortTypeValueMuDashUpc string = "mu-upc"

	// FrontPortTypeValueMuDashApc captures enum value "mu-apc"
	FrontPortTypeValueMuDashApc string = "mu-apc"

	// FrontPortTypeValueLsh captures enum value "lsh"
	FrontPortTypeValueLsh string = "lsh"

	// FrontPortTypeValueLshDashPc captures enum value "lsh-pc"
	FrontPortTypeValueLshDashPc string = "lsh-pc"

	// FrontPortTypeValueLshDashUpc captures enum value "lsh-upc"
	FrontPortTypeValueLshDashUpc string = "lsh-upc"

	// FrontPortTypeValueLshDashApc captures enum value "lsh-apc"
	FrontPortTypeValueLshDashApc string = "lsh-apc"

	// FrontPortTypeValueLx5 captures enum value "lx5"
	FrontPortTypeValueLx5 string = "lx5"

	// FrontPortTypeValueLx5DashPc captures enum value "lx5-pc"
	FrontPortTypeValueLx5DashPc string = "lx5-pc"

	// FrontPortTypeValueLx5DashUpc captures enum value "lx5-upc"
	FrontPortTypeValueLx5DashUpc string = "lx5-upc"

	// FrontPortTypeValueLx5DashApc captures enum value "lx5-apc"
	FrontPortTypeValueLx5DashApc string = "lx5-apc"

	// FrontPortTypeValueMpo captures enum value "mpo"
	FrontPortTypeValueMpo string = "mpo"

	// FrontPortTypeValueMtrj captures enum value "mtrj"
	FrontPortTypeValueMtrj string = "mtrj"

	// FrontPortTypeValueSc captures enum value "sc"
	FrontPortTypeValueSc string = "sc"

	// FrontPortTypeValueScDashPc captures enum value "sc-pc"
	FrontPortTypeValueScDashPc string = "sc-pc"

	// FrontPortTypeValueScDashUpc captures enum value "sc-upc"
	FrontPortTypeValueScDashUpc string = "sc-upc"

	// FrontPortTypeValueScDashApc captures enum value "sc-apc"
	FrontPortTypeValueScDashApc string = "sc-apc"

	// FrontPortTypeValueSt captures enum value "st"
	FrontPortTypeValueSt string = "st"

	// FrontPortTypeValueCs captures enum value "cs"
	FrontPortTypeValueCs string = "cs"

	// FrontPortTypeValueSn captures enum value "sn"
	FrontPortTypeValueSn string = "sn"

	// FrontPortTypeValueMdc captures enum value "mdc"
	FrontPortTypeValueMdc string = "mdc"

	// FrontPortTypeValueSmaDash905 captures enum value "sma-905"
	FrontPortTypeValueSmaDash905 string = "sma-905"

	// FrontPortTypeValueSmaDash906 captures enum value "sma-906"
	FrontPortTypeValueSmaDash906 string = "sma-906"

	// FrontPortTypeValueUrmDashP2 captures enum value "urm-p2"
	FrontPortTypeValueUrmDashP2 string = "urm-p2"

	// FrontPortTypeValueUrmDashP4 captures enum value "urm-p4"
	FrontPortTypeValueUrmDashP4 string = "urm-p4"

	// FrontPortTypeValueUrmDashP8 captures enum value "urm-p8"
	FrontPortTypeValueUrmDashP8 string = "urm-p8"

	// FrontPortTypeValueSplice captures enum value "splice"
	FrontPortTypeValueSplice string = "splice"

	// FrontPortTypeValueUsbDasha captures enum value "usb-a"
	FrontPortTypeValueUsbDasha string = "usb-a"

	// FrontPortTypeValueUsbDashb captures enum value "usb-b"
	FrontPortTypeValueUsbDashb string = "usb-b"

	// FrontPortTypeValueUsbDashc captures enum value "usb-c"
	FrontPortTypeValueUsbDashc string = "usb-c"

	// FrontPortTypeValueUsbDashMiniDasha captures enum value "usb-mini-a"
	FrontPortTypeValueUsbDashMiniDasha string = "usb-mini-a"

	// FrontPortTypeValueUsbDashMiniDashb captures enum value "usb-mini-b"
	FrontPortTypeValueUsbDashMiniDashb string = "usb-mini-b"

	// FrontPortTypeValueUsbDashMicroDasha captures enum value "usb-micro-a"
	FrontPortTypeValueUsbDashMicroDasha string = "usb-micro-a"

	// FrontPortTypeValueUsbDashMicroDashb captures enum value "usb-micro-b"
	FrontPortTypeValueUsbDashMicroDashb string = "usb-micro-b"

	// FrontPortTypeValueUsbDashMicroDashAb captures enum value "usb-micro-ab"
	FrontPortTypeValueUsbDashMicroDashAb string = "usb-micro-ab"

	// FrontPortTypeValueOther captures enum value "other"
	FrontPortTypeValueOther string = "other"
)

// prop value enum
func (m *FrontPortType) validateValueEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, frontPortTypeTypeValuePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FrontPortType) validateValue(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Value) { // not required
		return nil
	}

	// value enum
	if err := m.validateValueEnum("type"+"."+"value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this front port type based on context it is used
func (m *FrontPortType) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FrontPortType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FrontPortType) UnmarshalBinary(b []byte) error {
	var res FrontPortType
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
