// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// WritableRearPortTemplate writable rear port template
//
// swagger:model WritableRearPortTemplate
type WritableRearPortTemplate struct {

	// color
	// Max Length: 6
	// Pattern: ^[0-9a-f]{6}$
	Color string `json:"color,omitempty"`

	// description
	// Max Length: 200
	Description string `json:"description,omitempty"`

	// device type
	DeviceType *int64 `json:"device_type,omitempty"`

	// front ports
	FrontPorts []*RearPortTemplateMapping `json:"front_ports"`

	// Physical label
	// Max Length: 64
	Label string `json:"label,omitempty"`

	// module type
	ModuleType *int64 `json:"module_type,omitempty"`

	// {module} is accepted as a substitution for the module bay position when attached to a module type.
	// Required: true
	// Max Length: 64
	// Min Length: 1
	Name *string `json:"name"`

	// positions
	// Maximum: 1024
	// Minimum: 1
	Positions int64 `json:"positions,omitempty"`

	// * `8p8c` - 8P8C
	// * `8p6c` - 8P6C
	// * `8p4c` - 8P4C
	// * `8p2c` - 8P2C
	// * `6p6c` - 6P6C
	// * `6p4c` - 6P4C
	// * `6p2c` - 6P2C
	// * `4p4c` - 4P4C
	// * `4p2c` - 4P2C
	// * `gg45` - GG45
	// * `tera-4p` - TERA 4P
	// * `tera-2p` - TERA 2P
	// * `tera-1p` - TERA 1P
	// * `110-punch` - 110 Punch
	// * `bnc` - BNC
	// * `f` - F Connector
	// * `n` - N Connector
	// * `mrj21` - MRJ21
	// * `fc` - FC
	// * `fc-pc` - FC/PC
	// * `fc-upc` - FC/UPC
	// * `fc-apc` - FC/APC
	// * `lc` - LC
	// * `lc-pc` - LC/PC
	// * `lc-upc` - LC/UPC
	// * `lc-apc` - LC/APC
	// * `mu` - MU
	// * `mu-pc` - MU/PC
	// * `mu-upc` - MU/UPC
	// * `mu-apc` - MU/APC
	// * `lsh` - LSH
	// * `lsh-pc` - LSH/PC
	// * `lsh-upc` - LSH/UPC
	// * `lsh-apc` - LSH/APC
	// * `lx5` - LX.5
	// * `lx5-pc` - LX.5/PC
	// * `lx5-upc` - LX.5/UPC
	// * `lx5-apc` - LX.5/APC
	// * `mpo` - MPO
	// * `mtrj` - MTRJ
	// * `sc` - SC
	// * `sc-pc` - SC/PC
	// * `sc-upc` - SC/UPC
	// * `sc-apc` - SC/APC
	// * `st` - ST
	// * `cs` - CS
	// * `sn` - SN
	// * `mdc` - MDC
	// * `sma-905` - SMA 905
	// * `sma-906` - SMA 906
	// * `urm-p2` - URM-P2
	// * `urm-p4` - URM-P4
	// * `urm-p8` - URM-P8
	// * `splice` - Splice
	// * `usb-a` - USB Type A
	// * `usb-b` - USB Type B
	// * `usb-c` - USB Type C
	// * `usb-mini-a` - USB Mini A
	// * `usb-mini-b` - USB Mini B
	// * `usb-micro-a` - USB Micro A
	// * `usb-micro-b` - USB Micro B
	// * `usb-micro-ab` - USB Micro AB
	// * `other` - Other
	// Required: true
	// Enum: ["8p8c","8p6c","8p4c","8p2c","6p6c","6p4c","6p2c","4p4c","4p2c","gg45","tera-4p","tera-2p","tera-1p","110-punch","bnc","f","n","mrj21","fc","fc-pc","fc-upc","fc-apc","lc","lc-pc","lc-upc","lc-apc","mu","mu-pc","mu-upc","mu-apc","lsh","lsh-pc","lsh-upc","lsh-apc","lx5","lx5-pc","lx5-upc","lx5-apc","mpo","mtrj","sc","sc-pc","sc-upc","sc-apc","st","cs","sn","mdc","sma-905","sma-906","urm-p2","urm-p4","urm-p8","splice","usb-a","usb-b","usb-c","usb-mini-a","usb-mini-b","usb-micro-a","usb-micro-b","usb-micro-ab","other"]
	Type *string `json:"type"`
}

// Validate validates this writable rear port template
func (m *WritableRearPortTemplate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateColor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFrontPorts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePositions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WritableRearPortTemplate) validateColor(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Color) { // not required
		return nil
	}

	if err := validate.MaxLength("color", "body", m.Color, 6); err != nil {
		return err
	}

	if err := validate.Pattern("color", "body", m.Color, `^[0-9a-f]{6}$`); err != nil {
		return err
	}

	return nil
}

func (m *WritableRearPortTemplate) validateDescription(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", m.Description, 200); err != nil {
		return err
	}

	return nil
}

func (m *WritableRearPortTemplate) validateFrontPorts(formats strfmt.Registry) error {
	if typeutils.IsZero(m.FrontPorts) { // not required
		return nil
	}

	for i := 0; i < len(m.FrontPorts); i++ {
		if typeutils.IsZero(m.FrontPorts[i]) { // not required
			continue
		}

		if m.FrontPorts[i] != nil {
			if err := m.FrontPorts[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("front_ports" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("front_ports" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *WritableRearPortTemplate) validateLabel(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Label) { // not required
		return nil
	}

	if err := validate.MaxLength("label", "body", m.Label, 64); err != nil {
		return err
	}

	return nil
}

func (m *WritableRearPortTemplate) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name, 64); err != nil {
		return err
	}

	return nil
}

func (m *WritableRearPortTemplate) validatePositions(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Positions) { // not required
		return nil
	}

	if err := validate.MinimumInt("positions", "body", m.Positions, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("positions", "body", m.Positions, 1024, false); err != nil {
		return err
	}

	return nil
}

var writableRearPortTemplateTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["8p8c","8p6c","8p4c","8p2c","6p6c","6p4c","6p2c","4p4c","4p2c","gg45","tera-4p","tera-2p","tera-1p","110-punch","bnc","f","n","mrj21","fc","fc-pc","fc-upc","fc-apc","lc","lc-pc","lc-upc","lc-apc","mu","mu-pc","mu-upc","mu-apc","lsh","lsh-pc","lsh-upc","lsh-apc","lx5","lx5-pc","lx5-upc","lx5-apc","mpo","mtrj","sc","sc-pc","sc-upc","sc-apc","st","cs","sn","mdc","sma-905","sma-906","urm-p2","urm-p4","urm-p8","splice","usb-a","usb-b","usb-c","usb-mini-a","usb-mini-b","usb-micro-a","usb-micro-b","usb-micro-ab","other"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		writableRearPortTemplateTypeTypePropEnum = append(writableRearPortTemplateTypeTypePropEnum, v)
	}
}

const (

	// WritableRearPortTemplateTypeNr8p8c captures enum value "8p8c"
	WritableRearPortTemplateTypeNr8p8c string = "8p8c"

	// WritableRearPortTemplateTypeNr8p6c captures enum value "8p6c"
	WritableRearPortTemplateTypeNr8p6c string = "8p6c"

	// WritableRearPortTemplateTypeNr8p4c captures enum value "8p4c"
	WritableRearPortTemplateTypeNr8p4c string = "8p4c"

	// WritableRearPortTemplateTypeNr8p2c captures enum value "8p2c"
	WritableRearPortTemplateTypeNr8p2c string = "8p2c"

	// WritableRearPortTemplateTypeNr6p6c captures enum value "6p6c"
	WritableRearPortTemplateTypeNr6p6c string = "6p6c"

	// WritableRearPortTemplateTypeNr6p4c captures enum value "6p4c"
	WritableRearPortTemplateTypeNr6p4c string = "6p4c"

	// WritableRearPortTemplateTypeNr6p2c captures enum value "6p2c"
	WritableRearPortTemplateTypeNr6p2c string = "6p2c"

	// WritableRearPortTemplateTypeNr4p4c captures enum value "4p4c"
	WritableRearPortTemplateTypeNr4p4c string = "4p4c"

	// WritableRearPortTemplateTypeNr4p2c captures enum value "4p2c"
	WritableRearPortTemplateTypeNr4p2c string = "4p2c"

	// WritableRearPortTemplateTypeGg45 captures enum value "gg45"
	WritableRearPortTemplateTypeGg45 string = "gg45"

	// WritableRearPortTemplateTypeTeraDash4p captures enum value "tera-4p"
	WritableRearPortTemplateTypeTeraDash4p string = "tera-4p"

	// WritableRearPortTemplateTypeTeraDash2p captures enum value "tera-2p"
	WritableRearPortTemplateTypeTeraDash2p string = "tera-2p"

	// WritableRearPortTemplateTypeTeraDash1p captures enum value "tera-1p"
	WritableRearPortTemplateTypeTeraDash1p string = "tera-1p"

	// WritableRearPortTemplateTypeNr110DashPunch captures enum value "110-punch"
	WritableRearPortTemplateTypeNr110DashPunch string = "110-punch"

	// WritableRearPortTemplateTypeBnc captures enum value "bnc"
	WritableRearPortTemplateTypeBnc string = "bnc"

	// WritableRearPortTemplateTypeF captures enum value "f"
	WritableRearPortTemplateTypeF string = "f"

	// WritableRearPortTemplateTypeN captures enum value "n"
	WritableRearPortTemplateTypeN string = "n"

	// WritableRearPortTemplateTypeMrj21 captures enum value "mrj21"
	WritableRearPortTemplateTypeMrj21 string = "mrj21"

	// WritableRearPortTemplateTypeFc captures enum value "fc"
	WritableRearPortTemplateTypeFc string = "fc"

	// WritableRearPortTemplateTypeFcDashPc captures enum value "fc-pc"
	WritableRearPortTemplateTypeFcDashPc string = "fc-pc"

	// WritableRearPortTemplateTypeFcDashUpc captures enum value "fc-upc"
	WritableRearPortTemplateTypeFcDashUpc string = "fc-upc"

	// WritableRearPortTemplateTypeFcDashApc captures enum value "fc-apc"
	WritableRearPortTemplateTypeFcDashApc string = "fc-apc"

	// WritableRearPortTemplateTypeLc captures enum value "lc"
	WritableRearPortTemplateTypeLc string = "lc"

	// WritableRearPortTemplateTypeLcDashPc captures enum value "lc-pc"
	WritableRearPortTemplateTypeLcDashPc string = "lc-pc"

	// WritableRearPortTemplateTypeLcDashUpc captures enum value "lc-upc"
	WritableRearPortTemplateTypeLcDashUpc string = "lc-upc"

	// WritableRearPortTemplateTypeLcDashApc captures enum value "lc-apc"
	WritableRearPortTemplateTypeLcDashApc string = "lc-apc"

	// WritableRearPortTemplateTypeMu captures enum value "mu"
	WritableRearPortTemplateTypeMu string = "mu"

	// WritableRearPortTemplateTypeMuDashPc captures enum value "mu-pc"
	WritableRearPortTemplateTypeMuDashPc string = "mu-pc"

	// WritableRearPortTemplateTypeMuDashUpc captures enum value "mu-upc"
	WritableRearPortTemplateTypeMuDashUpc string = "mu-upc"

	// WritableRearPortTemplateTypeMuDashApc captures enum value "mu-apc"
	WritableRearPortTemplateTypeMuDashApc string = "mu-apc"

	// WritableRearPortTemplateTypeLsh captures enum value "lsh"
	WritableRearPortTemplateTypeLsh string = "lsh"

	// WritableRearPortTemplateTypeLshDashPc captures enum value "lsh-pc"
	WritableRearPortTemplateTypeLshDashPc string = "lsh-pc"

	// WritableRearPortTemplateTypeLshDashUpc captures enum value "lsh-upc"
	WritableRearPortTemplateTypeLshDashUpc string = "lsh-upc"

	// WritableRearPortTemplateTypeLshDashApc captures enum value "lsh-apc"
	WritableRearPortTemplateTypeLshDashApc string = "lsh-apc"

	// WritableRearPortTemplateTypeLx5 captures enum value "lx5"
	WritableRearPortTemplateTypeLx5 string = "lx5"

	// WritableRearPortTemplateTypeLx5DashPc captures enum value "lx5-pc"
	WritableRearPortTemplateTypeLx5DashPc string = "lx5-pc"

	// WritableRearPortTemplateTypeLx5DashUpc captures enum value "lx5-upc"
	WritableRearPortTemplateTypeLx5DashUpc string = "lx5-upc"

	// WritableRearPortTemplateTypeLx5DashApc captures enum value "lx5-apc"
	WritableRearPortTemplateTypeLx5DashApc string = "lx5-apc"

	// WritableRearPortTemplateTypeMpo captures enum value "mpo"
	WritableRearPortTemplateTypeMpo string = "mpo"

	// WritableRearPortTemplateTypeMtrj captures enum value "mtrj"
	WritableRearPortTemplateTypeMtrj string = "mtrj"

	// WritableRearPortTemplateTypeSc captures enum value "sc"
	WritableRearPortTemplateTypeSc string = "sc"

	// WritableRearPortTemplateTypeScDashPc captures enum value "sc-pc"
	WritableRearPortTemplateTypeScDashPc string = "sc-pc"

	// WritableRearPortTemplateTypeScDashUpc captures enum value "sc-upc"
	WritableRearPortTemplateTypeScDashUpc string = "sc-upc"

	// WritableRearPortTemplateTypeScDashApc captures enum value "sc-apc"
	WritableRearPortTemplateTypeScDashApc string = "sc-apc"

	// WritableRearPortTemplateTypeSt captures enum value "st"
	WritableRearPortTemplateTypeSt string = "st"

	// WritableRearPortTemplateTypeCs captures enum value "cs"
	WritableRearPortTemplateTypeCs string = "cs"

	// WritableRearPortTemplateTypeSn captures enum value "sn"
	WritableRearPortTemplateTypeSn string = "sn"

	// WritableRearPortTemplateTypeMdc captures enum value "mdc"
	WritableRearPortTemplateTypeMdc string = "mdc"

	// WritableRearPortTemplateTypeSmaDash905 captures enum value "sma-905"
	WritableRearPortTemplateTypeSmaDash905 string = "sma-905"

	// WritableRearPortTemplateTypeSmaDash906 captures enum value "sma-906"
	WritableRearPortTemplateTypeSmaDash906 string = "sma-906"

	// WritableRearPortTemplateTypeUrmDashP2 captures enum value "urm-p2"
	WritableRearPortTemplateTypeUrmDashP2 string = "urm-p2"

	// WritableRearPortTemplateTypeUrmDashP4 captures enum value "urm-p4"
	WritableRearPortTemplateTypeUrmDashP4 string = "urm-p4"

	// WritableRearPortTemplateTypeUrmDashP8 captures enum value "urm-p8"
	WritableRearPortTemplateTypeUrmDashP8 string = "urm-p8"

	// WritableRearPortTemplateTypeSplice captures enum value "splice"
	WritableRearPortTemplateTypeSplice string = "splice"

	// WritableRearPortTemplateTypeUsbDasha captures enum value "usb-a"
	WritableRearPortTemplateTypeUsbDasha string = "usb-a"

	// WritableRearPortTemplateTypeUsbDashb captures enum value "usb-b"
	WritableRearPortTemplateTypeUsbDashb string = "usb-b"

	// WritableRearPortTemplateTypeUsbDashc captures enum value "usb-c"
	WritableRearPortTemplateTypeUsbDashc string = "usb-c"

	// WritableRearPortTemplateTypeUsbDashMiniDasha captures enum value "usb-mini-a"
	WritableRearPortTemplateTypeUsbDashMiniDasha string = "usb-mini-a"

	// WritableRearPortTemplateTypeUsbDashMiniDashb captures enum value "usb-mini-b"
	WritableRearPortTemplateTypeUsbDashMiniDashb string = "usb-mini-b"

	// WritableRearPortTemplateTypeUsbDashMicroDasha captures enum value "usb-micro-a"
	WritableRearPortTemplateTypeUsbDashMicroDasha string = "usb-micro-a"

	// WritableRearPortTemplateTypeUsbDashMicroDashb captures enum value "usb-micro-b"
	WritableRearPortTemplateTypeUsbDashMicroDashb string = "usb-micro-b"

	// WritableRearPortTemplateTypeUsbDashMicroDashAb captures enum value "usb-micro-ab"
	WritableRearPortTemplateTypeUsbDashMicroDashAb string = "usb-micro-ab"

	// WritableRearPortTemplateTypeOther captures enum value "other"
	WritableRearPortTemplateTypeOther string = "other"
)

// prop value enum
func (m *WritableRearPortTemplate) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, writableRearPortTemplateTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WritableRearPortTemplate) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this writable rear port template based on the context it is used
func (m *WritableRearPortTemplate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFrontPorts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WritableRearPortTemplate) contextValidateFrontPorts(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.FrontPorts); i++ {

		if m.FrontPorts[i] != nil {

			if typeutils.IsZero(m.FrontPorts[i]) { // not required
				return nil
			}

			if err := m.FrontPorts[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("front_ports" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("front_ports" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *WritableRearPortTemplate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WritableRearPortTemplate) UnmarshalBinary(b []byte) error {
	var res WritableRearPortTemplate
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
