// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package vpn

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewVpnL2vpnsPartialUpdateParams creates a new VpnL2vpnsPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVpnL2vpnsPartialUpdateParams() *VpnL2vpnsPartialUpdateParams {
	return NewVpnL2vpnsPartialUpdateParamsWithTimeout(cr.DefaultTimeout)
}

// NewVpnL2vpnsPartialUpdateParamsWithTimeout creates a new VpnL2vpnsPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewVpnL2vpnsPartialUpdateParamsWithTimeout(timeout time.Duration) *VpnL2vpnsPartialUpdateParams {
	return &VpnL2vpnsPartialUpdateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewVpnL2vpnsPartialUpdateParamsWithContext creates a new VpnL2vpnsPartialUpdateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnL2vpnsPartialUpdateParams].
func NewVpnL2vpnsPartialUpdateParamsWithContext(ctx context.Context) *VpnL2vpnsPartialUpdateParams {
	return &VpnL2vpnsPartialUpdateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewVpnL2vpnsPartialUpdateParamsWithHTTPClient creates a new VpnL2vpnsPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewVpnL2vpnsPartialUpdateParamsWithHTTPClient(client *http.Client) *VpnL2vpnsPartialUpdateParams {
	return &VpnL2vpnsPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
VpnL2vpnsPartialUpdateParams contains all the parameters to send to the API endpoint

	for the vpn l2vpns partial update operation.

	Typically these are written to a http.Request.
*/
type VpnL2vpnsPartialUpdateParams struct {

	// Data.
	Data *models.WritableL2VPN

	// ID.
	//
	// A unique integer value identifying this L2VPN.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the vpn l2vpns partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnL2vpnsPartialUpdateParams) WithDefaults() *VpnL2vpnsPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vpn l2vpns partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnL2vpnsPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vpn l2vpns partial update params.
func (o *VpnL2vpnsPartialUpdateParams) WithTimeout(timeout time.Duration) *VpnL2vpnsPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vpn l2vpns partial update params.
func (o *VpnL2vpnsPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the vpn l2vpns partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnL2vpnsPartialUpdateParams].
func (o *VpnL2vpnsPartialUpdateParams) WithContext(ctx context.Context) *VpnL2vpnsPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vpn l2vpns partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnL2vpnsPartialUpdateParams].
func (o *VpnL2vpnsPartialUpdateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the vpn l2vpns partial update params.
func (o *VpnL2vpnsPartialUpdateParams) WithHTTPClient(client *http.Client) *VpnL2vpnsPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vpn l2vpns partial update params.
func (o *VpnL2vpnsPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the vpn l2vpns partial update params.
func (o *VpnL2vpnsPartialUpdateParams) WithData(data *models.WritableL2VPN) *VpnL2vpnsPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the vpn l2vpns partial update params.
func (o *VpnL2vpnsPartialUpdateParams) SetData(data *models.WritableL2VPN) {
	o.Data = data
}

// WithID adds the id to the vpn l2vpns partial update params.
func (o *VpnL2vpnsPartialUpdateParams) WithID(id int64) *VpnL2vpnsPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the vpn l2vpns partial update params.
func (o *VpnL2vpnsPartialUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *VpnL2vpnsPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
