// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package vpn

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewVpnIpsecProfilesPartialUpdateParams creates a new VpnIpsecProfilesPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVpnIpsecProfilesPartialUpdateParams() *VpnIpsecProfilesPartialUpdateParams {
	return NewVpnIpsecProfilesPartialUpdateParamsWithTimeout(cr.DefaultTimeout)
}

// NewVpnIpsecProfilesPartialUpdateParamsWithTimeout creates a new VpnIpsecProfilesPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewVpnIpsecProfilesPartialUpdateParamsWithTimeout(timeout time.Duration) *VpnIpsecProfilesPartialUpdateParams {
	return &VpnIpsecProfilesPartialUpdateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewVpnIpsecProfilesPartialUpdateParamsWithContext creates a new VpnIpsecProfilesPartialUpdateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnIpsecProfilesPartialUpdateParams].
func NewVpnIpsecProfilesPartialUpdateParamsWithContext(ctx context.Context) *VpnIpsecProfilesPartialUpdateParams {
	return &VpnIpsecProfilesPartialUpdateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewVpnIpsecProfilesPartialUpdateParamsWithHTTPClient creates a new VpnIpsecProfilesPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewVpnIpsecProfilesPartialUpdateParamsWithHTTPClient(client *http.Client) *VpnIpsecProfilesPartialUpdateParams {
	return &VpnIpsecProfilesPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
VpnIpsecProfilesPartialUpdateParams contains all the parameters to send to the API endpoint

	for the vpn ipsec profiles partial update operation.

	Typically these are written to a http.Request.
*/
type VpnIpsecProfilesPartialUpdateParams struct {

	// Data.
	Data *models.WritableIPSecProfile

	// ID.
	//
	// A unique integer value identifying this IPSec profile.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the vpn ipsec profiles partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnIpsecProfilesPartialUpdateParams) WithDefaults() *VpnIpsecProfilesPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vpn ipsec profiles partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnIpsecProfilesPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vpn ipsec profiles partial update params.
func (o *VpnIpsecProfilesPartialUpdateParams) WithTimeout(timeout time.Duration) *VpnIpsecProfilesPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vpn ipsec profiles partial update params.
func (o *VpnIpsecProfilesPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the vpn ipsec profiles partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnIpsecProfilesPartialUpdateParams].
func (o *VpnIpsecProfilesPartialUpdateParams) WithContext(ctx context.Context) *VpnIpsecProfilesPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vpn ipsec profiles partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnIpsecProfilesPartialUpdateParams].
func (o *VpnIpsecProfilesPartialUpdateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the vpn ipsec profiles partial update params.
func (o *VpnIpsecProfilesPartialUpdateParams) WithHTTPClient(client *http.Client) *VpnIpsecProfilesPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vpn ipsec profiles partial update params.
func (o *VpnIpsecProfilesPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the vpn ipsec profiles partial update params.
func (o *VpnIpsecProfilesPartialUpdateParams) WithData(data *models.WritableIPSecProfile) *VpnIpsecProfilesPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the vpn ipsec profiles partial update params.
func (o *VpnIpsecProfilesPartialUpdateParams) SetData(data *models.WritableIPSecProfile) {
	o.Data = data
}

// WithID adds the id to the vpn ipsec profiles partial update params.
func (o *VpnIpsecProfilesPartialUpdateParams) WithID(id int64) *VpnIpsecProfilesPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the vpn ipsec profiles partial update params.
func (o *VpnIpsecProfilesPartialUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *VpnIpsecProfilesPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
