// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package vpn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewVpnIpsecProposalsListParams creates a new VpnIpsecProposalsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVpnIpsecProposalsListParams() *VpnIpsecProposalsListParams {
	return &VpnIpsecProposalsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVpnIpsecProposalsListParamsWithTimeout creates a new VpnIpsecProposalsListParams object
// with the ability to set a timeout on a request.
func NewVpnIpsecProposalsListParamsWithTimeout(timeout time.Duration) *VpnIpsecProposalsListParams {
	return &VpnIpsecProposalsListParams{
		timeout: timeout,
	}
}

// NewVpnIpsecProposalsListParamsWithContext creates a new VpnIpsecProposalsListParams object
// with the ability to set a context for a request.
func NewVpnIpsecProposalsListParamsWithContext(ctx context.Context) *VpnIpsecProposalsListParams {
	return &VpnIpsecProposalsListParams{
		Context: ctx,
	}
}

// NewVpnIpsecProposalsListParamsWithHTTPClient creates a new VpnIpsecProposalsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewVpnIpsecProposalsListParamsWithHTTPClient(client *http.Client) *VpnIpsecProposalsListParams {
	return &VpnIpsecProposalsListParams{
		HTTPClient: client,
	}
}

/*
VpnIpsecProposalsListParams contains all the parameters to send to the API endpoint

	for the vpn ipsec proposals list operation.

	Typically these are written to a http.Request.
*/
type VpnIpsecProposalsListParams struct {

	// AuthenticationAlgorithm.
	AuthenticationAlgorithm *string

	// Created.
	Created *string

	// Description.
	Description *string

	// EncryptionAlgorithm.
	EncryptionAlgorithm *string

	// ID.
	ID *string

	// LastUpdated.
	LastUpdated *string

	/* Limit.

	   Number of results to return per page.
	*/
	Limit *int64

	// Name.
	Name *string

	/* Offset.

	   The initial index from which to return the results.
	*/
	Offset *int64

	/* Ordering.

	   Which field to use when ordering the results.
	*/
	Ordering *string

	// Q.
	Q *string

	// Tag.
	Tag []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the vpn ipsec proposals list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnIpsecProposalsListParams) WithDefaults() *VpnIpsecProposalsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vpn ipsec proposals list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnIpsecProposalsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithTimeout(timeout time.Duration) *VpnIpsecProposalsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithContext(ctx context.Context) *VpnIpsecProposalsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithHTTPClient(client *http.Client) *VpnIpsecProposalsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthenticationAlgorithm adds the authenticationAlgorithm to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithAuthenticationAlgorithm(authenticationAlgorithm *string) *VpnIpsecProposalsListParams {
	o.SetAuthenticationAlgorithm(authenticationAlgorithm)
	return o
}

// SetAuthenticationAlgorithm adds the authenticationAlgorithm to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetAuthenticationAlgorithm(authenticationAlgorithm *string) {
	o.AuthenticationAlgorithm = authenticationAlgorithm
}

// WithCreated adds the created to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithCreated(created *string) *VpnIpsecProposalsListParams {
	o.SetCreated(created)
	return o
}

// SetCreated adds the created to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetCreated(created *string) {
	o.Created = created
}

// WithDescription adds the description to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithDescription(description *string) *VpnIpsecProposalsListParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetDescription(description *string) {
	o.Description = description
}

// WithEncryptionAlgorithm adds the encryptionAlgorithm to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithEncryptionAlgorithm(encryptionAlgorithm *string) *VpnIpsecProposalsListParams {
	o.SetEncryptionAlgorithm(encryptionAlgorithm)
	return o
}

// SetEncryptionAlgorithm adds the encryptionAlgorithm to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetEncryptionAlgorithm(encryptionAlgorithm *string) {
	o.EncryptionAlgorithm = encryptionAlgorithm
}

// WithID adds the id to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithID(id *string) *VpnIpsecProposalsListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetID(id *string) {
	o.ID = id
}

// WithLastUpdated adds the lastUpdated to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithLastUpdated(lastUpdated *string) *VpnIpsecProposalsListParams {
	o.SetLastUpdated(lastUpdated)
	return o
}

// SetLastUpdated adds the lastUpdated to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetLastUpdated(lastUpdated *string) {
	o.LastUpdated = lastUpdated
}

// WithLimit adds the limit to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithLimit(limit *int64) *VpnIpsecProposalsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithName(name *string) *VpnIpsecProposalsListParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithOffset(offset *int64) *VpnIpsecProposalsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithOrdering(ordering *string) *VpnIpsecProposalsListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WithQ adds the q to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithQ(q *string) *VpnIpsecProposalsListParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetQ(q *string) {
	o.Q = q
}

// WithTag adds the tag to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) WithTag(tag []string) *VpnIpsecProposalsListParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the vpn ipsec proposals list params
func (o *VpnIpsecProposalsListParams) SetTag(tag []string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *VpnIpsecProposalsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AuthenticationAlgorithm != nil {

		// query param authentication_algorithm
		var qrAuthenticationAlgorithm string

		if o.AuthenticationAlgorithm != nil {
			qrAuthenticationAlgorithm = *o.AuthenticationAlgorithm
		}
		qAuthenticationAlgorithm := qrAuthenticationAlgorithm
		if qAuthenticationAlgorithm != "" {

			if err := r.SetQueryParam("authentication_algorithm", qAuthenticationAlgorithm); err != nil {
				return err
			}
		}
	}

	if o.Created != nil {

		// query param created
		var qrCreated string

		if o.Created != nil {
			qrCreated = *o.Created
		}
		qCreated := qrCreated
		if qCreated != "" {

			if err := r.SetQueryParam("created", qCreated); err != nil {
				return err
			}
		}
	}

	if o.Description != nil {

		// query param description
		var qrDescription string

		if o.Description != nil {
			qrDescription = *o.Description
		}
		qDescription := qrDescription
		if qDescription != "" {

			if err := r.SetQueryParam("description", qDescription); err != nil {
				return err
			}
		}
	}

	if o.EncryptionAlgorithm != nil {

		// query param encryption_algorithm
		var qrEncryptionAlgorithm string

		if o.EncryptionAlgorithm != nil {
			qrEncryptionAlgorithm = *o.EncryptionAlgorithm
		}
		qEncryptionAlgorithm := qrEncryptionAlgorithm
		if qEncryptionAlgorithm != "" {

			if err := r.SetQueryParam("encryption_algorithm", qEncryptionAlgorithm); err != nil {
				return err
			}
		}
	}

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if o.LastUpdated != nil {

		// query param last_updated
		var qrLastUpdated string

		if o.LastUpdated != nil {
			qrLastUpdated = *o.LastUpdated
		}
		qLastUpdated := qrLastUpdated
		if qLastUpdated != "" {

			if err := r.SetQueryParam("last_updated", qLastUpdated); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string

		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {

			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if o.Tag != nil {

		// binding items for tag
		joinedTag := o.bindParamTag(reg)

		// query array param tag
		if err := r.SetQueryParam("tag", joinedTag...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamVpnIpsecProposalsList binds the parameter tag
func (o *VpnIpsecProposalsListParams) bindParamTag(formats strfmt.Registry) []string {
	tagIR := o.Tag

	var tagIC []string
	for _, tagIIR := range tagIR { // explode []string

		tagIIV := tagIIR // string as string
		tagIC = append(tagIC, tagIIV)
	}

	// items.CollectionFormat: "multi"
	tagIS := swag.JoinByFormat(tagIC, "multi")

	return tagIS
}
