// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package vpn

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// VpnIkeProposalsRetrieveReader is a Reader for the VpnIkeProposalsRetrieve structure.
type VpnIkeProposalsRetrieveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VpnIkeProposalsRetrieveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewVpnIkeProposalsRetrieveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVpnIkeProposalsRetrieveDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVpnIkeProposalsRetrieveOK creates a VpnIkeProposalsRetrieveOK with default headers values
func NewVpnIkeProposalsRetrieveOK() *VpnIkeProposalsRetrieveOK {
	return &VpnIkeProposalsRetrieveOK{}
}

// VpnIkeProposalsRetrieveOK describes a response with status code 200, with default header values.
//
// VpnIkeProposalsRetrieveOK vpn ike proposals retrieve o k
type VpnIkeProposalsRetrieveOK struct {
	Payload *models.IKEProposal
}

// IsSuccess returns true when this vpn ike proposals retrieve o k response has a 2xx status code
func (o *VpnIkeProposalsRetrieveOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this vpn ike proposals retrieve o k response has a 3xx status code
func (o *VpnIkeProposalsRetrieveOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vpn ike proposals retrieve o k response has a 4xx status code
func (o *VpnIkeProposalsRetrieveOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this vpn ike proposals retrieve o k response has a 5xx status code
func (o *VpnIkeProposalsRetrieveOK) IsServerError() bool {
	return false
}

// IsCode returns true when this vpn ike proposals retrieve o k response a status code equal to that given
func (o *VpnIkeProposalsRetrieveOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the vpn ike proposals retrieve o k response
func (o *VpnIkeProposalsRetrieveOK) Code() int {
	return 200
}

func (o *VpnIkeProposalsRetrieveOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vpn/ike-proposals/{id}/][%d] vpnIkeProposalsRetrieveOK %s", 200, payload)
}

func (o *VpnIkeProposalsRetrieveOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vpn/ike-proposals/{id}/][%d] vpnIkeProposalsRetrieveOK %s", 200, payload)
}

func (o *VpnIkeProposalsRetrieveOK) GetPayload() *models.IKEProposal {
	return o.Payload
}

func (o *VpnIkeProposalsRetrieveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IKEProposal)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewVpnIkeProposalsRetrieveDefault creates a VpnIkeProposalsRetrieveDefault with default headers values
func NewVpnIkeProposalsRetrieveDefault(code int) *VpnIkeProposalsRetrieveDefault {
	return &VpnIkeProposalsRetrieveDefault{
		_statusCode: code,
	}
}

// VpnIkeProposalsRetrieveDefault describes a response with status code -1, with default header values.
//
// VpnIkeProposalsRetrieveDefault vpn ike proposals retrieve default
type VpnIkeProposalsRetrieveDefault struct {
	_statusCode int

	Payload any
}

// IsSuccess returns true when this vpn ike proposals retrieve default response has a 2xx status code
func (o *VpnIkeProposalsRetrieveDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this vpn ike proposals retrieve default response has a 3xx status code
func (o *VpnIkeProposalsRetrieveDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this vpn ike proposals retrieve default response has a 4xx status code
func (o *VpnIkeProposalsRetrieveDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this vpn ike proposals retrieve default response has a 5xx status code
func (o *VpnIkeProposalsRetrieveDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this vpn ike proposals retrieve default response a status code equal to that given
func (o *VpnIkeProposalsRetrieveDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the vpn ike proposals retrieve default response
func (o *VpnIkeProposalsRetrieveDefault) Code() int {
	return o._statusCode
}

func (o *VpnIkeProposalsRetrieveDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vpn/ike-proposals/{id}/][%d] vpn_ike_proposals_retrieve default %s", o._statusCode, payload)
}

func (o *VpnIkeProposalsRetrieveDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vpn/ike-proposals/{id}/][%d] vpn_ike_proposals_retrieve default %s", o._statusCode, payload)
}

func (o *VpnIkeProposalsRetrieveDefault) GetPayload() any {
	return o.Payload
}

func (o *VpnIkeProposalsRetrieveDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
