// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package vpn

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewVpnTunnelGroupsPartialUpdateParams creates a new VpnTunnelGroupsPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVpnTunnelGroupsPartialUpdateParams() *VpnTunnelGroupsPartialUpdateParams {
	return NewVpnTunnelGroupsPartialUpdateParamsWithTimeout(cr.DefaultTimeout)
}

// NewVpnTunnelGroupsPartialUpdateParamsWithTimeout creates a new VpnTunnelGroupsPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewVpnTunnelGroupsPartialUpdateParamsWithTimeout(timeout time.Duration) *VpnTunnelGroupsPartialUpdateParams {
	return &VpnTunnelGroupsPartialUpdateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewVpnTunnelGroupsPartialUpdateParamsWithContext creates a new VpnTunnelGroupsPartialUpdateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnTunnelGroupsPartialUpdateParams].
func NewVpnTunnelGroupsPartialUpdateParamsWithContext(ctx context.Context) *VpnTunnelGroupsPartialUpdateParams {
	return &VpnTunnelGroupsPartialUpdateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewVpnTunnelGroupsPartialUpdateParamsWithHTTPClient creates a new VpnTunnelGroupsPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewVpnTunnelGroupsPartialUpdateParamsWithHTTPClient(client *http.Client) *VpnTunnelGroupsPartialUpdateParams {
	return &VpnTunnelGroupsPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
VpnTunnelGroupsPartialUpdateParams contains all the parameters to send to the API endpoint

	for the vpn tunnel groups partial update operation.

	Typically these are written to a http.Request.
*/
type VpnTunnelGroupsPartialUpdateParams struct {

	// Data.
	Data *models.WritableTunnelGroup

	// ID.
	//
	// A unique integer value identifying this tunnel group.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the vpn tunnel groups partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnTunnelGroupsPartialUpdateParams) WithDefaults() *VpnTunnelGroupsPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vpn tunnel groups partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnTunnelGroupsPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vpn tunnel groups partial update params.
func (o *VpnTunnelGroupsPartialUpdateParams) WithTimeout(timeout time.Duration) *VpnTunnelGroupsPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vpn tunnel groups partial update params.
func (o *VpnTunnelGroupsPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the vpn tunnel groups partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnTunnelGroupsPartialUpdateParams].
func (o *VpnTunnelGroupsPartialUpdateParams) WithContext(ctx context.Context) *VpnTunnelGroupsPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vpn tunnel groups partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnTunnelGroupsPartialUpdateParams].
func (o *VpnTunnelGroupsPartialUpdateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the vpn tunnel groups partial update params.
func (o *VpnTunnelGroupsPartialUpdateParams) WithHTTPClient(client *http.Client) *VpnTunnelGroupsPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vpn tunnel groups partial update params.
func (o *VpnTunnelGroupsPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the vpn tunnel groups partial update params.
func (o *VpnTunnelGroupsPartialUpdateParams) WithData(data *models.WritableTunnelGroup) *VpnTunnelGroupsPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the vpn tunnel groups partial update params.
func (o *VpnTunnelGroupsPartialUpdateParams) SetData(data *models.WritableTunnelGroup) {
	o.Data = data
}

// WithID adds the id to the vpn tunnel groups partial update params.
func (o *VpnTunnelGroupsPartialUpdateParams) WithID(id int64) *VpnTunnelGroupsPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the vpn tunnel groups partial update params.
func (o *VpnTunnelGroupsPartialUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *VpnTunnelGroupsPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
