// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package vpn

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewVpnIpsecProfilesDestroyParams creates a new VpnIpsecProfilesDestroyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVpnIpsecProfilesDestroyParams() *VpnIpsecProfilesDestroyParams {
	return NewVpnIpsecProfilesDestroyParamsWithTimeout(cr.DefaultTimeout)
}

// NewVpnIpsecProfilesDestroyParamsWithTimeout creates a new VpnIpsecProfilesDestroyParams object
// with the ability to set a timeout on a request.
func NewVpnIpsecProfilesDestroyParamsWithTimeout(timeout time.Duration) *VpnIpsecProfilesDestroyParams {
	return &VpnIpsecProfilesDestroyParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewVpnIpsecProfilesDestroyParamsWithContext creates a new VpnIpsecProfilesDestroyParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnIpsecProfilesDestroyParams].
func NewVpnIpsecProfilesDestroyParamsWithContext(ctx context.Context) *VpnIpsecProfilesDestroyParams {
	return &VpnIpsecProfilesDestroyParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewVpnIpsecProfilesDestroyParamsWithHTTPClient creates a new VpnIpsecProfilesDestroyParams object
// with the ability to set a custom HTTPClient for a request.
func NewVpnIpsecProfilesDestroyParamsWithHTTPClient(client *http.Client) *VpnIpsecProfilesDestroyParams {
	return &VpnIpsecProfilesDestroyParams{
		HTTPClient: client,
	}
}

/*
VpnIpsecProfilesDestroyParams contains all the parameters to send to the API endpoint

	for the vpn ipsec profiles destroy operation.

	Typically these are written to a http.Request.
*/
type VpnIpsecProfilesDestroyParams struct {

	// ID.
	//
	// A unique integer value identifying this IPSec profile.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the vpn ipsec profiles destroy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnIpsecProfilesDestroyParams) WithDefaults() *VpnIpsecProfilesDestroyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vpn ipsec profiles destroy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnIpsecProfilesDestroyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vpn ipsec profiles destroy params.
func (o *VpnIpsecProfilesDestroyParams) WithTimeout(timeout time.Duration) *VpnIpsecProfilesDestroyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vpn ipsec profiles destroy params.
func (o *VpnIpsecProfilesDestroyParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the vpn ipsec profiles destroy params.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnIpsecProfilesDestroyParams].
func (o *VpnIpsecProfilesDestroyParams) WithContext(ctx context.Context) *VpnIpsecProfilesDestroyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vpn ipsec profiles destroy params.
//
// Deprecated: use the operation call with context to pass the context instead of [VpnIpsecProfilesDestroyParams].
func (o *VpnIpsecProfilesDestroyParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the vpn ipsec profiles destroy params.
func (o *VpnIpsecProfilesDestroyParams) WithHTTPClient(client *http.Client) *VpnIpsecProfilesDestroyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vpn ipsec profiles destroy params.
func (o *VpnIpsecProfilesDestroyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the vpn ipsec profiles destroy params.
func (o *VpnIpsecProfilesDestroyParams) WithID(id int64) *VpnIpsecProfilesDestroyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the vpn ipsec profiles destroy params.
func (o *VpnIpsecProfilesDestroyParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *VpnIpsecProfilesDestroyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
