// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package vpn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/netbox/models"
)

// VpnIpsecProposalsCreateReader is a Reader for the VpnIpsecProposalsCreate structure.
type VpnIpsecProposalsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VpnIpsecProposalsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewVpnIpsecProposalsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVpnIpsecProposalsCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVpnIpsecProposalsCreateCreated creates a VpnIpsecProposalsCreateCreated with default headers values
func NewVpnIpsecProposalsCreateCreated() *VpnIpsecProposalsCreateCreated {
	return &VpnIpsecProposalsCreateCreated{}
}

/*
VpnIpsecProposalsCreateCreated describes a response with status code 201, with default header values.

VpnIpsecProposalsCreateCreated vpn ipsec proposals create created
*/
type VpnIpsecProposalsCreateCreated struct {
	Payload *models.IPSecProposal
}

// IsSuccess returns true when this vpn ipsec proposals create created response has a 2xx status code
func (o *VpnIpsecProposalsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this vpn ipsec proposals create created response has a 3xx status code
func (o *VpnIpsecProposalsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vpn ipsec proposals create created response has a 4xx status code
func (o *VpnIpsecProposalsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this vpn ipsec proposals create created response has a 5xx status code
func (o *VpnIpsecProposalsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this vpn ipsec proposals create created response a status code equal to that given
func (o *VpnIpsecProposalsCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the vpn ipsec proposals create created response
func (o *VpnIpsecProposalsCreateCreated) Code() int {
	return 201
}

func (o *VpnIpsecProposalsCreateCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /vpn/ipsec-proposals/][%d] vpnIpsecProposalsCreateCreated %s", 201, payload)
}

func (o *VpnIpsecProposalsCreateCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /vpn/ipsec-proposals/][%d] vpnIpsecProposalsCreateCreated %s", 201, payload)
}

func (o *VpnIpsecProposalsCreateCreated) GetPayload() *models.IPSecProposal {
	return o.Payload
}

func (o *VpnIpsecProposalsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IPSecProposal)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVpnIpsecProposalsCreateDefault creates a VpnIpsecProposalsCreateDefault with default headers values
func NewVpnIpsecProposalsCreateDefault(code int) *VpnIpsecProposalsCreateDefault {
	return &VpnIpsecProposalsCreateDefault{
		_statusCode: code,
	}
}

/*
VpnIpsecProposalsCreateDefault describes a response with status code -1, with default header values.

VpnIpsecProposalsCreateDefault vpn ipsec proposals create default
*/
type VpnIpsecProposalsCreateDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this vpn ipsec proposals create default response has a 2xx status code
func (o *VpnIpsecProposalsCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this vpn ipsec proposals create default response has a 3xx status code
func (o *VpnIpsecProposalsCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this vpn ipsec proposals create default response has a 4xx status code
func (o *VpnIpsecProposalsCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this vpn ipsec proposals create default response has a 5xx status code
func (o *VpnIpsecProposalsCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this vpn ipsec proposals create default response a status code equal to that given
func (o *VpnIpsecProposalsCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the vpn ipsec proposals create default response
func (o *VpnIpsecProposalsCreateDefault) Code() int {
	return o._statusCode
}

func (o *VpnIpsecProposalsCreateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /vpn/ipsec-proposals/][%d] vpn_ipsec-proposals_create default %s", o._statusCode, payload)
}

func (o *VpnIpsecProposalsCreateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /vpn/ipsec-proposals/][%d] vpn_ipsec-proposals_create default %s", o._statusCode, payload)
}

func (o *VpnIpsecProposalsCreateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *VpnIpsecProposalsCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
