// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package authentication_check

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAuthenticationCheckRetrieveParams creates a new AuthenticationCheckRetrieveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAuthenticationCheckRetrieveParams() *AuthenticationCheckRetrieveParams {
	return NewAuthenticationCheckRetrieveParamsWithTimeout(cr.DefaultTimeout)
}

// NewAuthenticationCheckRetrieveParamsWithTimeout creates a new AuthenticationCheckRetrieveParams object
// with the ability to set a timeout on a request.
func NewAuthenticationCheckRetrieveParamsWithTimeout(timeout time.Duration) *AuthenticationCheckRetrieveParams {
	return &AuthenticationCheckRetrieveParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewAuthenticationCheckRetrieveParamsWithContext creates a new AuthenticationCheckRetrieveParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [AuthenticationCheckRetrieveParams].
func NewAuthenticationCheckRetrieveParamsWithContext(ctx context.Context) *AuthenticationCheckRetrieveParams {
	return &AuthenticationCheckRetrieveParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewAuthenticationCheckRetrieveParamsWithHTTPClient creates a new AuthenticationCheckRetrieveParams object
// with the ability to set a custom HTTPClient for a request.
func NewAuthenticationCheckRetrieveParamsWithHTTPClient(client *http.Client) *AuthenticationCheckRetrieveParams {
	return &AuthenticationCheckRetrieveParams{
		HTTPClient: client,
	}
}

/*
AuthenticationCheckRetrieveParams contains all the parameters to send to the API endpoint

	for the authentication check retrieve operation.

	Typically these are written to a http.Request.
*/
type AuthenticationCheckRetrieveParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the authentication check retrieve params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthenticationCheckRetrieveParams) WithDefaults() *AuthenticationCheckRetrieveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the authentication check retrieve params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthenticationCheckRetrieveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the authentication check retrieve params.
func (o *AuthenticationCheckRetrieveParams) WithTimeout(timeout time.Duration) *AuthenticationCheckRetrieveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the authentication check retrieve params.
func (o *AuthenticationCheckRetrieveParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the authentication check retrieve params.
//
// Deprecated: use the operation call with context to pass the context instead of [AuthenticationCheckRetrieveParams].
func (o *AuthenticationCheckRetrieveParams) WithContext(ctx context.Context) *AuthenticationCheckRetrieveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the authentication check retrieve params.
//
// Deprecated: use the operation call with context to pass the context instead of [AuthenticationCheckRetrieveParams].
func (o *AuthenticationCheckRetrieveParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the authentication check retrieve params.
func (o *AuthenticationCheckRetrieveParams) WithHTTPClient(client *http.Client) *AuthenticationCheckRetrieveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the authentication check retrieve params.
func (o *AuthenticationCheckRetrieveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *AuthenticationCheckRetrieveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
