// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package extras

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExtrasSubscriptionsCreateParams creates a new ExtrasSubscriptionsCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExtrasSubscriptionsCreateParams() *ExtrasSubscriptionsCreateParams {
	return NewExtrasSubscriptionsCreateParamsWithTimeout(cr.DefaultTimeout)
}

// NewExtrasSubscriptionsCreateParamsWithTimeout creates a new ExtrasSubscriptionsCreateParams object
// with the ability to set a timeout on a request.
func NewExtrasSubscriptionsCreateParamsWithTimeout(timeout time.Duration) *ExtrasSubscriptionsCreateParams {
	return &ExtrasSubscriptionsCreateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewExtrasSubscriptionsCreateParamsWithContext creates a new ExtrasSubscriptionsCreateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasSubscriptionsCreateParams].
func NewExtrasSubscriptionsCreateParamsWithContext(ctx context.Context) *ExtrasSubscriptionsCreateParams {
	return &ExtrasSubscriptionsCreateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewExtrasSubscriptionsCreateParamsWithHTTPClient creates a new ExtrasSubscriptionsCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewExtrasSubscriptionsCreateParamsWithHTTPClient(client *http.Client) *ExtrasSubscriptionsCreateParams {
	return &ExtrasSubscriptionsCreateParams{
		HTTPClient: client,
	}
}

/*
ExtrasSubscriptionsCreateParams contains all the parameters to send to the API endpoint

	for the extras subscriptions create operation.

	Typically these are written to a http.Request.
*/
type ExtrasSubscriptionsCreateParams struct {

	// Data.
	Data *models.WritableSubscription

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the extras subscriptions create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasSubscriptionsCreateParams) WithDefaults() *ExtrasSubscriptionsCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the extras subscriptions create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasSubscriptionsCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the extras subscriptions create params.
func (o *ExtrasSubscriptionsCreateParams) WithTimeout(timeout time.Duration) *ExtrasSubscriptionsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the extras subscriptions create params.
func (o *ExtrasSubscriptionsCreateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the extras subscriptions create params.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasSubscriptionsCreateParams].
func (o *ExtrasSubscriptionsCreateParams) WithContext(ctx context.Context) *ExtrasSubscriptionsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the extras subscriptions create params.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasSubscriptionsCreateParams].
func (o *ExtrasSubscriptionsCreateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the extras subscriptions create params.
func (o *ExtrasSubscriptionsCreateParams) WithHTTPClient(client *http.Client) *ExtrasSubscriptionsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the extras subscriptions create params.
func (o *ExtrasSubscriptionsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the extras subscriptions create params.
func (o *ExtrasSubscriptionsCreateParams) WithData(data *models.WritableSubscription) *ExtrasSubscriptionsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the extras subscriptions create params.
func (o *ExtrasSubscriptionsCreateParams) SetData(data *models.WritableSubscription) {
	o.Data = data
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ExtrasSubscriptionsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
