// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package extras

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewExtrasImageAttachmentsDestroyParams creates a new ExtrasImageAttachmentsDestroyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExtrasImageAttachmentsDestroyParams() *ExtrasImageAttachmentsDestroyParams {
	return NewExtrasImageAttachmentsDestroyParamsWithTimeout(cr.DefaultTimeout)
}

// NewExtrasImageAttachmentsDestroyParamsWithTimeout creates a new ExtrasImageAttachmentsDestroyParams object
// with the ability to set a timeout on a request.
func NewExtrasImageAttachmentsDestroyParamsWithTimeout(timeout time.Duration) *ExtrasImageAttachmentsDestroyParams {
	return &ExtrasImageAttachmentsDestroyParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewExtrasImageAttachmentsDestroyParamsWithContext creates a new ExtrasImageAttachmentsDestroyParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasImageAttachmentsDestroyParams].
func NewExtrasImageAttachmentsDestroyParamsWithContext(ctx context.Context) *ExtrasImageAttachmentsDestroyParams {
	return &ExtrasImageAttachmentsDestroyParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewExtrasImageAttachmentsDestroyParamsWithHTTPClient creates a new ExtrasImageAttachmentsDestroyParams object
// with the ability to set a custom HTTPClient for a request.
func NewExtrasImageAttachmentsDestroyParamsWithHTTPClient(client *http.Client) *ExtrasImageAttachmentsDestroyParams {
	return &ExtrasImageAttachmentsDestroyParams{
		HTTPClient: client,
	}
}

/*
ExtrasImageAttachmentsDestroyParams contains all the parameters to send to the API endpoint

	for the extras image attachments destroy operation.

	Typically these are written to a http.Request.
*/
type ExtrasImageAttachmentsDestroyParams struct {

	// ID.
	//
	// A unique integer value identifying this image attachment.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the extras image attachments destroy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasImageAttachmentsDestroyParams) WithDefaults() *ExtrasImageAttachmentsDestroyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the extras image attachments destroy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasImageAttachmentsDestroyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the extras image attachments destroy params.
func (o *ExtrasImageAttachmentsDestroyParams) WithTimeout(timeout time.Duration) *ExtrasImageAttachmentsDestroyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the extras image attachments destroy params.
func (o *ExtrasImageAttachmentsDestroyParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the extras image attachments destroy params.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasImageAttachmentsDestroyParams].
func (o *ExtrasImageAttachmentsDestroyParams) WithContext(ctx context.Context) *ExtrasImageAttachmentsDestroyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the extras image attachments destroy params.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasImageAttachmentsDestroyParams].
func (o *ExtrasImageAttachmentsDestroyParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the extras image attachments destroy params.
func (o *ExtrasImageAttachmentsDestroyParams) WithHTTPClient(client *http.Client) *ExtrasImageAttachmentsDestroyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the extras image attachments destroy params.
func (o *ExtrasImageAttachmentsDestroyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the extras image attachments destroy params.
func (o *ExtrasImageAttachmentsDestroyParams) WithID(id int64) *ExtrasImageAttachmentsDestroyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the extras image attachments destroy params.
func (o *ExtrasImageAttachmentsDestroyParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ExtrasImageAttachmentsDestroyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
