// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package extras

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExtrasExportTemplatesSyncCreateReader is a Reader for the ExtrasExportTemplatesSyncCreate structure.
type ExtrasExportTemplatesSyncCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasExportTemplatesSyncCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewExtrasExportTemplatesSyncCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewExtrasExportTemplatesSyncCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExtrasExportTemplatesSyncCreateOK creates a ExtrasExportTemplatesSyncCreateOK with default headers values
func NewExtrasExportTemplatesSyncCreateOK() *ExtrasExportTemplatesSyncCreateOK {
	return &ExtrasExportTemplatesSyncCreateOK{}
}

// ExtrasExportTemplatesSyncCreateOK describes a response with status code 200, with default header values.
//
// ExtrasExportTemplatesSyncCreateOK extras export templates sync create o k
type ExtrasExportTemplatesSyncCreateOK struct {
	Payload *models.ExportTemplate
}

// IsSuccess returns true when this extras export templates sync create o k response has a 2xx status code
func (o *ExtrasExportTemplatesSyncCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras export templates sync create o k response has a 3xx status code
func (o *ExtrasExportTemplatesSyncCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras export templates sync create o k response has a 4xx status code
func (o *ExtrasExportTemplatesSyncCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras export templates sync create o k response has a 5xx status code
func (o *ExtrasExportTemplatesSyncCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this extras export templates sync create o k response a status code equal to that given
func (o *ExtrasExportTemplatesSyncCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the extras export templates sync create o k response
func (o *ExtrasExportTemplatesSyncCreateOK) Code() int {
	return 200
}

func (o *ExtrasExportTemplatesSyncCreateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /extras/export-templates/{id}/sync/][%d] extrasExportTemplatesSyncCreateOK %s", 200, payload)
}

func (o *ExtrasExportTemplatesSyncCreateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /extras/export-templates/{id}/sync/][%d] extrasExportTemplatesSyncCreateOK %s", 200, payload)
}

func (o *ExtrasExportTemplatesSyncCreateOK) GetPayload() *models.ExportTemplate {
	return o.Payload
}

func (o *ExtrasExportTemplatesSyncCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExportTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewExtrasExportTemplatesSyncCreateDefault creates a ExtrasExportTemplatesSyncCreateDefault with default headers values
func NewExtrasExportTemplatesSyncCreateDefault(code int) *ExtrasExportTemplatesSyncCreateDefault {
	return &ExtrasExportTemplatesSyncCreateDefault{
		_statusCode: code,
	}
}

// ExtrasExportTemplatesSyncCreateDefault describes a response with status code -1, with default header values.
//
// ExtrasExportTemplatesSyncCreateDefault extras export templates sync create default
type ExtrasExportTemplatesSyncCreateDefault struct {
	_statusCode int

	Payload any
}

// IsSuccess returns true when this extras export templates sync create default response has a 2xx status code
func (o *ExtrasExportTemplatesSyncCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this extras export templates sync create default response has a 3xx status code
func (o *ExtrasExportTemplatesSyncCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this extras export templates sync create default response has a 4xx status code
func (o *ExtrasExportTemplatesSyncCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this extras export templates sync create default response has a 5xx status code
func (o *ExtrasExportTemplatesSyncCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this extras export templates sync create default response a status code equal to that given
func (o *ExtrasExportTemplatesSyncCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the extras export templates sync create default response
func (o *ExtrasExportTemplatesSyncCreateDefault) Code() int {
	return o._statusCode
}

func (o *ExtrasExportTemplatesSyncCreateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /extras/export-templates/{id}/sync/][%d] extras_export_templates_sync_create default %s", o._statusCode, payload)
}

func (o *ExtrasExportTemplatesSyncCreateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /extras/export-templates/{id}/sync/][%d] extras_export_templates_sync_create default %s", o._statusCode, payload)
}

func (o *ExtrasExportTemplatesSyncCreateDefault) GetPayload() any {
	return o.Payload
}

func (o *ExtrasExportTemplatesSyncCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
