// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fbreckle/go-netbox/netbox/models"
)

// NewExtrasNotificationGroupsUpdateParams creates a new ExtrasNotificationGroupsUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExtrasNotificationGroupsUpdateParams() *ExtrasNotificationGroupsUpdateParams {
	return &ExtrasNotificationGroupsUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExtrasNotificationGroupsUpdateParamsWithTimeout creates a new ExtrasNotificationGroupsUpdateParams object
// with the ability to set a timeout on a request.
func NewExtrasNotificationGroupsUpdateParamsWithTimeout(timeout time.Duration) *ExtrasNotificationGroupsUpdateParams {
	return &ExtrasNotificationGroupsUpdateParams{
		timeout: timeout,
	}
}

// NewExtrasNotificationGroupsUpdateParamsWithContext creates a new ExtrasNotificationGroupsUpdateParams object
// with the ability to set a context for a request.
func NewExtrasNotificationGroupsUpdateParamsWithContext(ctx context.Context) *ExtrasNotificationGroupsUpdateParams {
	return &ExtrasNotificationGroupsUpdateParams{
		Context: ctx,
	}
}

// NewExtrasNotificationGroupsUpdateParamsWithHTTPClient creates a new ExtrasNotificationGroupsUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewExtrasNotificationGroupsUpdateParamsWithHTTPClient(client *http.Client) *ExtrasNotificationGroupsUpdateParams {
	return &ExtrasNotificationGroupsUpdateParams{
		HTTPClient: client,
	}
}

/*
ExtrasNotificationGroupsUpdateParams contains all the parameters to send to the API endpoint

	for the extras notification groups update operation.

	Typically these are written to a http.Request.
*/
type ExtrasNotificationGroupsUpdateParams struct {

	// Data.
	Data *models.WritableNotificationGroup

	/* ID.

	   A unique integer value identifying this notification group.
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the extras notification groups update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasNotificationGroupsUpdateParams) WithDefaults() *ExtrasNotificationGroupsUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the extras notification groups update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasNotificationGroupsUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the extras notification groups update params
func (o *ExtrasNotificationGroupsUpdateParams) WithTimeout(timeout time.Duration) *ExtrasNotificationGroupsUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the extras notification groups update params
func (o *ExtrasNotificationGroupsUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the extras notification groups update params
func (o *ExtrasNotificationGroupsUpdateParams) WithContext(ctx context.Context) *ExtrasNotificationGroupsUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the extras notification groups update params
func (o *ExtrasNotificationGroupsUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the extras notification groups update params
func (o *ExtrasNotificationGroupsUpdateParams) WithHTTPClient(client *http.Client) *ExtrasNotificationGroupsUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the extras notification groups update params
func (o *ExtrasNotificationGroupsUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the extras notification groups update params
func (o *ExtrasNotificationGroupsUpdateParams) WithData(data *models.WritableNotificationGroup) *ExtrasNotificationGroupsUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the extras notification groups update params
func (o *ExtrasNotificationGroupsUpdateParams) SetData(data *models.WritableNotificationGroup) {
	o.Data = data
}

// WithID adds the id to the extras notification groups update params
func (o *ExtrasNotificationGroupsUpdateParams) WithID(id int64) *ExtrasNotificationGroupsUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the extras notification groups update params
func (o *ExtrasNotificationGroupsUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ExtrasNotificationGroupsUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
