// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package extras

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExtrasWebhooksRetrieveReader is a Reader for the ExtrasWebhooksRetrieve structure.
type ExtrasWebhooksRetrieveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasWebhooksRetrieveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewExtrasWebhooksRetrieveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewExtrasWebhooksRetrieveDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExtrasWebhooksRetrieveOK creates a ExtrasWebhooksRetrieveOK with default headers values
func NewExtrasWebhooksRetrieveOK() *ExtrasWebhooksRetrieveOK {
	return &ExtrasWebhooksRetrieveOK{}
}

// ExtrasWebhooksRetrieveOK describes a response with status code 200, with default header values.
//
// ExtrasWebhooksRetrieveOK extras webhooks retrieve o k
type ExtrasWebhooksRetrieveOK struct {
	Payload *models.Webhook
}

// IsSuccess returns true when this extras webhooks retrieve o k response has a 2xx status code
func (o *ExtrasWebhooksRetrieveOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras webhooks retrieve o k response has a 3xx status code
func (o *ExtrasWebhooksRetrieveOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras webhooks retrieve o k response has a 4xx status code
func (o *ExtrasWebhooksRetrieveOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras webhooks retrieve o k response has a 5xx status code
func (o *ExtrasWebhooksRetrieveOK) IsServerError() bool {
	return false
}

// IsCode returns true when this extras webhooks retrieve o k response a status code equal to that given
func (o *ExtrasWebhooksRetrieveOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the extras webhooks retrieve o k response
func (o *ExtrasWebhooksRetrieveOK) Code() int {
	return 200
}

func (o *ExtrasWebhooksRetrieveOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /extras/webhooks/{id}/][%d] extrasWebhooksRetrieveOK %s", 200, payload)
}

func (o *ExtrasWebhooksRetrieveOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /extras/webhooks/{id}/][%d] extrasWebhooksRetrieveOK %s", 200, payload)
}

func (o *ExtrasWebhooksRetrieveOK) GetPayload() *models.Webhook {
	return o.Payload
}

func (o *ExtrasWebhooksRetrieveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Webhook)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewExtrasWebhooksRetrieveDefault creates a ExtrasWebhooksRetrieveDefault with default headers values
func NewExtrasWebhooksRetrieveDefault(code int) *ExtrasWebhooksRetrieveDefault {
	return &ExtrasWebhooksRetrieveDefault{
		_statusCode: code,
	}
}

// ExtrasWebhooksRetrieveDefault describes a response with status code -1, with default header values.
//
// ExtrasWebhooksRetrieveDefault extras webhooks retrieve default
type ExtrasWebhooksRetrieveDefault struct {
	_statusCode int

	Payload any
}

// IsSuccess returns true when this extras webhooks retrieve default response has a 2xx status code
func (o *ExtrasWebhooksRetrieveDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this extras webhooks retrieve default response has a 3xx status code
func (o *ExtrasWebhooksRetrieveDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this extras webhooks retrieve default response has a 4xx status code
func (o *ExtrasWebhooksRetrieveDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this extras webhooks retrieve default response has a 5xx status code
func (o *ExtrasWebhooksRetrieveDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this extras webhooks retrieve default response a status code equal to that given
func (o *ExtrasWebhooksRetrieveDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the extras webhooks retrieve default response
func (o *ExtrasWebhooksRetrieveDefault) Code() int {
	return o._statusCode
}

func (o *ExtrasWebhooksRetrieveDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /extras/webhooks/{id}/][%d] extras_webhooks_retrieve default %s", o._statusCode, payload)
}

func (o *ExtrasWebhooksRetrieveDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /extras/webhooks/{id}/][%d] extras_webhooks_retrieve default %s", o._statusCode, payload)
}

func (o *ExtrasWebhooksRetrieveDefault) GetPayload() any {
	return o.Payload
}

func (o *ExtrasWebhooksRetrieveDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
