// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package extras

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewExtrasCustomFieldChoiceSetsPartialUpdateParams creates a new ExtrasCustomFieldChoiceSetsPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExtrasCustomFieldChoiceSetsPartialUpdateParams() *ExtrasCustomFieldChoiceSetsPartialUpdateParams {
	return NewExtrasCustomFieldChoiceSetsPartialUpdateParamsWithTimeout(cr.DefaultTimeout)
}

// NewExtrasCustomFieldChoiceSetsPartialUpdateParamsWithTimeout creates a new ExtrasCustomFieldChoiceSetsPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewExtrasCustomFieldChoiceSetsPartialUpdateParamsWithTimeout(timeout time.Duration) *ExtrasCustomFieldChoiceSetsPartialUpdateParams {
	return &ExtrasCustomFieldChoiceSetsPartialUpdateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewExtrasCustomFieldChoiceSetsPartialUpdateParamsWithContext creates a new ExtrasCustomFieldChoiceSetsPartialUpdateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasCustomFieldChoiceSetsPartialUpdateParams].
func NewExtrasCustomFieldChoiceSetsPartialUpdateParamsWithContext(ctx context.Context) *ExtrasCustomFieldChoiceSetsPartialUpdateParams {
	return &ExtrasCustomFieldChoiceSetsPartialUpdateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewExtrasCustomFieldChoiceSetsPartialUpdateParamsWithHTTPClient creates a new ExtrasCustomFieldChoiceSetsPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewExtrasCustomFieldChoiceSetsPartialUpdateParamsWithHTTPClient(client *http.Client) *ExtrasCustomFieldChoiceSetsPartialUpdateParams {
	return &ExtrasCustomFieldChoiceSetsPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
ExtrasCustomFieldChoiceSetsPartialUpdateParams contains all the parameters to send to the API endpoint

	for the extras custom field choice sets partial update operation.

	Typically these are written to a http.Request.
*/
type ExtrasCustomFieldChoiceSetsPartialUpdateParams struct {

	// Data.
	Data *models.WritableCustomFieldChoiceSet

	// ID.
	//
	// A unique integer value identifying this custom field choice set.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the extras custom field choice sets partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) WithDefaults() *ExtrasCustomFieldChoiceSetsPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the extras custom field choice sets partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the extras custom field choice sets partial update params.
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) WithTimeout(timeout time.Duration) *ExtrasCustomFieldChoiceSetsPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the extras custom field choice sets partial update params.
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the extras custom field choice sets partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasCustomFieldChoiceSetsPartialUpdateParams].
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) WithContext(ctx context.Context) *ExtrasCustomFieldChoiceSetsPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the extras custom field choice sets partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasCustomFieldChoiceSetsPartialUpdateParams].
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the extras custom field choice sets partial update params.
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) WithHTTPClient(client *http.Client) *ExtrasCustomFieldChoiceSetsPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the extras custom field choice sets partial update params.
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the extras custom field choice sets partial update params.
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) WithData(data *models.WritableCustomFieldChoiceSet) *ExtrasCustomFieldChoiceSetsPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the extras custom field choice sets partial update params.
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) SetData(data *models.WritableCustomFieldChoiceSet) {
	o.Data = data
}

// WithID adds the id to the extras custom field choice sets partial update params.
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) WithID(id int64) *ExtrasCustomFieldChoiceSetsPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the extras custom field choice sets partial update params.
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ExtrasCustomFieldChoiceSetsPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
