// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package extras

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
	"github.com/go-openapi/swag/stringutils"
)

// NewExtrasScriptsListParams creates a new ExtrasScriptsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExtrasScriptsListParams() *ExtrasScriptsListParams {
	return NewExtrasScriptsListParamsWithTimeout(cr.DefaultTimeout)
}

// NewExtrasScriptsListParamsWithTimeout creates a new ExtrasScriptsListParams object
// with the ability to set a timeout on a request.
func NewExtrasScriptsListParamsWithTimeout(timeout time.Duration) *ExtrasScriptsListParams {
	return &ExtrasScriptsListParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewExtrasScriptsListParamsWithContext creates a new ExtrasScriptsListParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasScriptsListParams].
func NewExtrasScriptsListParamsWithContext(ctx context.Context) *ExtrasScriptsListParams {
	return &ExtrasScriptsListParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewExtrasScriptsListParamsWithHTTPClient creates a new ExtrasScriptsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewExtrasScriptsListParamsWithHTTPClient(client *http.Client) *ExtrasScriptsListParams {
	return &ExtrasScriptsListParams{
		HTTPClient: client,
	}
}

/*
ExtrasScriptsListParams contains all the parameters to send to the API endpoint

	for the extras scripts list operation.

	Typically these are written to a http.Request.
*/
type ExtrasScriptsListParams struct {

	// ID.
	ID []int64

	// IDEmpty.
	IDEmpty *bool

	// IDGt.
	IDGt []int64

	// IDGte.
	IDGte []int64

	// IDLt.
	IDLt []int64

	// IDLte.
	IDLte []int64

	// IDn.
	IDn []int64

	// IsExecutable.
	IsExecutable *bool

	// Limit.
	//
	// Number of results to return per page.
	Limit *int64

	// ModuleID.
	//
	// Script module (ID)
	ModuleID []int64

	// ModuleIDn.
	//
	// Script module (ID)
	ModuleIDn []int64

	// Name.
	Name []string

	// NameEmpty.
	NameEmpty *bool

	// NameIc.
	NameIc []string

	// NameIe.
	NameIe []string

	// NameIew.
	NameIew []string

	// NameIregex.
	NameIregex []string

	// NameIsw.
	NameIsw []string

	// Namen.
	Namen []string

	// NameNic.
	NameNic []string

	// NameNie.
	NameNie []string

	// NameNiew.
	NameNiew []string

	// NameNisw.
	NameNisw []string

	// NameRegex.
	NameRegex []string

	// Offset.
	//
	// The initial index from which to return the results.
	Offset *int64

	// Ordering.
	//
	// Which field to use when ordering the results.
	Ordering *string

	// Q.
	//
	// Search
	Q *string

	// Start.
	//
	// Cursor-based pagination: return results with pk >= start, ordered by pk. Mutually exclusive with offset.
	Start *int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the extras scripts list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasScriptsListParams) WithDefaults() *ExtrasScriptsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the extras scripts list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasScriptsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithTimeout(timeout time.Duration) *ExtrasScriptsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the extras scripts list params.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasScriptsListParams].
func (o *ExtrasScriptsListParams) WithContext(ctx context.Context) *ExtrasScriptsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the extras scripts list params.
//
// Deprecated: use the operation call with context to pass the context instead of [ExtrasScriptsListParams].
func (o *ExtrasScriptsListParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithHTTPClient(client *http.Client) *ExtrasScriptsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithID(id []int64) *ExtrasScriptsListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetID(id []int64) {
	o.ID = id
}

// WithIDEmpty adds the idEmpty to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithIDEmpty(idEmpty *bool) *ExtrasScriptsListParams {
	o.SetIDEmpty(idEmpty)
	return o
}

// SetIDEmpty adds the idEmpty to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetIDEmpty(idEmpty *bool) {
	o.IDEmpty = idEmpty
}

// WithIDGt adds the idGt to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithIDGt(idGt []int64) *ExtrasScriptsListParams {
	o.SetIDGt(idGt)
	return o
}

// SetIDGt adds the idGt to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetIDGt(idGt []int64) {
	o.IDGt = idGt
}

// WithIDGte adds the idGte to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithIDGte(idGte []int64) *ExtrasScriptsListParams {
	o.SetIDGte(idGte)
	return o
}

// SetIDGte adds the idGte to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetIDGte(idGte []int64) {
	o.IDGte = idGte
}

// WithIDLt adds the idLt to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithIDLt(idLt []int64) *ExtrasScriptsListParams {
	o.SetIDLt(idLt)
	return o
}

// SetIDLt adds the idLt to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetIDLt(idLt []int64) {
	o.IDLt = idLt
}

// WithIDLte adds the idLte to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithIDLte(idLte []int64) *ExtrasScriptsListParams {
	o.SetIDLte(idLte)
	return o
}

// SetIDLte adds the idLte to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetIDLte(idLte []int64) {
	o.IDLte = idLte
}

// WithIDn adds the idn to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithIDn(idn []int64) *ExtrasScriptsListParams {
	o.SetIDn(idn)
	return o
}

// SetIDn adds the idN to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetIDn(idn []int64) {
	o.IDn = idn
}

// WithIsExecutable adds the isExecutable to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithIsExecutable(isExecutable *bool) *ExtrasScriptsListParams {
	o.SetIsExecutable(isExecutable)
	return o
}

// SetIsExecutable adds the isExecutable to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetIsExecutable(isExecutable *bool) {
	o.IsExecutable = isExecutable
}

// WithLimit adds the limit to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithLimit(limit *int64) *ExtrasScriptsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithModuleID adds the moduleID to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithModuleID(moduleID []int64) *ExtrasScriptsListParams {
	o.SetModuleID(moduleID)
	return o
}

// SetModuleID adds the moduleId to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetModuleID(moduleID []int64) {
	o.ModuleID = moduleID
}

// WithModuleIDn adds the moduleIDn to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithModuleIDn(moduleIDn []int64) *ExtrasScriptsListParams {
	o.SetModuleIDn(moduleIDn)
	return o
}

// SetModuleIDn adds the moduleIdN to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetModuleIDn(moduleIDn []int64) {
	o.ModuleIDn = moduleIDn
}

// WithName adds the name to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithName(name []string) *ExtrasScriptsListParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetName(name []string) {
	o.Name = name
}

// WithNameEmpty adds the nameEmpty to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNameEmpty(nameEmpty *bool) *ExtrasScriptsListParams {
	o.SetNameEmpty(nameEmpty)
	return o
}

// SetNameEmpty adds the nameEmpty to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNameEmpty(nameEmpty *bool) {
	o.NameEmpty = nameEmpty
}

// WithNameIc adds the nameIc to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNameIc(nameIc []string) *ExtrasScriptsListParams {
	o.SetNameIc(nameIc)
	return o
}

// SetNameIc adds the nameIc to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNameIc(nameIc []string) {
	o.NameIc = nameIc
}

// WithNameIe adds the nameIe to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNameIe(nameIe []string) *ExtrasScriptsListParams {
	o.SetNameIe(nameIe)
	return o
}

// SetNameIe adds the nameIe to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNameIe(nameIe []string) {
	o.NameIe = nameIe
}

// WithNameIew adds the nameIew to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNameIew(nameIew []string) *ExtrasScriptsListParams {
	o.SetNameIew(nameIew)
	return o
}

// SetNameIew adds the nameIew to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNameIew(nameIew []string) {
	o.NameIew = nameIew
}

// WithNameIregex adds the nameIregex to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNameIregex(nameIregex []string) *ExtrasScriptsListParams {
	o.SetNameIregex(nameIregex)
	return o
}

// SetNameIregex adds the nameIregex to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNameIregex(nameIregex []string) {
	o.NameIregex = nameIregex
}

// WithNameIsw adds the nameIsw to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNameIsw(nameIsw []string) *ExtrasScriptsListParams {
	o.SetNameIsw(nameIsw)
	return o
}

// SetNameIsw adds the nameIsw to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNameIsw(nameIsw []string) {
	o.NameIsw = nameIsw
}

// WithNamen adds the namen to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNamen(namen []string) *ExtrasScriptsListParams {
	o.SetNamen(namen)
	return o
}

// SetNamen adds the nameN to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNamen(namen []string) {
	o.Namen = namen
}

// WithNameNic adds the nameNic to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNameNic(nameNic []string) *ExtrasScriptsListParams {
	o.SetNameNic(nameNic)
	return o
}

// SetNameNic adds the nameNic to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNameNic(nameNic []string) {
	o.NameNic = nameNic
}

// WithNameNie adds the nameNie to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNameNie(nameNie []string) *ExtrasScriptsListParams {
	o.SetNameNie(nameNie)
	return o
}

// SetNameNie adds the nameNie to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNameNie(nameNie []string) {
	o.NameNie = nameNie
}

// WithNameNiew adds the nameNiew to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNameNiew(nameNiew []string) *ExtrasScriptsListParams {
	o.SetNameNiew(nameNiew)
	return o
}

// SetNameNiew adds the nameNiew to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNameNiew(nameNiew []string) {
	o.NameNiew = nameNiew
}

// WithNameNisw adds the nameNisw to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNameNisw(nameNisw []string) *ExtrasScriptsListParams {
	o.SetNameNisw(nameNisw)
	return o
}

// SetNameNisw adds the nameNisw to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNameNisw(nameNisw []string) {
	o.NameNisw = nameNisw
}

// WithNameRegex adds the nameRegex to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithNameRegex(nameRegex []string) *ExtrasScriptsListParams {
	o.SetNameRegex(nameRegex)
	return o
}

// SetNameRegex adds the nameRegex to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetNameRegex(nameRegex []string) {
	o.NameRegex = nameRegex
}

// WithOffset adds the offset to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithOffset(offset *int64) *ExtrasScriptsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithOrdering(ordering *string) *ExtrasScriptsListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WithQ adds the q to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithQ(q *string) *ExtrasScriptsListParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetQ(q *string) {
	o.Q = q
}

// WithStart adds the start to the extras scripts list params.
func (o *ExtrasScriptsListParams) WithStart(start *int64) *ExtrasScriptsListParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the extras scripts list params.
func (o *ExtrasScriptsListParams) SetStart(start *int64) {
	o.Start = start
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ExtrasScriptsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// binding items for id
		joinedID := o.bindParamID(reg)

		// query array param id
		if err := r.SetQueryParam("id", joinedID...); err != nil {
			return err
		}
	}

	if o.IDEmpty != nil {

		// query param id__empty
		var qrIDEmpty bool

		if o.IDEmpty != nil {
			qrIDEmpty = *o.IDEmpty
		}
		qIDEmpty := conv.FormatBool(qrIDEmpty)
		if qIDEmpty != "" {

			if err := r.SetQueryParam("id__empty", qIDEmpty); err != nil {
				return err
			}
		}
	}

	if o.IDGt != nil {

		// binding items for id__gt
		joinedIDGt := o.bindParamIDGt(reg)

		// query array param id__gt
		if err := r.SetQueryParam("id__gt", joinedIDGt...); err != nil {
			return err
		}
	}

	if o.IDGte != nil {

		// binding items for id__gte
		joinedIDGte := o.bindParamIDGte(reg)

		// query array param id__gte
		if err := r.SetQueryParam("id__gte", joinedIDGte...); err != nil {
			return err
		}
	}

	if o.IDLt != nil {

		// binding items for id__lt
		joinedIDLt := o.bindParamIDLt(reg)

		// query array param id__lt
		if err := r.SetQueryParam("id__lt", joinedIDLt...); err != nil {
			return err
		}
	}

	if o.IDLte != nil {

		// binding items for id__lte
		joinedIDLte := o.bindParamIDLte(reg)

		// query array param id__lte
		if err := r.SetQueryParam("id__lte", joinedIDLte...); err != nil {
			return err
		}
	}

	if o.IDn != nil {

		// binding items for id__n
		joinedIDn := o.bindParamIDn(reg)

		// query array param id__n
		if err := r.SetQueryParam("id__n", joinedIDn...); err != nil {
			return err
		}
	}

	if o.IsExecutable != nil {

		// query param is_executable
		var qrIsExecutable bool

		if o.IsExecutable != nil {
			qrIsExecutable = *o.IsExecutable
		}
		qIsExecutable := conv.FormatBool(qrIsExecutable)
		if qIsExecutable != "" {

			if err := r.SetQueryParam("is_executable", qIsExecutable); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := conv.FormatInteger(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.ModuleID != nil {

		// binding items for module_id
		joinedModuleID := o.bindParamModuleID(reg)

		// query array param module_id
		if err := r.SetQueryParam("module_id", joinedModuleID...); err != nil {
			return err
		}
	}

	if o.ModuleIDn != nil {

		// binding items for module_id__n
		joinedModuleIDn := o.bindParamModuleIDn(reg)

		// query array param module_id__n
		if err := r.SetQueryParam("module_id__n", joinedModuleIDn...); err != nil {
			return err
		}
	}

	if o.Name != nil {

		// binding items for name
		joinedName := o.bindParamName(reg)

		// query array param name
		if err := r.SetQueryParam("name", joinedName...); err != nil {
			return err
		}
	}

	if o.NameEmpty != nil {

		// query param name__empty
		var qrNameEmpty bool

		if o.NameEmpty != nil {
			qrNameEmpty = *o.NameEmpty
		}
		qNameEmpty := conv.FormatBool(qrNameEmpty)
		if qNameEmpty != "" {

			if err := r.SetQueryParam("name__empty", qNameEmpty); err != nil {
				return err
			}
		}
	}

	if o.NameIc != nil {

		// binding items for name__ic
		joinedNameIc := o.bindParamNameIc(reg)

		// query array param name__ic
		if err := r.SetQueryParam("name__ic", joinedNameIc...); err != nil {
			return err
		}
	}

	if o.NameIe != nil {

		// binding items for name__ie
		joinedNameIe := o.bindParamNameIe(reg)

		// query array param name__ie
		if err := r.SetQueryParam("name__ie", joinedNameIe...); err != nil {
			return err
		}
	}

	if o.NameIew != nil {

		// binding items for name__iew
		joinedNameIew := o.bindParamNameIew(reg)

		// query array param name__iew
		if err := r.SetQueryParam("name__iew", joinedNameIew...); err != nil {
			return err
		}
	}

	if o.NameIregex != nil {

		// binding items for name__iregex
		joinedNameIregex := o.bindParamNameIregex(reg)

		// query array param name__iregex
		if err := r.SetQueryParam("name__iregex", joinedNameIregex...); err != nil {
			return err
		}
	}

	if o.NameIsw != nil {

		// binding items for name__isw
		joinedNameIsw := o.bindParamNameIsw(reg)

		// query array param name__isw
		if err := r.SetQueryParam("name__isw", joinedNameIsw...); err != nil {
			return err
		}
	}

	if o.Namen != nil {

		// binding items for name__n
		joinedNamen := o.bindParamNamen(reg)

		// query array param name__n
		if err := r.SetQueryParam("name__n", joinedNamen...); err != nil {
			return err
		}
	}

	if o.NameNic != nil {

		// binding items for name__nic
		joinedNameNic := o.bindParamNameNic(reg)

		// query array param name__nic
		if err := r.SetQueryParam("name__nic", joinedNameNic...); err != nil {
			return err
		}
	}

	if o.NameNie != nil {

		// binding items for name__nie
		joinedNameNie := o.bindParamNameNie(reg)

		// query array param name__nie
		if err := r.SetQueryParam("name__nie", joinedNameNie...); err != nil {
			return err
		}
	}

	if o.NameNiew != nil {

		// binding items for name__niew
		joinedNameNiew := o.bindParamNameNiew(reg)

		// query array param name__niew
		if err := r.SetQueryParam("name__niew", joinedNameNiew...); err != nil {
			return err
		}
	}

	if o.NameNisw != nil {

		// binding items for name__nisw
		joinedNameNisw := o.bindParamNameNisw(reg)

		// query array param name__nisw
		if err := r.SetQueryParam("name__nisw", joinedNameNisw...); err != nil {
			return err
		}
	}

	if o.NameRegex != nil {

		// binding items for name__regex
		joinedNameRegex := o.bindParamNameRegex(reg)

		// query array param name__regex
		if err := r.SetQueryParam("name__regex", joinedNameRegex...); err != nil {
			return err
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := conv.FormatInteger(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string

		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {

			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if o.Start != nil {

		// query param start
		var qrStart int64

		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := conv.FormatInteger(qrStart)
		if qStart != "" {

			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamExtrasScriptsList binds the parameter id.
func (o *ExtrasScriptsListParams) bindParamID(formats strfmt.Registry) []string {
	idIR := o.ID

	var idIC []string
	for _, idIIR := range idIR { // explode []int64

		idIIV := conv.FormatInteger(idIIR) // int64 as string
		idIC = append(idIC, idIIV)
	}

	// items.CollectionFormat: "multi"
	idIS := stringutils.JoinByFormat(idIC, "multi")

	return idIS
}

// bindParamExtrasScriptsList binds the parameter id__gt.
func (o *ExtrasScriptsListParams) bindParamIDGt(formats strfmt.Registry) []string {
	idGtIR := o.IDGt

	var idGtIC []string
	for _, idGtIIR := range idGtIR { // explode []int64

		idGtIIV := conv.FormatInteger(idGtIIR) // int64 as string
		idGtIC = append(idGtIC, idGtIIV)
	}

	// items.CollectionFormat: "multi"
	idGtIS := stringutils.JoinByFormat(idGtIC, "multi")

	return idGtIS
}

// bindParamExtrasScriptsList binds the parameter id__gte.
func (o *ExtrasScriptsListParams) bindParamIDGte(formats strfmt.Registry) []string {
	idGteIR := o.IDGte

	var idGteIC []string
	for _, idGteIIR := range idGteIR { // explode []int64

		idGteIIV := conv.FormatInteger(idGteIIR) // int64 as string
		idGteIC = append(idGteIC, idGteIIV)
	}

	// items.CollectionFormat: "multi"
	idGteIS := stringutils.JoinByFormat(idGteIC, "multi")

	return idGteIS
}

// bindParamExtrasScriptsList binds the parameter id__lt.
func (o *ExtrasScriptsListParams) bindParamIDLt(formats strfmt.Registry) []string {
	idLtIR := o.IDLt

	var idLtIC []string
	for _, idLtIIR := range idLtIR { // explode []int64

		idLtIIV := conv.FormatInteger(idLtIIR) // int64 as string
		idLtIC = append(idLtIC, idLtIIV)
	}

	// items.CollectionFormat: "multi"
	idLtIS := stringutils.JoinByFormat(idLtIC, "multi")

	return idLtIS
}

// bindParamExtrasScriptsList binds the parameter id__lte.
func (o *ExtrasScriptsListParams) bindParamIDLte(formats strfmt.Registry) []string {
	idLteIR := o.IDLte

	var idLteIC []string
	for _, idLteIIR := range idLteIR { // explode []int64

		idLteIIV := conv.FormatInteger(idLteIIR) // int64 as string
		idLteIC = append(idLteIC, idLteIIV)
	}

	// items.CollectionFormat: "multi"
	idLteIS := stringutils.JoinByFormat(idLteIC, "multi")

	return idLteIS
}

// bindParamExtrasScriptsList binds the parameter id__n.
func (o *ExtrasScriptsListParams) bindParamIDn(formats strfmt.Registry) []string {
	idnIR := o.IDn

	var idnIC []string
	for _, idnIIR := range idnIR { // explode []int64

		idnIIV := conv.FormatInteger(idnIIR) // int64 as string
		idnIC = append(idnIC, idnIIV)
	}

	// items.CollectionFormat: "multi"
	idnIS := stringutils.JoinByFormat(idnIC, "multi")

	return idnIS
}

// bindParamExtrasScriptsList binds the parameter module_id.
func (o *ExtrasScriptsListParams) bindParamModuleID(formats strfmt.Registry) []string {
	moduleIDIR := o.ModuleID

	var moduleIDIC []string
	for _, moduleIDIIR := range moduleIDIR { // explode []int64

		moduleIDIIV := conv.FormatInteger(moduleIDIIR) // int64 as string
		moduleIDIC = append(moduleIDIC, moduleIDIIV)
	}

	// items.CollectionFormat: "multi"
	moduleIDIS := stringutils.JoinByFormat(moduleIDIC, "multi")

	return moduleIDIS
}

// bindParamExtrasScriptsList binds the parameter module_id__n.
func (o *ExtrasScriptsListParams) bindParamModuleIDn(formats strfmt.Registry) []string {
	moduleIDnIR := o.ModuleIDn

	var moduleIDnIC []string
	for _, moduleIDnIIR := range moduleIDnIR { // explode []int64

		moduleIDnIIV := conv.FormatInteger(moduleIDnIIR) // int64 as string
		moduleIDnIC = append(moduleIDnIC, moduleIDnIIV)
	}

	// items.CollectionFormat: "multi"
	moduleIDnIS := stringutils.JoinByFormat(moduleIDnIC, "multi")

	return moduleIDnIS
}

// bindParamExtrasScriptsList binds the parameter name.
func (o *ExtrasScriptsListParams) bindParamName(formats strfmt.Registry) []string {
	nameIR := o.Name

	var nameIC []string
	for _, nameIIR := range nameIR { // explode []string

		nameIIV := nameIIR // string as string
		nameIC = append(nameIC, nameIIV)
	}

	// items.CollectionFormat: "multi"
	nameIS := stringutils.JoinByFormat(nameIC, "multi")

	return nameIS
}

// bindParamExtrasScriptsList binds the parameter name__ic.
func (o *ExtrasScriptsListParams) bindParamNameIc(formats strfmt.Registry) []string {
	nameIcIR := o.NameIc

	var nameIcIC []string
	for _, nameIcIIR := range nameIcIR { // explode []string

		nameIcIIV := nameIcIIR // string as string
		nameIcIC = append(nameIcIC, nameIcIIV)
	}

	// items.CollectionFormat: "multi"
	nameIcIS := stringutils.JoinByFormat(nameIcIC, "multi")

	return nameIcIS
}

// bindParamExtrasScriptsList binds the parameter name__ie.
func (o *ExtrasScriptsListParams) bindParamNameIe(formats strfmt.Registry) []string {
	nameIeIR := o.NameIe

	var nameIeIC []string
	for _, nameIeIIR := range nameIeIR { // explode []string

		nameIeIIV := nameIeIIR // string as string
		nameIeIC = append(nameIeIC, nameIeIIV)
	}

	// items.CollectionFormat: "multi"
	nameIeIS := stringutils.JoinByFormat(nameIeIC, "multi")

	return nameIeIS
}

// bindParamExtrasScriptsList binds the parameter name__iew.
func (o *ExtrasScriptsListParams) bindParamNameIew(formats strfmt.Registry) []string {
	nameIewIR := o.NameIew

	var nameIewIC []string
	for _, nameIewIIR := range nameIewIR { // explode []string

		nameIewIIV := nameIewIIR // string as string
		nameIewIC = append(nameIewIC, nameIewIIV)
	}

	// items.CollectionFormat: "multi"
	nameIewIS := stringutils.JoinByFormat(nameIewIC, "multi")

	return nameIewIS
}

// bindParamExtrasScriptsList binds the parameter name__iregex.
func (o *ExtrasScriptsListParams) bindParamNameIregex(formats strfmt.Registry) []string {
	nameIregexIR := o.NameIregex

	var nameIregexIC []string
	for _, nameIregexIIR := range nameIregexIR { // explode []string

		nameIregexIIV := nameIregexIIR // string as string
		nameIregexIC = append(nameIregexIC, nameIregexIIV)
	}

	// items.CollectionFormat: "multi"
	nameIregexIS := stringutils.JoinByFormat(nameIregexIC, "multi")

	return nameIregexIS
}

// bindParamExtrasScriptsList binds the parameter name__isw.
func (o *ExtrasScriptsListParams) bindParamNameIsw(formats strfmt.Registry) []string {
	nameIswIR := o.NameIsw

	var nameIswIC []string
	for _, nameIswIIR := range nameIswIR { // explode []string

		nameIswIIV := nameIswIIR // string as string
		nameIswIC = append(nameIswIC, nameIswIIV)
	}

	// items.CollectionFormat: "multi"
	nameIswIS := stringutils.JoinByFormat(nameIswIC, "multi")

	return nameIswIS
}

// bindParamExtrasScriptsList binds the parameter name__n.
func (o *ExtrasScriptsListParams) bindParamNamen(formats strfmt.Registry) []string {
	namenIR := o.Namen

	var namenIC []string
	for _, namenIIR := range namenIR { // explode []string

		namenIIV := namenIIR // string as string
		namenIC = append(namenIC, namenIIV)
	}

	// items.CollectionFormat: "multi"
	namenIS := stringutils.JoinByFormat(namenIC, "multi")

	return namenIS
}

// bindParamExtrasScriptsList binds the parameter name__nic.
func (o *ExtrasScriptsListParams) bindParamNameNic(formats strfmt.Registry) []string {
	nameNicIR := o.NameNic

	var nameNicIC []string
	for _, nameNicIIR := range nameNicIR { // explode []string

		nameNicIIV := nameNicIIR // string as string
		nameNicIC = append(nameNicIC, nameNicIIV)
	}

	// items.CollectionFormat: "multi"
	nameNicIS := stringutils.JoinByFormat(nameNicIC, "multi")

	return nameNicIS
}

// bindParamExtrasScriptsList binds the parameter name__nie.
func (o *ExtrasScriptsListParams) bindParamNameNie(formats strfmt.Registry) []string {
	nameNieIR := o.NameNie

	var nameNieIC []string
	for _, nameNieIIR := range nameNieIR { // explode []string

		nameNieIIV := nameNieIIR // string as string
		nameNieIC = append(nameNieIC, nameNieIIV)
	}

	// items.CollectionFormat: "multi"
	nameNieIS := stringutils.JoinByFormat(nameNieIC, "multi")

	return nameNieIS
}

// bindParamExtrasScriptsList binds the parameter name__niew.
func (o *ExtrasScriptsListParams) bindParamNameNiew(formats strfmt.Registry) []string {
	nameNiewIR := o.NameNiew

	var nameNiewIC []string
	for _, nameNiewIIR := range nameNiewIR { // explode []string

		nameNiewIIV := nameNiewIIR // string as string
		nameNiewIC = append(nameNiewIC, nameNiewIIV)
	}

	// items.CollectionFormat: "multi"
	nameNiewIS := stringutils.JoinByFormat(nameNiewIC, "multi")

	return nameNiewIS
}

// bindParamExtrasScriptsList binds the parameter name__nisw.
func (o *ExtrasScriptsListParams) bindParamNameNisw(formats strfmt.Registry) []string {
	nameNiswIR := o.NameNisw

	var nameNiswIC []string
	for _, nameNiswIIR := range nameNiswIR { // explode []string

		nameNiswIIV := nameNiswIIR // string as string
		nameNiswIC = append(nameNiswIC, nameNiswIIV)
	}

	// items.CollectionFormat: "multi"
	nameNiswIS := stringutils.JoinByFormat(nameNiswIC, "multi")

	return nameNiswIS
}

// bindParamExtrasScriptsList binds the parameter name__regex.
func (o *ExtrasScriptsListParams) bindParamNameRegex(formats strfmt.Registry) []string {
	nameRegexIR := o.NameRegex

	var nameRegexIC []string
	for _, nameRegexIIR := range nameRegexIR { // explode []string

		nameRegexIIV := nameRegexIIR // string as string
		nameRegexIC = append(nameRegexIC, nameRegexIIV)
	}

	// items.CollectionFormat: "multi"
	nameRegexIS := stringutils.JoinByFormat(nameRegexIC, "multi")

	return nameRegexIS
}
