// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package circuits

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CircuitsVirtualCircuitTerminationsDestroyReader is a Reader for the CircuitsVirtualCircuitTerminationsDestroy structure.
type CircuitsVirtualCircuitTerminationsDestroyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CircuitsVirtualCircuitTerminationsDestroyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewCircuitsVirtualCircuitTerminationsDestroyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCircuitsVirtualCircuitTerminationsDestroyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCircuitsVirtualCircuitTerminationsDestroyNoContent creates a CircuitsVirtualCircuitTerminationsDestroyNoContent with default headers values
func NewCircuitsVirtualCircuitTerminationsDestroyNoContent() *CircuitsVirtualCircuitTerminationsDestroyNoContent {
	return &CircuitsVirtualCircuitTerminationsDestroyNoContent{}
}

// CircuitsVirtualCircuitTerminationsDestroyNoContent describes a response with status code 204, with default header values.
//
// CircuitsVirtualCircuitTerminationsDestroyNoContent circuits virtual circuit terminations destroy no content
type CircuitsVirtualCircuitTerminationsDestroyNoContent struct {
}

// IsSuccess returns true when this circuits virtual circuit terminations destroy no content response has a 2xx status code
func (o *CircuitsVirtualCircuitTerminationsDestroyNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this circuits virtual circuit terminations destroy no content response has a 3xx status code
func (o *CircuitsVirtualCircuitTerminationsDestroyNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this circuits virtual circuit terminations destroy no content response has a 4xx status code
func (o *CircuitsVirtualCircuitTerminationsDestroyNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this circuits virtual circuit terminations destroy no content response has a 5xx status code
func (o *CircuitsVirtualCircuitTerminationsDestroyNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this circuits virtual circuit terminations destroy no content response a status code equal to that given
func (o *CircuitsVirtualCircuitTerminationsDestroyNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the circuits virtual circuit terminations destroy no content response
func (o *CircuitsVirtualCircuitTerminationsDestroyNoContent) Code() int {
	return 204
}

func (o *CircuitsVirtualCircuitTerminationsDestroyNoContent) Error() string {
	return fmt.Sprintf("[DELETE /circuits/virtual-circuit-terminations/{id}/][%d] circuitsVirtualCircuitTerminationsDestroyNoContent", 204)
}

func (o *CircuitsVirtualCircuitTerminationsDestroyNoContent) String() string {
	return fmt.Sprintf("[DELETE /circuits/virtual-circuit-terminations/{id}/][%d] circuitsVirtualCircuitTerminationsDestroyNoContent", 204)
}

func (o *CircuitsVirtualCircuitTerminationsDestroyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCircuitsVirtualCircuitTerminationsDestroyDefault creates a CircuitsVirtualCircuitTerminationsDestroyDefault with default headers values
func NewCircuitsVirtualCircuitTerminationsDestroyDefault(code int) *CircuitsVirtualCircuitTerminationsDestroyDefault {
	return &CircuitsVirtualCircuitTerminationsDestroyDefault{
		_statusCode: code,
	}
}

// CircuitsVirtualCircuitTerminationsDestroyDefault describes a response with status code -1, with default header values.
//
// CircuitsVirtualCircuitTerminationsDestroyDefault circuits virtual circuit terminations destroy default
type CircuitsVirtualCircuitTerminationsDestroyDefault struct {
	_statusCode int

	Payload any
}

// IsSuccess returns true when this circuits virtual circuit terminations destroy default response has a 2xx status code
func (o *CircuitsVirtualCircuitTerminationsDestroyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this circuits virtual circuit terminations destroy default response has a 3xx status code
func (o *CircuitsVirtualCircuitTerminationsDestroyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this circuits virtual circuit terminations destroy default response has a 4xx status code
func (o *CircuitsVirtualCircuitTerminationsDestroyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this circuits virtual circuit terminations destroy default response has a 5xx status code
func (o *CircuitsVirtualCircuitTerminationsDestroyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this circuits virtual circuit terminations destroy default response a status code equal to that given
func (o *CircuitsVirtualCircuitTerminationsDestroyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the circuits virtual circuit terminations destroy default response
func (o *CircuitsVirtualCircuitTerminationsDestroyDefault) Code() int {
	return o._statusCode
}

func (o *CircuitsVirtualCircuitTerminationsDestroyDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /circuits/virtual-circuit-terminations/{id}/][%d] circuits_virtual_circuit_terminations_destroy default %s", o._statusCode, payload)
}

func (o *CircuitsVirtualCircuitTerminationsDestroyDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /circuits/virtual-circuit-terminations/{id}/][%d] circuits_virtual_circuit_terminations_destroy default %s", o._statusCode, payload)
}

func (o *CircuitsVirtualCircuitTerminationsDestroyDefault) GetPayload() any {
	return o.Payload
}

func (o *CircuitsVirtualCircuitTerminationsDestroyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
