// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package circuits

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CircuitsCircuitTerminationsPathsRetrieveReader is a Reader for the CircuitsCircuitTerminationsPathsRetrieve structure.
type CircuitsCircuitTerminationsPathsRetrieveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CircuitsCircuitTerminationsPathsRetrieveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCircuitsCircuitTerminationsPathsRetrieveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCircuitsCircuitTerminationsPathsRetrieveDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCircuitsCircuitTerminationsPathsRetrieveOK creates a CircuitsCircuitTerminationsPathsRetrieveOK with default headers values
func NewCircuitsCircuitTerminationsPathsRetrieveOK() *CircuitsCircuitTerminationsPathsRetrieveOK {
	return &CircuitsCircuitTerminationsPathsRetrieveOK{}
}

// CircuitsCircuitTerminationsPathsRetrieveOK describes a response with status code 200, with default header values.
//
// CircuitsCircuitTerminationsPathsRetrieveOK circuits circuit terminations paths retrieve o k
type CircuitsCircuitTerminationsPathsRetrieveOK struct {
	Payload *models.CircuitTermination
}

// IsSuccess returns true when this circuits circuit terminations paths retrieve o k response has a 2xx status code
func (o *CircuitsCircuitTerminationsPathsRetrieveOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this circuits circuit terminations paths retrieve o k response has a 3xx status code
func (o *CircuitsCircuitTerminationsPathsRetrieveOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this circuits circuit terminations paths retrieve o k response has a 4xx status code
func (o *CircuitsCircuitTerminationsPathsRetrieveOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this circuits circuit terminations paths retrieve o k response has a 5xx status code
func (o *CircuitsCircuitTerminationsPathsRetrieveOK) IsServerError() bool {
	return false
}

// IsCode returns true when this circuits circuit terminations paths retrieve o k response a status code equal to that given
func (o *CircuitsCircuitTerminationsPathsRetrieveOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the circuits circuit terminations paths retrieve o k response
func (o *CircuitsCircuitTerminationsPathsRetrieveOK) Code() int {
	return 200
}

func (o *CircuitsCircuitTerminationsPathsRetrieveOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /circuits/circuit-terminations/{id}/paths/][%d] circuitsCircuitTerminationsPathsRetrieveOK %s", 200, payload)
}

func (o *CircuitsCircuitTerminationsPathsRetrieveOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /circuits/circuit-terminations/{id}/paths/][%d] circuitsCircuitTerminationsPathsRetrieveOK %s", 200, payload)
}

func (o *CircuitsCircuitTerminationsPathsRetrieveOK) GetPayload() *models.CircuitTermination {
	return o.Payload
}

func (o *CircuitsCircuitTerminationsPathsRetrieveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CircuitTermination)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCircuitsCircuitTerminationsPathsRetrieveDefault creates a CircuitsCircuitTerminationsPathsRetrieveDefault with default headers values
func NewCircuitsCircuitTerminationsPathsRetrieveDefault(code int) *CircuitsCircuitTerminationsPathsRetrieveDefault {
	return &CircuitsCircuitTerminationsPathsRetrieveDefault{
		_statusCode: code,
	}
}

// CircuitsCircuitTerminationsPathsRetrieveDefault describes a response with status code -1, with default header values.
//
// CircuitsCircuitTerminationsPathsRetrieveDefault circuits circuit terminations paths retrieve default
type CircuitsCircuitTerminationsPathsRetrieveDefault struct {
	_statusCode int

	Payload any
}

// IsSuccess returns true when this circuits circuit terminations paths retrieve default response has a 2xx status code
func (o *CircuitsCircuitTerminationsPathsRetrieveDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this circuits circuit terminations paths retrieve default response has a 3xx status code
func (o *CircuitsCircuitTerminationsPathsRetrieveDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this circuits circuit terminations paths retrieve default response has a 4xx status code
func (o *CircuitsCircuitTerminationsPathsRetrieveDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this circuits circuit terminations paths retrieve default response has a 5xx status code
func (o *CircuitsCircuitTerminationsPathsRetrieveDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this circuits circuit terminations paths retrieve default response a status code equal to that given
func (o *CircuitsCircuitTerminationsPathsRetrieveDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the circuits circuit terminations paths retrieve default response
func (o *CircuitsCircuitTerminationsPathsRetrieveDefault) Code() int {
	return o._statusCode
}

func (o *CircuitsCircuitTerminationsPathsRetrieveDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /circuits/circuit-terminations/{id}/paths/][%d] circuits_circuit_terminations_paths_retrieve default %s", o._statusCode, payload)
}

func (o *CircuitsCircuitTerminationsPathsRetrieveDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /circuits/circuit-terminations/{id}/paths/][%d] circuits_circuit_terminations_paths_retrieve default %s", o._statusCode, payload)
}

func (o *CircuitsCircuitTerminationsPathsRetrieveDefault) GetPayload() any {
	return o.Payload
}

func (o *CircuitsCircuitTerminationsPathsRetrieveDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
