// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package circuits

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCircuitsCircuitTypesCreateParams creates a new CircuitsCircuitTypesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCircuitsCircuitTypesCreateParams() *CircuitsCircuitTypesCreateParams {
	return NewCircuitsCircuitTypesCreateParamsWithTimeout(cr.DefaultTimeout)
}

// NewCircuitsCircuitTypesCreateParamsWithTimeout creates a new CircuitsCircuitTypesCreateParams object
// with the ability to set a timeout on a request.
func NewCircuitsCircuitTypesCreateParamsWithTimeout(timeout time.Duration) *CircuitsCircuitTypesCreateParams {
	return &CircuitsCircuitTypesCreateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewCircuitsCircuitTypesCreateParamsWithContext creates a new CircuitsCircuitTypesCreateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [CircuitsCircuitTypesCreateParams].
func NewCircuitsCircuitTypesCreateParamsWithContext(ctx context.Context) *CircuitsCircuitTypesCreateParams {
	return &CircuitsCircuitTypesCreateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewCircuitsCircuitTypesCreateParamsWithHTTPClient creates a new CircuitsCircuitTypesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewCircuitsCircuitTypesCreateParamsWithHTTPClient(client *http.Client) *CircuitsCircuitTypesCreateParams {
	return &CircuitsCircuitTypesCreateParams{
		HTTPClient: client,
	}
}

/*
CircuitsCircuitTypesCreateParams contains all the parameters to send to the API endpoint

	for the circuits circuit types create operation.

	Typically these are written to a http.Request.
*/
type CircuitsCircuitTypesCreateParams struct {

	// Data.
	Data *models.WritableCircuitType

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the circuits circuit types create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CircuitsCircuitTypesCreateParams) WithDefaults() *CircuitsCircuitTypesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the circuits circuit types create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CircuitsCircuitTypesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the circuits circuit types create params.
func (o *CircuitsCircuitTypesCreateParams) WithTimeout(timeout time.Duration) *CircuitsCircuitTypesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the circuits circuit types create params.
func (o *CircuitsCircuitTypesCreateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the circuits circuit types create params.
//
// Deprecated: use the operation call with context to pass the context instead of [CircuitsCircuitTypesCreateParams].
func (o *CircuitsCircuitTypesCreateParams) WithContext(ctx context.Context) *CircuitsCircuitTypesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the circuits circuit types create params.
//
// Deprecated: use the operation call with context to pass the context instead of [CircuitsCircuitTypesCreateParams].
func (o *CircuitsCircuitTypesCreateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the circuits circuit types create params.
func (o *CircuitsCircuitTypesCreateParams) WithHTTPClient(client *http.Client) *CircuitsCircuitTypesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the circuits circuit types create params.
func (o *CircuitsCircuitTypesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the circuits circuit types create params.
func (o *CircuitsCircuitTypesCreateParams) WithData(data *models.WritableCircuitType) *CircuitsCircuitTypesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the circuits circuit types create params.
func (o *CircuitsCircuitTypesCreateParams) SetData(data *models.WritableCircuitType) {
	o.Data = data
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *CircuitsCircuitTypesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
