// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package ipam

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewIpamIPRangesAvailableIpsListParams creates a new IpamIPRangesAvailableIpsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIpamIPRangesAvailableIpsListParams() *IpamIPRangesAvailableIpsListParams {
	return NewIpamIPRangesAvailableIpsListParamsWithTimeout(cr.DefaultTimeout)
}

// NewIpamIPRangesAvailableIpsListParamsWithTimeout creates a new IpamIPRangesAvailableIpsListParams object
// with the ability to set a timeout on a request.
func NewIpamIPRangesAvailableIpsListParamsWithTimeout(timeout time.Duration) *IpamIPRangesAvailableIpsListParams {
	return &IpamIPRangesAvailableIpsListParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewIpamIPRangesAvailableIpsListParamsWithContext creates a new IpamIPRangesAvailableIpsListParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamIPRangesAvailableIpsListParams].
func NewIpamIPRangesAvailableIpsListParamsWithContext(ctx context.Context) *IpamIPRangesAvailableIpsListParams {
	return &IpamIPRangesAvailableIpsListParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewIpamIPRangesAvailableIpsListParamsWithHTTPClient creates a new IpamIPRangesAvailableIpsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewIpamIPRangesAvailableIpsListParamsWithHTTPClient(client *http.Client) *IpamIPRangesAvailableIpsListParams {
	return &IpamIPRangesAvailableIpsListParams{
		HTTPClient: client,
	}
}

/*
IpamIPRangesAvailableIpsListParams contains all the parameters to send to the API endpoint

	for the ipam ip ranges available ips list operation.

	Typically these are written to a http.Request.
*/
type IpamIPRangesAvailableIpsListParams struct {

	// ID.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the ipam ip ranges available ips list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IpamIPRangesAvailableIpsListParams) WithDefaults() *IpamIPRangesAvailableIpsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ipam ip ranges available ips list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IpamIPRangesAvailableIpsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ipam ip ranges available ips list params.
func (o *IpamIPRangesAvailableIpsListParams) WithTimeout(timeout time.Duration) *IpamIPRangesAvailableIpsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ipam ip ranges available ips list params.
func (o *IpamIPRangesAvailableIpsListParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the ipam ip ranges available ips list params.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamIPRangesAvailableIpsListParams].
func (o *IpamIPRangesAvailableIpsListParams) WithContext(ctx context.Context) *IpamIPRangesAvailableIpsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ipam ip ranges available ips list params.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamIPRangesAvailableIpsListParams].
func (o *IpamIPRangesAvailableIpsListParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the ipam ip ranges available ips list params.
func (o *IpamIPRangesAvailableIpsListParams) WithHTTPClient(client *http.Client) *IpamIPRangesAvailableIpsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ipam ip ranges available ips list params.
func (o *IpamIPRangesAvailableIpsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the ipam ip ranges available ips list params.
func (o *IpamIPRangesAvailableIpsListParams) WithID(id int64) *IpamIPRangesAvailableIpsListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ipam ip ranges available ips list params.
func (o *IpamIPRangesAvailableIpsListParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *IpamIPRangesAvailableIpsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
