// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package ipam

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewIpamRirsUpdateParams creates a new IpamRirsUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIpamRirsUpdateParams() *IpamRirsUpdateParams {
	return NewIpamRirsUpdateParamsWithTimeout(cr.DefaultTimeout)
}

// NewIpamRirsUpdateParamsWithTimeout creates a new IpamRirsUpdateParams object
// with the ability to set a timeout on a request.
func NewIpamRirsUpdateParamsWithTimeout(timeout time.Duration) *IpamRirsUpdateParams {
	return &IpamRirsUpdateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewIpamRirsUpdateParamsWithContext creates a new IpamRirsUpdateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamRirsUpdateParams].
func NewIpamRirsUpdateParamsWithContext(ctx context.Context) *IpamRirsUpdateParams {
	return &IpamRirsUpdateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewIpamRirsUpdateParamsWithHTTPClient creates a new IpamRirsUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewIpamRirsUpdateParamsWithHTTPClient(client *http.Client) *IpamRirsUpdateParams {
	return &IpamRirsUpdateParams{
		HTTPClient: client,
	}
}

/*
IpamRirsUpdateParams contains all the parameters to send to the API endpoint

	for the ipam rirs update operation.

	Typically these are written to a http.Request.
*/
type IpamRirsUpdateParams struct {

	// Data.
	Data *models.WritableRIR

	// ID.
	//
	// A unique integer value identifying this RIR.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the ipam rirs update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IpamRirsUpdateParams) WithDefaults() *IpamRirsUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ipam rirs update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IpamRirsUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ipam rirs update params.
func (o *IpamRirsUpdateParams) WithTimeout(timeout time.Duration) *IpamRirsUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ipam rirs update params.
func (o *IpamRirsUpdateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the ipam rirs update params.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamRirsUpdateParams].
func (o *IpamRirsUpdateParams) WithContext(ctx context.Context) *IpamRirsUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ipam rirs update params.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamRirsUpdateParams].
func (o *IpamRirsUpdateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the ipam rirs update params.
func (o *IpamRirsUpdateParams) WithHTTPClient(client *http.Client) *IpamRirsUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ipam rirs update params.
func (o *IpamRirsUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the ipam rirs update params.
func (o *IpamRirsUpdateParams) WithData(data *models.WritableRIR) *IpamRirsUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the ipam rirs update params.
func (o *IpamRirsUpdateParams) SetData(data *models.WritableRIR) {
	o.Data = data
}

// WithID adds the id to the ipam rirs update params.
func (o *IpamRirsUpdateParams) WithID(id int64) *IpamRirsUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ipam rirs update params.
func (o *IpamRirsUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *IpamRirsUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
