// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package ipam

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIpamIPRangesCreateParams creates a new IpamIPRangesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIpamIPRangesCreateParams() *IpamIPRangesCreateParams {
	return NewIpamIPRangesCreateParamsWithTimeout(cr.DefaultTimeout)
}

// NewIpamIPRangesCreateParamsWithTimeout creates a new IpamIPRangesCreateParams object
// with the ability to set a timeout on a request.
func NewIpamIPRangesCreateParamsWithTimeout(timeout time.Duration) *IpamIPRangesCreateParams {
	return &IpamIPRangesCreateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewIpamIPRangesCreateParamsWithContext creates a new IpamIPRangesCreateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamIPRangesCreateParams].
func NewIpamIPRangesCreateParamsWithContext(ctx context.Context) *IpamIPRangesCreateParams {
	return &IpamIPRangesCreateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewIpamIPRangesCreateParamsWithHTTPClient creates a new IpamIPRangesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewIpamIPRangesCreateParamsWithHTTPClient(client *http.Client) *IpamIPRangesCreateParams {
	return &IpamIPRangesCreateParams{
		HTTPClient: client,
	}
}

/*
IpamIPRangesCreateParams contains all the parameters to send to the API endpoint

	for the ipam ip ranges create operation.

	Typically these are written to a http.Request.
*/
type IpamIPRangesCreateParams struct {

	// Data.
	Data *models.WritableIPRange

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the ipam ip ranges create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IpamIPRangesCreateParams) WithDefaults() *IpamIPRangesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ipam ip ranges create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IpamIPRangesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ipam ip ranges create params.
func (o *IpamIPRangesCreateParams) WithTimeout(timeout time.Duration) *IpamIPRangesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ipam ip ranges create params.
func (o *IpamIPRangesCreateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the ipam ip ranges create params.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamIPRangesCreateParams].
func (o *IpamIPRangesCreateParams) WithContext(ctx context.Context) *IpamIPRangesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ipam ip ranges create params.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamIPRangesCreateParams].
func (o *IpamIPRangesCreateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the ipam ip ranges create params.
func (o *IpamIPRangesCreateParams) WithHTTPClient(client *http.Client) *IpamIPRangesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ipam ip ranges create params.
func (o *IpamIPRangesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the ipam ip ranges create params.
func (o *IpamIPRangesCreateParams) WithData(data *models.WritableIPRange) *IpamIPRangesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the ipam ip ranges create params.
func (o *IpamIPRangesCreateParams) SetData(data *models.WritableIPRange) {
	o.Data = data
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *IpamIPRangesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
