// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package ipam

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewIpamVlanTranslationRulesUpdateParams creates a new IpamVlanTranslationRulesUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIpamVlanTranslationRulesUpdateParams() *IpamVlanTranslationRulesUpdateParams {
	return NewIpamVlanTranslationRulesUpdateParamsWithTimeout(cr.DefaultTimeout)
}

// NewIpamVlanTranslationRulesUpdateParamsWithTimeout creates a new IpamVlanTranslationRulesUpdateParams object
// with the ability to set a timeout on a request.
func NewIpamVlanTranslationRulesUpdateParamsWithTimeout(timeout time.Duration) *IpamVlanTranslationRulesUpdateParams {
	return &IpamVlanTranslationRulesUpdateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewIpamVlanTranslationRulesUpdateParamsWithContext creates a new IpamVlanTranslationRulesUpdateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamVlanTranslationRulesUpdateParams].
func NewIpamVlanTranslationRulesUpdateParamsWithContext(ctx context.Context) *IpamVlanTranslationRulesUpdateParams {
	return &IpamVlanTranslationRulesUpdateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewIpamVlanTranslationRulesUpdateParamsWithHTTPClient creates a new IpamVlanTranslationRulesUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewIpamVlanTranslationRulesUpdateParamsWithHTTPClient(client *http.Client) *IpamVlanTranslationRulesUpdateParams {
	return &IpamVlanTranslationRulesUpdateParams{
		HTTPClient: client,
	}
}

/*
IpamVlanTranslationRulesUpdateParams contains all the parameters to send to the API endpoint

	for the ipam vlan translation rules update operation.

	Typically these are written to a http.Request.
*/
type IpamVlanTranslationRulesUpdateParams struct {

	// Data.
	Data *models.VLANTranslationRule

	// ID.
	//
	// A unique integer value identifying this VLAN translation rule.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the ipam vlan translation rules update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IpamVlanTranslationRulesUpdateParams) WithDefaults() *IpamVlanTranslationRulesUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ipam vlan translation rules update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IpamVlanTranslationRulesUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ipam vlan translation rules update params.
func (o *IpamVlanTranslationRulesUpdateParams) WithTimeout(timeout time.Duration) *IpamVlanTranslationRulesUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ipam vlan translation rules update params.
func (o *IpamVlanTranslationRulesUpdateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the ipam vlan translation rules update params.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamVlanTranslationRulesUpdateParams].
func (o *IpamVlanTranslationRulesUpdateParams) WithContext(ctx context.Context) *IpamVlanTranslationRulesUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ipam vlan translation rules update params.
//
// Deprecated: use the operation call with context to pass the context instead of [IpamVlanTranslationRulesUpdateParams].
func (o *IpamVlanTranslationRulesUpdateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the ipam vlan translation rules update params.
func (o *IpamVlanTranslationRulesUpdateParams) WithHTTPClient(client *http.Client) *IpamVlanTranslationRulesUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ipam vlan translation rules update params.
func (o *IpamVlanTranslationRulesUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the ipam vlan translation rules update params.
func (o *IpamVlanTranslationRulesUpdateParams) WithData(data *models.VLANTranslationRule) *IpamVlanTranslationRulesUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the ipam vlan translation rules update params.
func (o *IpamVlanTranslationRulesUpdateParams) SetData(data *models.VLANTranslationRule) {
	o.Data = data
}

// WithID adds the id to the ipam vlan translation rules update params.
func (o *IpamVlanTranslationRulesUpdateParams) WithID(id int64) *IpamVlanTranslationRulesUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ipam vlan translation rules update params.
func (o *IpamVlanTranslationRulesUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *IpamVlanTranslationRulesUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
