// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package core

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
	"github.com/go-openapi/swag/stringutils"
)

// NewCoreObjectTypesListParams creates a new CoreObjectTypesListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCoreObjectTypesListParams() *CoreObjectTypesListParams {
	return NewCoreObjectTypesListParamsWithTimeout(cr.DefaultTimeout)
}

// NewCoreObjectTypesListParamsWithTimeout creates a new CoreObjectTypesListParams object
// with the ability to set a timeout on a request.
func NewCoreObjectTypesListParamsWithTimeout(timeout time.Duration) *CoreObjectTypesListParams {
	return &CoreObjectTypesListParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewCoreObjectTypesListParamsWithContext creates a new CoreObjectTypesListParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [CoreObjectTypesListParams].
func NewCoreObjectTypesListParamsWithContext(ctx context.Context) *CoreObjectTypesListParams {
	return &CoreObjectTypesListParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewCoreObjectTypesListParamsWithHTTPClient creates a new CoreObjectTypesListParams object
// with the ability to set a custom HTTPClient for a request.
func NewCoreObjectTypesListParamsWithHTTPClient(client *http.Client) *CoreObjectTypesListParams {
	return &CoreObjectTypesListParams{
		HTTPClient: client,
	}
}

/*
CoreObjectTypesListParams contains all the parameters to send to the API endpoint

	for the core object types list operation.

	Typically these are written to a http.Request.
*/
type CoreObjectTypesListParams struct {

	// AppLabel.
	AppLabel []string

	// AppLabelEmpty.
	AppLabelEmpty *bool

	// AppLabelIc.
	AppLabelIc []string

	// AppLabelIe.
	AppLabelIe []string

	// AppLabelIew.
	AppLabelIew []string

	// AppLabelIregex.
	AppLabelIregex []string

	// AppLabelIsw.
	AppLabelIsw []string

	// AppLabeln.
	AppLabeln []string

	// AppLabelNic.
	AppLabelNic []string

	// AppLabelNie.
	AppLabelNie []string

	// AppLabelNiew.
	AppLabelNiew []string

	// AppLabelNisw.
	AppLabelNisw []string

	// AppLabelRegex.
	AppLabelRegex []string

	// Features.
	Features *string

	// ID.
	ID []int64

	// IDEmpty.
	IDEmpty *bool

	// IDGt.
	IDGt []int64

	// IDGte.
	IDGte []int64

	// IDLt.
	IDLt []int64

	// IDLte.
	IDLte []int64

	// IDn.
	IDn []int64

	// Limit.
	//
	// Number of results to return per page.
	Limit *int64

	// Model.
	Model []string

	// ModelEmpty.
	ModelEmpty *bool

	// ModelIc.
	ModelIc []string

	// ModelIe.
	ModelIe []string

	// ModelIew.
	ModelIew []string

	// ModelIregex.
	ModelIregex []string

	// ModelIsw.
	ModelIsw []string

	// Modeln.
	Modeln []string

	// ModelNic.
	ModelNic []string

	// ModelNie.
	ModelNie []string

	// ModelNiew.
	ModelNiew []string

	// ModelNisw.
	ModelNisw []string

	// ModelRegex.
	ModelRegex []string

	// Offset.
	//
	// The initial index from which to return the results.
	Offset *int64

	// Ordering.
	//
	// Which field to use when ordering the results.
	Ordering *string

	// Public.
	Public *bool

	// Q.
	//
	// Search
	Q *string

	// Start.
	//
	// Cursor-based pagination: return results with pk >= start, ordered by pk. Mutually exclusive with offset.
	Start *int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the core object types list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CoreObjectTypesListParams) WithDefaults() *CoreObjectTypesListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the core object types list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CoreObjectTypesListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the core object types list params.
func (o *CoreObjectTypesListParams) WithTimeout(timeout time.Duration) *CoreObjectTypesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the core object types list params.
func (o *CoreObjectTypesListParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the core object types list params.
//
// Deprecated: use the operation call with context to pass the context instead of [CoreObjectTypesListParams].
func (o *CoreObjectTypesListParams) WithContext(ctx context.Context) *CoreObjectTypesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the core object types list params.
//
// Deprecated: use the operation call with context to pass the context instead of [CoreObjectTypesListParams].
func (o *CoreObjectTypesListParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the core object types list params.
func (o *CoreObjectTypesListParams) WithHTTPClient(client *http.Client) *CoreObjectTypesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the core object types list params.
func (o *CoreObjectTypesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppLabel adds the appLabel to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabel(appLabel []string) *CoreObjectTypesListParams {
	o.SetAppLabel(appLabel)
	return o
}

// SetAppLabel adds the appLabel to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabel(appLabel []string) {
	o.AppLabel = appLabel
}

// WithAppLabelEmpty adds the appLabelEmpty to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabelEmpty(appLabelEmpty *bool) *CoreObjectTypesListParams {
	o.SetAppLabelEmpty(appLabelEmpty)
	return o
}

// SetAppLabelEmpty adds the appLabelEmpty to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabelEmpty(appLabelEmpty *bool) {
	o.AppLabelEmpty = appLabelEmpty
}

// WithAppLabelIc adds the appLabelIc to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabelIc(appLabelIc []string) *CoreObjectTypesListParams {
	o.SetAppLabelIc(appLabelIc)
	return o
}

// SetAppLabelIc adds the appLabelIc to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabelIc(appLabelIc []string) {
	o.AppLabelIc = appLabelIc
}

// WithAppLabelIe adds the appLabelIe to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabelIe(appLabelIe []string) *CoreObjectTypesListParams {
	o.SetAppLabelIe(appLabelIe)
	return o
}

// SetAppLabelIe adds the appLabelIe to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabelIe(appLabelIe []string) {
	o.AppLabelIe = appLabelIe
}

// WithAppLabelIew adds the appLabelIew to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabelIew(appLabelIew []string) *CoreObjectTypesListParams {
	o.SetAppLabelIew(appLabelIew)
	return o
}

// SetAppLabelIew adds the appLabelIew to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabelIew(appLabelIew []string) {
	o.AppLabelIew = appLabelIew
}

// WithAppLabelIregex adds the appLabelIregex to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabelIregex(appLabelIregex []string) *CoreObjectTypesListParams {
	o.SetAppLabelIregex(appLabelIregex)
	return o
}

// SetAppLabelIregex adds the appLabelIregex to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabelIregex(appLabelIregex []string) {
	o.AppLabelIregex = appLabelIregex
}

// WithAppLabelIsw adds the appLabelIsw to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabelIsw(appLabelIsw []string) *CoreObjectTypesListParams {
	o.SetAppLabelIsw(appLabelIsw)
	return o
}

// SetAppLabelIsw adds the appLabelIsw to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabelIsw(appLabelIsw []string) {
	o.AppLabelIsw = appLabelIsw
}

// WithAppLabeln adds the appLabeln to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabeln(appLabeln []string) *CoreObjectTypesListParams {
	o.SetAppLabeln(appLabeln)
	return o
}

// SetAppLabeln adds the appLabelN to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabeln(appLabeln []string) {
	o.AppLabeln = appLabeln
}

// WithAppLabelNic adds the appLabelNic to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabelNic(appLabelNic []string) *CoreObjectTypesListParams {
	o.SetAppLabelNic(appLabelNic)
	return o
}

// SetAppLabelNic adds the appLabelNic to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabelNic(appLabelNic []string) {
	o.AppLabelNic = appLabelNic
}

// WithAppLabelNie adds the appLabelNie to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabelNie(appLabelNie []string) *CoreObjectTypesListParams {
	o.SetAppLabelNie(appLabelNie)
	return o
}

// SetAppLabelNie adds the appLabelNie to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabelNie(appLabelNie []string) {
	o.AppLabelNie = appLabelNie
}

// WithAppLabelNiew adds the appLabelNiew to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabelNiew(appLabelNiew []string) *CoreObjectTypesListParams {
	o.SetAppLabelNiew(appLabelNiew)
	return o
}

// SetAppLabelNiew adds the appLabelNiew to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabelNiew(appLabelNiew []string) {
	o.AppLabelNiew = appLabelNiew
}

// WithAppLabelNisw adds the appLabelNisw to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabelNisw(appLabelNisw []string) *CoreObjectTypesListParams {
	o.SetAppLabelNisw(appLabelNisw)
	return o
}

// SetAppLabelNisw adds the appLabelNisw to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabelNisw(appLabelNisw []string) {
	o.AppLabelNisw = appLabelNisw
}

// WithAppLabelRegex adds the appLabelRegex to the core object types list params.
func (o *CoreObjectTypesListParams) WithAppLabelRegex(appLabelRegex []string) *CoreObjectTypesListParams {
	o.SetAppLabelRegex(appLabelRegex)
	return o
}

// SetAppLabelRegex adds the appLabelRegex to the core object types list params.
func (o *CoreObjectTypesListParams) SetAppLabelRegex(appLabelRegex []string) {
	o.AppLabelRegex = appLabelRegex
}

// WithFeatures adds the features to the core object types list params.
func (o *CoreObjectTypesListParams) WithFeatures(features *string) *CoreObjectTypesListParams {
	o.SetFeatures(features)
	return o
}

// SetFeatures adds the features to the core object types list params.
func (o *CoreObjectTypesListParams) SetFeatures(features *string) {
	o.Features = features
}

// WithID adds the id to the core object types list params.
func (o *CoreObjectTypesListParams) WithID(id []int64) *CoreObjectTypesListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the core object types list params.
func (o *CoreObjectTypesListParams) SetID(id []int64) {
	o.ID = id
}

// WithIDEmpty adds the idEmpty to the core object types list params.
func (o *CoreObjectTypesListParams) WithIDEmpty(idEmpty *bool) *CoreObjectTypesListParams {
	o.SetIDEmpty(idEmpty)
	return o
}

// SetIDEmpty adds the idEmpty to the core object types list params.
func (o *CoreObjectTypesListParams) SetIDEmpty(idEmpty *bool) {
	o.IDEmpty = idEmpty
}

// WithIDGt adds the idGt to the core object types list params.
func (o *CoreObjectTypesListParams) WithIDGt(idGt []int64) *CoreObjectTypesListParams {
	o.SetIDGt(idGt)
	return o
}

// SetIDGt adds the idGt to the core object types list params.
func (o *CoreObjectTypesListParams) SetIDGt(idGt []int64) {
	o.IDGt = idGt
}

// WithIDGte adds the idGte to the core object types list params.
func (o *CoreObjectTypesListParams) WithIDGte(idGte []int64) *CoreObjectTypesListParams {
	o.SetIDGte(idGte)
	return o
}

// SetIDGte adds the idGte to the core object types list params.
func (o *CoreObjectTypesListParams) SetIDGte(idGte []int64) {
	o.IDGte = idGte
}

// WithIDLt adds the idLt to the core object types list params.
func (o *CoreObjectTypesListParams) WithIDLt(idLt []int64) *CoreObjectTypesListParams {
	o.SetIDLt(idLt)
	return o
}

// SetIDLt adds the idLt to the core object types list params.
func (o *CoreObjectTypesListParams) SetIDLt(idLt []int64) {
	o.IDLt = idLt
}

// WithIDLte adds the idLte to the core object types list params.
func (o *CoreObjectTypesListParams) WithIDLte(idLte []int64) *CoreObjectTypesListParams {
	o.SetIDLte(idLte)
	return o
}

// SetIDLte adds the idLte to the core object types list params.
func (o *CoreObjectTypesListParams) SetIDLte(idLte []int64) {
	o.IDLte = idLte
}

// WithIDn adds the idn to the core object types list params.
func (o *CoreObjectTypesListParams) WithIDn(idn []int64) *CoreObjectTypesListParams {
	o.SetIDn(idn)
	return o
}

// SetIDn adds the idN to the core object types list params.
func (o *CoreObjectTypesListParams) SetIDn(idn []int64) {
	o.IDn = idn
}

// WithLimit adds the limit to the core object types list params.
func (o *CoreObjectTypesListParams) WithLimit(limit *int64) *CoreObjectTypesListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the core object types list params.
func (o *CoreObjectTypesListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithModel adds the model to the core object types list params.
func (o *CoreObjectTypesListParams) WithModel(model []string) *CoreObjectTypesListParams {
	o.SetModel(model)
	return o
}

// SetModel adds the model to the core object types list params.
func (o *CoreObjectTypesListParams) SetModel(model []string) {
	o.Model = model
}

// WithModelEmpty adds the modelEmpty to the core object types list params.
func (o *CoreObjectTypesListParams) WithModelEmpty(modelEmpty *bool) *CoreObjectTypesListParams {
	o.SetModelEmpty(modelEmpty)
	return o
}

// SetModelEmpty adds the modelEmpty to the core object types list params.
func (o *CoreObjectTypesListParams) SetModelEmpty(modelEmpty *bool) {
	o.ModelEmpty = modelEmpty
}

// WithModelIc adds the modelIc to the core object types list params.
func (o *CoreObjectTypesListParams) WithModelIc(modelIc []string) *CoreObjectTypesListParams {
	o.SetModelIc(modelIc)
	return o
}

// SetModelIc adds the modelIc to the core object types list params.
func (o *CoreObjectTypesListParams) SetModelIc(modelIc []string) {
	o.ModelIc = modelIc
}

// WithModelIe adds the modelIe to the core object types list params.
func (o *CoreObjectTypesListParams) WithModelIe(modelIe []string) *CoreObjectTypesListParams {
	o.SetModelIe(modelIe)
	return o
}

// SetModelIe adds the modelIe to the core object types list params.
func (o *CoreObjectTypesListParams) SetModelIe(modelIe []string) {
	o.ModelIe = modelIe
}

// WithModelIew adds the modelIew to the core object types list params.
func (o *CoreObjectTypesListParams) WithModelIew(modelIew []string) *CoreObjectTypesListParams {
	o.SetModelIew(modelIew)
	return o
}

// SetModelIew adds the modelIew to the core object types list params.
func (o *CoreObjectTypesListParams) SetModelIew(modelIew []string) {
	o.ModelIew = modelIew
}

// WithModelIregex adds the modelIregex to the core object types list params.
func (o *CoreObjectTypesListParams) WithModelIregex(modelIregex []string) *CoreObjectTypesListParams {
	o.SetModelIregex(modelIregex)
	return o
}

// SetModelIregex adds the modelIregex to the core object types list params.
func (o *CoreObjectTypesListParams) SetModelIregex(modelIregex []string) {
	o.ModelIregex = modelIregex
}

// WithModelIsw adds the modelIsw to the core object types list params.
func (o *CoreObjectTypesListParams) WithModelIsw(modelIsw []string) *CoreObjectTypesListParams {
	o.SetModelIsw(modelIsw)
	return o
}

// SetModelIsw adds the modelIsw to the core object types list params.
func (o *CoreObjectTypesListParams) SetModelIsw(modelIsw []string) {
	o.ModelIsw = modelIsw
}

// WithModeln adds the modeln to the core object types list params.
func (o *CoreObjectTypesListParams) WithModeln(modeln []string) *CoreObjectTypesListParams {
	o.SetModeln(modeln)
	return o
}

// SetModeln adds the modelN to the core object types list params.
func (o *CoreObjectTypesListParams) SetModeln(modeln []string) {
	o.Modeln = modeln
}

// WithModelNic adds the modelNic to the core object types list params.
func (o *CoreObjectTypesListParams) WithModelNic(modelNic []string) *CoreObjectTypesListParams {
	o.SetModelNic(modelNic)
	return o
}

// SetModelNic adds the modelNic to the core object types list params.
func (o *CoreObjectTypesListParams) SetModelNic(modelNic []string) {
	o.ModelNic = modelNic
}

// WithModelNie adds the modelNie to the core object types list params.
func (o *CoreObjectTypesListParams) WithModelNie(modelNie []string) *CoreObjectTypesListParams {
	o.SetModelNie(modelNie)
	return o
}

// SetModelNie adds the modelNie to the core object types list params.
func (o *CoreObjectTypesListParams) SetModelNie(modelNie []string) {
	o.ModelNie = modelNie
}

// WithModelNiew adds the modelNiew to the core object types list params.
func (o *CoreObjectTypesListParams) WithModelNiew(modelNiew []string) *CoreObjectTypesListParams {
	o.SetModelNiew(modelNiew)
	return o
}

// SetModelNiew adds the modelNiew to the core object types list params.
func (o *CoreObjectTypesListParams) SetModelNiew(modelNiew []string) {
	o.ModelNiew = modelNiew
}

// WithModelNisw adds the modelNisw to the core object types list params.
func (o *CoreObjectTypesListParams) WithModelNisw(modelNisw []string) *CoreObjectTypesListParams {
	o.SetModelNisw(modelNisw)
	return o
}

// SetModelNisw adds the modelNisw to the core object types list params.
func (o *CoreObjectTypesListParams) SetModelNisw(modelNisw []string) {
	o.ModelNisw = modelNisw
}

// WithModelRegex adds the modelRegex to the core object types list params.
func (o *CoreObjectTypesListParams) WithModelRegex(modelRegex []string) *CoreObjectTypesListParams {
	o.SetModelRegex(modelRegex)
	return o
}

// SetModelRegex adds the modelRegex to the core object types list params.
func (o *CoreObjectTypesListParams) SetModelRegex(modelRegex []string) {
	o.ModelRegex = modelRegex
}

// WithOffset adds the offset to the core object types list params.
func (o *CoreObjectTypesListParams) WithOffset(offset *int64) *CoreObjectTypesListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the core object types list params.
func (o *CoreObjectTypesListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the core object types list params.
func (o *CoreObjectTypesListParams) WithOrdering(ordering *string) *CoreObjectTypesListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the core object types list params.
func (o *CoreObjectTypesListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WithPublic adds the public to the core object types list params.
func (o *CoreObjectTypesListParams) WithPublic(public *bool) *CoreObjectTypesListParams {
	o.SetPublic(public)
	return o
}

// SetPublic adds the public to the core object types list params.
func (o *CoreObjectTypesListParams) SetPublic(public *bool) {
	o.Public = public
}

// WithQ adds the q to the core object types list params.
func (o *CoreObjectTypesListParams) WithQ(q *string) *CoreObjectTypesListParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the core object types list params.
func (o *CoreObjectTypesListParams) SetQ(q *string) {
	o.Q = q
}

// WithStart adds the start to the core object types list params.
func (o *CoreObjectTypesListParams) WithStart(start *int64) *CoreObjectTypesListParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the core object types list params.
func (o *CoreObjectTypesListParams) SetStart(start *int64) {
	o.Start = start
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *CoreObjectTypesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.AppLabel != nil {

		// binding items for app_label
		joinedAppLabel := o.bindParamAppLabel(reg)

		// query array param app_label
		if err := r.SetQueryParam("app_label", joinedAppLabel...); err != nil {
			return err
		}
	}

	if o.AppLabelEmpty != nil {

		// query param app_label__empty
		var qrAppLabelEmpty bool

		if o.AppLabelEmpty != nil {
			qrAppLabelEmpty = *o.AppLabelEmpty
		}
		qAppLabelEmpty := conv.FormatBool(qrAppLabelEmpty)
		if qAppLabelEmpty != "" {

			if err := r.SetQueryParam("app_label__empty", qAppLabelEmpty); err != nil {
				return err
			}
		}
	}

	if o.AppLabelIc != nil {

		// binding items for app_label__ic
		joinedAppLabelIc := o.bindParamAppLabelIc(reg)

		// query array param app_label__ic
		if err := r.SetQueryParam("app_label__ic", joinedAppLabelIc...); err != nil {
			return err
		}
	}

	if o.AppLabelIe != nil {

		// binding items for app_label__ie
		joinedAppLabelIe := o.bindParamAppLabelIe(reg)

		// query array param app_label__ie
		if err := r.SetQueryParam("app_label__ie", joinedAppLabelIe...); err != nil {
			return err
		}
	}

	if o.AppLabelIew != nil {

		// binding items for app_label__iew
		joinedAppLabelIew := o.bindParamAppLabelIew(reg)

		// query array param app_label__iew
		if err := r.SetQueryParam("app_label__iew", joinedAppLabelIew...); err != nil {
			return err
		}
	}

	if o.AppLabelIregex != nil {

		// binding items for app_label__iregex
		joinedAppLabelIregex := o.bindParamAppLabelIregex(reg)

		// query array param app_label__iregex
		if err := r.SetQueryParam("app_label__iregex", joinedAppLabelIregex...); err != nil {
			return err
		}
	}

	if o.AppLabelIsw != nil {

		// binding items for app_label__isw
		joinedAppLabelIsw := o.bindParamAppLabelIsw(reg)

		// query array param app_label__isw
		if err := r.SetQueryParam("app_label__isw", joinedAppLabelIsw...); err != nil {
			return err
		}
	}

	if o.AppLabeln != nil {

		// binding items for app_label__n
		joinedAppLabeln := o.bindParamAppLabeln(reg)

		// query array param app_label__n
		if err := r.SetQueryParam("app_label__n", joinedAppLabeln...); err != nil {
			return err
		}
	}

	if o.AppLabelNic != nil {

		// binding items for app_label__nic
		joinedAppLabelNic := o.bindParamAppLabelNic(reg)

		// query array param app_label__nic
		if err := r.SetQueryParam("app_label__nic", joinedAppLabelNic...); err != nil {
			return err
		}
	}

	if o.AppLabelNie != nil {

		// binding items for app_label__nie
		joinedAppLabelNie := o.bindParamAppLabelNie(reg)

		// query array param app_label__nie
		if err := r.SetQueryParam("app_label__nie", joinedAppLabelNie...); err != nil {
			return err
		}
	}

	if o.AppLabelNiew != nil {

		// binding items for app_label__niew
		joinedAppLabelNiew := o.bindParamAppLabelNiew(reg)

		// query array param app_label__niew
		if err := r.SetQueryParam("app_label__niew", joinedAppLabelNiew...); err != nil {
			return err
		}
	}

	if o.AppLabelNisw != nil {

		// binding items for app_label__nisw
		joinedAppLabelNisw := o.bindParamAppLabelNisw(reg)

		// query array param app_label__nisw
		if err := r.SetQueryParam("app_label__nisw", joinedAppLabelNisw...); err != nil {
			return err
		}
	}

	if o.AppLabelRegex != nil {

		// binding items for app_label__regex
		joinedAppLabelRegex := o.bindParamAppLabelRegex(reg)

		// query array param app_label__regex
		if err := r.SetQueryParam("app_label__regex", joinedAppLabelRegex...); err != nil {
			return err
		}
	}

	if o.Features != nil {

		// query param features
		var qrFeatures string

		if o.Features != nil {
			qrFeatures = *o.Features
		}
		qFeatures := qrFeatures
		if qFeatures != "" {

			if err := r.SetQueryParam("features", qFeatures); err != nil {
				return err
			}
		}
	}

	if o.ID != nil {

		// binding items for id
		joinedID := o.bindParamID(reg)

		// query array param id
		if err := r.SetQueryParam("id", joinedID...); err != nil {
			return err
		}
	}

	if o.IDEmpty != nil {

		// query param id__empty
		var qrIDEmpty bool

		if o.IDEmpty != nil {
			qrIDEmpty = *o.IDEmpty
		}
		qIDEmpty := conv.FormatBool(qrIDEmpty)
		if qIDEmpty != "" {

			if err := r.SetQueryParam("id__empty", qIDEmpty); err != nil {
				return err
			}
		}
	}

	if o.IDGt != nil {

		// binding items for id__gt
		joinedIDGt := o.bindParamIDGt(reg)

		// query array param id__gt
		if err := r.SetQueryParam("id__gt", joinedIDGt...); err != nil {
			return err
		}
	}

	if o.IDGte != nil {

		// binding items for id__gte
		joinedIDGte := o.bindParamIDGte(reg)

		// query array param id__gte
		if err := r.SetQueryParam("id__gte", joinedIDGte...); err != nil {
			return err
		}
	}

	if o.IDLt != nil {

		// binding items for id__lt
		joinedIDLt := o.bindParamIDLt(reg)

		// query array param id__lt
		if err := r.SetQueryParam("id__lt", joinedIDLt...); err != nil {
			return err
		}
	}

	if o.IDLte != nil {

		// binding items for id__lte
		joinedIDLte := o.bindParamIDLte(reg)

		// query array param id__lte
		if err := r.SetQueryParam("id__lte", joinedIDLte...); err != nil {
			return err
		}
	}

	if o.IDn != nil {

		// binding items for id__n
		joinedIDn := o.bindParamIDn(reg)

		// query array param id__n
		if err := r.SetQueryParam("id__n", joinedIDn...); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := conv.FormatInteger(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Model != nil {

		// binding items for model
		joinedModel := o.bindParamModel(reg)

		// query array param model
		if err := r.SetQueryParam("model", joinedModel...); err != nil {
			return err
		}
	}

	if o.ModelEmpty != nil {

		// query param model__empty
		var qrModelEmpty bool

		if o.ModelEmpty != nil {
			qrModelEmpty = *o.ModelEmpty
		}
		qModelEmpty := conv.FormatBool(qrModelEmpty)
		if qModelEmpty != "" {

			if err := r.SetQueryParam("model__empty", qModelEmpty); err != nil {
				return err
			}
		}
	}

	if o.ModelIc != nil {

		// binding items for model__ic
		joinedModelIc := o.bindParamModelIc(reg)

		// query array param model__ic
		if err := r.SetQueryParam("model__ic", joinedModelIc...); err != nil {
			return err
		}
	}

	if o.ModelIe != nil {

		// binding items for model__ie
		joinedModelIe := o.bindParamModelIe(reg)

		// query array param model__ie
		if err := r.SetQueryParam("model__ie", joinedModelIe...); err != nil {
			return err
		}
	}

	if o.ModelIew != nil {

		// binding items for model__iew
		joinedModelIew := o.bindParamModelIew(reg)

		// query array param model__iew
		if err := r.SetQueryParam("model__iew", joinedModelIew...); err != nil {
			return err
		}
	}

	if o.ModelIregex != nil {

		// binding items for model__iregex
		joinedModelIregex := o.bindParamModelIregex(reg)

		// query array param model__iregex
		if err := r.SetQueryParam("model__iregex", joinedModelIregex...); err != nil {
			return err
		}
	}

	if o.ModelIsw != nil {

		// binding items for model__isw
		joinedModelIsw := o.bindParamModelIsw(reg)

		// query array param model__isw
		if err := r.SetQueryParam("model__isw", joinedModelIsw...); err != nil {
			return err
		}
	}

	if o.Modeln != nil {

		// binding items for model__n
		joinedModeln := o.bindParamModeln(reg)

		// query array param model__n
		if err := r.SetQueryParam("model__n", joinedModeln...); err != nil {
			return err
		}
	}

	if o.ModelNic != nil {

		// binding items for model__nic
		joinedModelNic := o.bindParamModelNic(reg)

		// query array param model__nic
		if err := r.SetQueryParam("model__nic", joinedModelNic...); err != nil {
			return err
		}
	}

	if o.ModelNie != nil {

		// binding items for model__nie
		joinedModelNie := o.bindParamModelNie(reg)

		// query array param model__nie
		if err := r.SetQueryParam("model__nie", joinedModelNie...); err != nil {
			return err
		}
	}

	if o.ModelNiew != nil {

		// binding items for model__niew
		joinedModelNiew := o.bindParamModelNiew(reg)

		// query array param model__niew
		if err := r.SetQueryParam("model__niew", joinedModelNiew...); err != nil {
			return err
		}
	}

	if o.ModelNisw != nil {

		// binding items for model__nisw
		joinedModelNisw := o.bindParamModelNisw(reg)

		// query array param model__nisw
		if err := r.SetQueryParam("model__nisw", joinedModelNisw...); err != nil {
			return err
		}
	}

	if o.ModelRegex != nil {

		// binding items for model__regex
		joinedModelRegex := o.bindParamModelRegex(reg)

		// query array param model__regex
		if err := r.SetQueryParam("model__regex", joinedModelRegex...); err != nil {
			return err
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := conv.FormatInteger(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string

		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {

			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}
	}

	if o.Public != nil {

		// query param public
		var qrPublic bool

		if o.Public != nil {
			qrPublic = *o.Public
		}
		qPublic := conv.FormatBool(qrPublic)
		if qPublic != "" {

			if err := r.SetQueryParam("public", qPublic); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if o.Start != nil {

		// query param start
		var qrStart int64

		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := conv.FormatInteger(qrStart)
		if qStart != "" {

			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamCoreObjectTypesList binds the parameter app_label.
func (o *CoreObjectTypesListParams) bindParamAppLabel(formats strfmt.Registry) []string {
	appLabelIR := o.AppLabel

	var appLabelIC []string
	for _, appLabelIIR := range appLabelIR { // explode []string

		appLabelIIV := appLabelIIR // string as string
		appLabelIC = append(appLabelIC, appLabelIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelIS := stringutils.JoinByFormat(appLabelIC, "multi")

	return appLabelIS
}

// bindParamCoreObjectTypesList binds the parameter app_label__ic.
func (o *CoreObjectTypesListParams) bindParamAppLabelIc(formats strfmt.Registry) []string {
	appLabelIcIR := o.AppLabelIc

	var appLabelIcIC []string
	for _, appLabelIcIIR := range appLabelIcIR { // explode []string

		appLabelIcIIV := appLabelIcIIR // string as string
		appLabelIcIC = append(appLabelIcIC, appLabelIcIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelIcIS := stringutils.JoinByFormat(appLabelIcIC, "multi")

	return appLabelIcIS
}

// bindParamCoreObjectTypesList binds the parameter app_label__ie.
func (o *CoreObjectTypesListParams) bindParamAppLabelIe(formats strfmt.Registry) []string {
	appLabelIeIR := o.AppLabelIe

	var appLabelIeIC []string
	for _, appLabelIeIIR := range appLabelIeIR { // explode []string

		appLabelIeIIV := appLabelIeIIR // string as string
		appLabelIeIC = append(appLabelIeIC, appLabelIeIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelIeIS := stringutils.JoinByFormat(appLabelIeIC, "multi")

	return appLabelIeIS
}

// bindParamCoreObjectTypesList binds the parameter app_label__iew.
func (o *CoreObjectTypesListParams) bindParamAppLabelIew(formats strfmt.Registry) []string {
	appLabelIewIR := o.AppLabelIew

	var appLabelIewIC []string
	for _, appLabelIewIIR := range appLabelIewIR { // explode []string

		appLabelIewIIV := appLabelIewIIR // string as string
		appLabelIewIC = append(appLabelIewIC, appLabelIewIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelIewIS := stringutils.JoinByFormat(appLabelIewIC, "multi")

	return appLabelIewIS
}

// bindParamCoreObjectTypesList binds the parameter app_label__iregex.
func (o *CoreObjectTypesListParams) bindParamAppLabelIregex(formats strfmt.Registry) []string {
	appLabelIregexIR := o.AppLabelIregex

	var appLabelIregexIC []string
	for _, appLabelIregexIIR := range appLabelIregexIR { // explode []string

		appLabelIregexIIV := appLabelIregexIIR // string as string
		appLabelIregexIC = append(appLabelIregexIC, appLabelIregexIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelIregexIS := stringutils.JoinByFormat(appLabelIregexIC, "multi")

	return appLabelIregexIS
}

// bindParamCoreObjectTypesList binds the parameter app_label__isw.
func (o *CoreObjectTypesListParams) bindParamAppLabelIsw(formats strfmt.Registry) []string {
	appLabelIswIR := o.AppLabelIsw

	var appLabelIswIC []string
	for _, appLabelIswIIR := range appLabelIswIR { // explode []string

		appLabelIswIIV := appLabelIswIIR // string as string
		appLabelIswIC = append(appLabelIswIC, appLabelIswIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelIswIS := stringutils.JoinByFormat(appLabelIswIC, "multi")

	return appLabelIswIS
}

// bindParamCoreObjectTypesList binds the parameter app_label__n.
func (o *CoreObjectTypesListParams) bindParamAppLabeln(formats strfmt.Registry) []string {
	appLabelnIR := o.AppLabeln

	var appLabelnIC []string
	for _, appLabelnIIR := range appLabelnIR { // explode []string

		appLabelnIIV := appLabelnIIR // string as string
		appLabelnIC = append(appLabelnIC, appLabelnIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelnIS := stringutils.JoinByFormat(appLabelnIC, "multi")

	return appLabelnIS
}

// bindParamCoreObjectTypesList binds the parameter app_label__nic.
func (o *CoreObjectTypesListParams) bindParamAppLabelNic(formats strfmt.Registry) []string {
	appLabelNicIR := o.AppLabelNic

	var appLabelNicIC []string
	for _, appLabelNicIIR := range appLabelNicIR { // explode []string

		appLabelNicIIV := appLabelNicIIR // string as string
		appLabelNicIC = append(appLabelNicIC, appLabelNicIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelNicIS := stringutils.JoinByFormat(appLabelNicIC, "multi")

	return appLabelNicIS
}

// bindParamCoreObjectTypesList binds the parameter app_label__nie.
func (o *CoreObjectTypesListParams) bindParamAppLabelNie(formats strfmt.Registry) []string {
	appLabelNieIR := o.AppLabelNie

	var appLabelNieIC []string
	for _, appLabelNieIIR := range appLabelNieIR { // explode []string

		appLabelNieIIV := appLabelNieIIR // string as string
		appLabelNieIC = append(appLabelNieIC, appLabelNieIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelNieIS := stringutils.JoinByFormat(appLabelNieIC, "multi")

	return appLabelNieIS
}

// bindParamCoreObjectTypesList binds the parameter app_label__niew.
func (o *CoreObjectTypesListParams) bindParamAppLabelNiew(formats strfmt.Registry) []string {
	appLabelNiewIR := o.AppLabelNiew

	var appLabelNiewIC []string
	for _, appLabelNiewIIR := range appLabelNiewIR { // explode []string

		appLabelNiewIIV := appLabelNiewIIR // string as string
		appLabelNiewIC = append(appLabelNiewIC, appLabelNiewIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelNiewIS := stringutils.JoinByFormat(appLabelNiewIC, "multi")

	return appLabelNiewIS
}

// bindParamCoreObjectTypesList binds the parameter app_label__nisw.
func (o *CoreObjectTypesListParams) bindParamAppLabelNisw(formats strfmt.Registry) []string {
	appLabelNiswIR := o.AppLabelNisw

	var appLabelNiswIC []string
	for _, appLabelNiswIIR := range appLabelNiswIR { // explode []string

		appLabelNiswIIV := appLabelNiswIIR // string as string
		appLabelNiswIC = append(appLabelNiswIC, appLabelNiswIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelNiswIS := stringutils.JoinByFormat(appLabelNiswIC, "multi")

	return appLabelNiswIS
}

// bindParamCoreObjectTypesList binds the parameter app_label__regex.
func (o *CoreObjectTypesListParams) bindParamAppLabelRegex(formats strfmt.Registry) []string {
	appLabelRegexIR := o.AppLabelRegex

	var appLabelRegexIC []string
	for _, appLabelRegexIIR := range appLabelRegexIR { // explode []string

		appLabelRegexIIV := appLabelRegexIIR // string as string
		appLabelRegexIC = append(appLabelRegexIC, appLabelRegexIIV)
	}

	// items.CollectionFormat: "multi"
	appLabelRegexIS := stringutils.JoinByFormat(appLabelRegexIC, "multi")

	return appLabelRegexIS
}

// bindParamCoreObjectTypesList binds the parameter id.
func (o *CoreObjectTypesListParams) bindParamID(formats strfmt.Registry) []string {
	idIR := o.ID

	var idIC []string
	for _, idIIR := range idIR { // explode []int64

		idIIV := conv.FormatInteger(idIIR) // int64 as string
		idIC = append(idIC, idIIV)
	}

	// items.CollectionFormat: "multi"
	idIS := stringutils.JoinByFormat(idIC, "multi")

	return idIS
}

// bindParamCoreObjectTypesList binds the parameter id__gt.
func (o *CoreObjectTypesListParams) bindParamIDGt(formats strfmt.Registry) []string {
	idGtIR := o.IDGt

	var idGtIC []string
	for _, idGtIIR := range idGtIR { // explode []int64

		idGtIIV := conv.FormatInteger(idGtIIR) // int64 as string
		idGtIC = append(idGtIC, idGtIIV)
	}

	// items.CollectionFormat: "multi"
	idGtIS := stringutils.JoinByFormat(idGtIC, "multi")

	return idGtIS
}

// bindParamCoreObjectTypesList binds the parameter id__gte.
func (o *CoreObjectTypesListParams) bindParamIDGte(formats strfmt.Registry) []string {
	idGteIR := o.IDGte

	var idGteIC []string
	for _, idGteIIR := range idGteIR { // explode []int64

		idGteIIV := conv.FormatInteger(idGteIIR) // int64 as string
		idGteIC = append(idGteIC, idGteIIV)
	}

	// items.CollectionFormat: "multi"
	idGteIS := stringutils.JoinByFormat(idGteIC, "multi")

	return idGteIS
}

// bindParamCoreObjectTypesList binds the parameter id__lt.
func (o *CoreObjectTypesListParams) bindParamIDLt(formats strfmt.Registry) []string {
	idLtIR := o.IDLt

	var idLtIC []string
	for _, idLtIIR := range idLtIR { // explode []int64

		idLtIIV := conv.FormatInteger(idLtIIR) // int64 as string
		idLtIC = append(idLtIC, idLtIIV)
	}

	// items.CollectionFormat: "multi"
	idLtIS := stringutils.JoinByFormat(idLtIC, "multi")

	return idLtIS
}

// bindParamCoreObjectTypesList binds the parameter id__lte.
func (o *CoreObjectTypesListParams) bindParamIDLte(formats strfmt.Registry) []string {
	idLteIR := o.IDLte

	var idLteIC []string
	for _, idLteIIR := range idLteIR { // explode []int64

		idLteIIV := conv.FormatInteger(idLteIIR) // int64 as string
		idLteIC = append(idLteIC, idLteIIV)
	}

	// items.CollectionFormat: "multi"
	idLteIS := stringutils.JoinByFormat(idLteIC, "multi")

	return idLteIS
}

// bindParamCoreObjectTypesList binds the parameter id__n.
func (o *CoreObjectTypesListParams) bindParamIDn(formats strfmt.Registry) []string {
	idnIR := o.IDn

	var idnIC []string
	for _, idnIIR := range idnIR { // explode []int64

		idnIIV := conv.FormatInteger(idnIIR) // int64 as string
		idnIC = append(idnIC, idnIIV)
	}

	// items.CollectionFormat: "multi"
	idnIS := stringutils.JoinByFormat(idnIC, "multi")

	return idnIS
}

// bindParamCoreObjectTypesList binds the parameter model.
func (o *CoreObjectTypesListParams) bindParamModel(formats strfmt.Registry) []string {
	modelIR := o.Model

	var modelIC []string
	for _, modelIIR := range modelIR { // explode []string

		modelIIV := modelIIR // string as string
		modelIC = append(modelIC, modelIIV)
	}

	// items.CollectionFormat: "multi"
	modelIS := stringutils.JoinByFormat(modelIC, "multi")

	return modelIS
}

// bindParamCoreObjectTypesList binds the parameter model__ic.
func (o *CoreObjectTypesListParams) bindParamModelIc(formats strfmt.Registry) []string {
	modelIcIR := o.ModelIc

	var modelIcIC []string
	for _, modelIcIIR := range modelIcIR { // explode []string

		modelIcIIV := modelIcIIR // string as string
		modelIcIC = append(modelIcIC, modelIcIIV)
	}

	// items.CollectionFormat: "multi"
	modelIcIS := stringutils.JoinByFormat(modelIcIC, "multi")

	return modelIcIS
}

// bindParamCoreObjectTypesList binds the parameter model__ie.
func (o *CoreObjectTypesListParams) bindParamModelIe(formats strfmt.Registry) []string {
	modelIeIR := o.ModelIe

	var modelIeIC []string
	for _, modelIeIIR := range modelIeIR { // explode []string

		modelIeIIV := modelIeIIR // string as string
		modelIeIC = append(modelIeIC, modelIeIIV)
	}

	// items.CollectionFormat: "multi"
	modelIeIS := stringutils.JoinByFormat(modelIeIC, "multi")

	return modelIeIS
}

// bindParamCoreObjectTypesList binds the parameter model__iew.
func (o *CoreObjectTypesListParams) bindParamModelIew(formats strfmt.Registry) []string {
	modelIewIR := o.ModelIew

	var modelIewIC []string
	for _, modelIewIIR := range modelIewIR { // explode []string

		modelIewIIV := modelIewIIR // string as string
		modelIewIC = append(modelIewIC, modelIewIIV)
	}

	// items.CollectionFormat: "multi"
	modelIewIS := stringutils.JoinByFormat(modelIewIC, "multi")

	return modelIewIS
}

// bindParamCoreObjectTypesList binds the parameter model__iregex.
func (o *CoreObjectTypesListParams) bindParamModelIregex(formats strfmt.Registry) []string {
	modelIregexIR := o.ModelIregex

	var modelIregexIC []string
	for _, modelIregexIIR := range modelIregexIR { // explode []string

		modelIregexIIV := modelIregexIIR // string as string
		modelIregexIC = append(modelIregexIC, modelIregexIIV)
	}

	// items.CollectionFormat: "multi"
	modelIregexIS := stringutils.JoinByFormat(modelIregexIC, "multi")

	return modelIregexIS
}

// bindParamCoreObjectTypesList binds the parameter model__isw.
func (o *CoreObjectTypesListParams) bindParamModelIsw(formats strfmt.Registry) []string {
	modelIswIR := o.ModelIsw

	var modelIswIC []string
	for _, modelIswIIR := range modelIswIR { // explode []string

		modelIswIIV := modelIswIIR // string as string
		modelIswIC = append(modelIswIC, modelIswIIV)
	}

	// items.CollectionFormat: "multi"
	modelIswIS := stringutils.JoinByFormat(modelIswIC, "multi")

	return modelIswIS
}

// bindParamCoreObjectTypesList binds the parameter model__n.
func (o *CoreObjectTypesListParams) bindParamModeln(formats strfmt.Registry) []string {
	modelnIR := o.Modeln

	var modelnIC []string
	for _, modelnIIR := range modelnIR { // explode []string

		modelnIIV := modelnIIR // string as string
		modelnIC = append(modelnIC, modelnIIV)
	}

	// items.CollectionFormat: "multi"
	modelnIS := stringutils.JoinByFormat(modelnIC, "multi")

	return modelnIS
}

// bindParamCoreObjectTypesList binds the parameter model__nic.
func (o *CoreObjectTypesListParams) bindParamModelNic(formats strfmt.Registry) []string {
	modelNicIR := o.ModelNic

	var modelNicIC []string
	for _, modelNicIIR := range modelNicIR { // explode []string

		modelNicIIV := modelNicIIR // string as string
		modelNicIC = append(modelNicIC, modelNicIIV)
	}

	// items.CollectionFormat: "multi"
	modelNicIS := stringutils.JoinByFormat(modelNicIC, "multi")

	return modelNicIS
}

// bindParamCoreObjectTypesList binds the parameter model__nie.
func (o *CoreObjectTypesListParams) bindParamModelNie(formats strfmt.Registry) []string {
	modelNieIR := o.ModelNie

	var modelNieIC []string
	for _, modelNieIIR := range modelNieIR { // explode []string

		modelNieIIV := modelNieIIR // string as string
		modelNieIC = append(modelNieIC, modelNieIIV)
	}

	// items.CollectionFormat: "multi"
	modelNieIS := stringutils.JoinByFormat(modelNieIC, "multi")

	return modelNieIS
}

// bindParamCoreObjectTypesList binds the parameter model__niew.
func (o *CoreObjectTypesListParams) bindParamModelNiew(formats strfmt.Registry) []string {
	modelNiewIR := o.ModelNiew

	var modelNiewIC []string
	for _, modelNiewIIR := range modelNiewIR { // explode []string

		modelNiewIIV := modelNiewIIR // string as string
		modelNiewIC = append(modelNiewIC, modelNiewIIV)
	}

	// items.CollectionFormat: "multi"
	modelNiewIS := stringutils.JoinByFormat(modelNiewIC, "multi")

	return modelNiewIS
}

// bindParamCoreObjectTypesList binds the parameter model__nisw.
func (o *CoreObjectTypesListParams) bindParamModelNisw(formats strfmt.Registry) []string {
	modelNiswIR := o.ModelNisw

	var modelNiswIC []string
	for _, modelNiswIIR := range modelNiswIR { // explode []string

		modelNiswIIV := modelNiswIIR // string as string
		modelNiswIC = append(modelNiswIC, modelNiswIIV)
	}

	// items.CollectionFormat: "multi"
	modelNiswIS := stringutils.JoinByFormat(modelNiswIC, "multi")

	return modelNiswIS
}

// bindParamCoreObjectTypesList binds the parameter model__regex.
func (o *CoreObjectTypesListParams) bindParamModelRegex(formats strfmt.Registry) []string {
	modelRegexIR := o.ModelRegex

	var modelRegexIC []string
	for _, modelRegexIIR := range modelRegexIR { // explode []string

		modelRegexIIV := modelRegexIIR // string as string
		modelRegexIC = append(modelRegexIC, modelRegexIIV)
	}

	// items.CollectionFormat: "multi"
	modelRegexIS := stringutils.JoinByFormat(modelRegexIC, "multi")

	return modelRegexIS
}
