// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package core

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CoreBackgroundTasksDeleteCreateReader is a Reader for the CoreBackgroundTasksDeleteCreate structure.
type CoreBackgroundTasksDeleteCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CoreBackgroundTasksDeleteCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCoreBackgroundTasksDeleteCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCoreBackgroundTasksDeleteCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCoreBackgroundTasksDeleteCreateOK creates a CoreBackgroundTasksDeleteCreateOK with default headers values
func NewCoreBackgroundTasksDeleteCreateOK() *CoreBackgroundTasksDeleteCreateOK {
	return &CoreBackgroundTasksDeleteCreateOK{}
}

// CoreBackgroundTasksDeleteCreateOK describes a response with status code 200, with default header values.
//
// CoreBackgroundTasksDeleteCreateOK core background tasks delete create o k
type CoreBackgroundTasksDeleteCreateOK struct {
	Payload *models.BackgroundTask
}

// IsSuccess returns true when this core background tasks delete create o k response has a 2xx status code
func (o *CoreBackgroundTasksDeleteCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this core background tasks delete create o k response has a 3xx status code
func (o *CoreBackgroundTasksDeleteCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this core background tasks delete create o k response has a 4xx status code
func (o *CoreBackgroundTasksDeleteCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this core background tasks delete create o k response has a 5xx status code
func (o *CoreBackgroundTasksDeleteCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this core background tasks delete create o k response a status code equal to that given
func (o *CoreBackgroundTasksDeleteCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the core background tasks delete create o k response
func (o *CoreBackgroundTasksDeleteCreateOK) Code() int {
	return 200
}

func (o *CoreBackgroundTasksDeleteCreateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /core/background-tasks/{id}/delete/][%d] coreBackgroundTasksDeleteCreateOK %s", 200, payload)
}

func (o *CoreBackgroundTasksDeleteCreateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /core/background-tasks/{id}/delete/][%d] coreBackgroundTasksDeleteCreateOK %s", 200, payload)
}

func (o *CoreBackgroundTasksDeleteCreateOK) GetPayload() *models.BackgroundTask {
	return o.Payload
}

func (o *CoreBackgroundTasksDeleteCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BackgroundTask)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCoreBackgroundTasksDeleteCreateDefault creates a CoreBackgroundTasksDeleteCreateDefault with default headers values
func NewCoreBackgroundTasksDeleteCreateDefault(code int) *CoreBackgroundTasksDeleteCreateDefault {
	return &CoreBackgroundTasksDeleteCreateDefault{
		_statusCode: code,
	}
}

// CoreBackgroundTasksDeleteCreateDefault describes a response with status code -1, with default header values.
//
// CoreBackgroundTasksDeleteCreateDefault core background tasks delete create default
type CoreBackgroundTasksDeleteCreateDefault struct {
	_statusCode int

	Payload any
}

// IsSuccess returns true when this core background tasks delete create default response has a 2xx status code
func (o *CoreBackgroundTasksDeleteCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this core background tasks delete create default response has a 3xx status code
func (o *CoreBackgroundTasksDeleteCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this core background tasks delete create default response has a 4xx status code
func (o *CoreBackgroundTasksDeleteCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this core background tasks delete create default response has a 5xx status code
func (o *CoreBackgroundTasksDeleteCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this core background tasks delete create default response a status code equal to that given
func (o *CoreBackgroundTasksDeleteCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the core background tasks delete create default response
func (o *CoreBackgroundTasksDeleteCreateDefault) Code() int {
	return o._statusCode
}

func (o *CoreBackgroundTasksDeleteCreateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /core/background-tasks/{id}/delete/][%d] core_background_tasks_delete_create default %s", o._statusCode, payload)
}

func (o *CoreBackgroundTasksDeleteCreateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /core/background-tasks/{id}/delete/][%d] core_background_tasks_delete_create default %s", o._statusCode, payload)
}

func (o *CoreBackgroundTasksDeleteCreateDefault) GetPayload() any {
	return o.Payload
}

func (o *CoreBackgroundTasksDeleteCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
