// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package core

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CoreDataFilesRetrieveReader is a Reader for the CoreDataFilesRetrieve structure.
type CoreDataFilesRetrieveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CoreDataFilesRetrieveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCoreDataFilesRetrieveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCoreDataFilesRetrieveDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCoreDataFilesRetrieveOK creates a CoreDataFilesRetrieveOK with default headers values
func NewCoreDataFilesRetrieveOK() *CoreDataFilesRetrieveOK {
	return &CoreDataFilesRetrieveOK{}
}

// CoreDataFilesRetrieveOK describes a response with status code 200, with default header values.
//
// CoreDataFilesRetrieveOK core data files retrieve o k
type CoreDataFilesRetrieveOK struct {
	Payload *models.DataFile
}

// IsSuccess returns true when this core data files retrieve o k response has a 2xx status code
func (o *CoreDataFilesRetrieveOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this core data files retrieve o k response has a 3xx status code
func (o *CoreDataFilesRetrieveOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this core data files retrieve o k response has a 4xx status code
func (o *CoreDataFilesRetrieveOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this core data files retrieve o k response has a 5xx status code
func (o *CoreDataFilesRetrieveOK) IsServerError() bool {
	return false
}

// IsCode returns true when this core data files retrieve o k response a status code equal to that given
func (o *CoreDataFilesRetrieveOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the core data files retrieve o k response
func (o *CoreDataFilesRetrieveOK) Code() int {
	return 200
}

func (o *CoreDataFilesRetrieveOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /core/data-files/{id}/][%d] coreDataFilesRetrieveOK %s", 200, payload)
}

func (o *CoreDataFilesRetrieveOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /core/data-files/{id}/][%d] coreDataFilesRetrieveOK %s", 200, payload)
}

func (o *CoreDataFilesRetrieveOK) GetPayload() *models.DataFile {
	return o.Payload
}

func (o *CoreDataFilesRetrieveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataFile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCoreDataFilesRetrieveDefault creates a CoreDataFilesRetrieveDefault with default headers values
func NewCoreDataFilesRetrieveDefault(code int) *CoreDataFilesRetrieveDefault {
	return &CoreDataFilesRetrieveDefault{
		_statusCode: code,
	}
}

// CoreDataFilesRetrieveDefault describes a response with status code -1, with default header values.
//
// CoreDataFilesRetrieveDefault core data files retrieve default
type CoreDataFilesRetrieveDefault struct {
	_statusCode int

	Payload any
}

// IsSuccess returns true when this core data files retrieve default response has a 2xx status code
func (o *CoreDataFilesRetrieveDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this core data files retrieve default response has a 3xx status code
func (o *CoreDataFilesRetrieveDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this core data files retrieve default response has a 4xx status code
func (o *CoreDataFilesRetrieveDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this core data files retrieve default response has a 5xx status code
func (o *CoreDataFilesRetrieveDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this core data files retrieve default response a status code equal to that given
func (o *CoreDataFilesRetrieveDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the core data files retrieve default response
func (o *CoreDataFilesRetrieveDefault) Code() int {
	return o._statusCode
}

func (o *CoreDataFilesRetrieveDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /core/data-files/{id}/][%d] core_data_files_retrieve default %s", o._statusCode, payload)
}

func (o *CoreDataFilesRetrieveDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /core/data-files/{id}/][%d] core_data_files_retrieve default %s", o._statusCode, payload)
}

func (o *CoreDataFilesRetrieveDefault) GetPayload() any {
	return o.Payload
}

func (o *CoreDataFilesRetrieveDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
