// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package core

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CoreBackgroundWorkersRetrieveByNameReader is a Reader for the CoreBackgroundWorkersRetrieveByName structure.
type CoreBackgroundWorkersRetrieveByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CoreBackgroundWorkersRetrieveByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCoreBackgroundWorkersRetrieveByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCoreBackgroundWorkersRetrieveByNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCoreBackgroundWorkersRetrieveByNameOK creates a CoreBackgroundWorkersRetrieveByNameOK with default headers values
func NewCoreBackgroundWorkersRetrieveByNameOK() *CoreBackgroundWorkersRetrieveByNameOK {
	return &CoreBackgroundWorkersRetrieveByNameOK{}
}

// CoreBackgroundWorkersRetrieveByNameOK describes a response with status code 200, with default header values.
//
// CoreBackgroundWorkersRetrieveByNameOK core background workers retrieve by name o k
type CoreBackgroundWorkersRetrieveByNameOK struct {
	Payload map[string]any
}

// IsSuccess returns true when this core background workers retrieve by name o k response has a 2xx status code
func (o *CoreBackgroundWorkersRetrieveByNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this core background workers retrieve by name o k response has a 3xx status code
func (o *CoreBackgroundWorkersRetrieveByNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this core background workers retrieve by name o k response has a 4xx status code
func (o *CoreBackgroundWorkersRetrieveByNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this core background workers retrieve by name o k response has a 5xx status code
func (o *CoreBackgroundWorkersRetrieveByNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this core background workers retrieve by name o k response a status code equal to that given
func (o *CoreBackgroundWorkersRetrieveByNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the core background workers retrieve by name o k response
func (o *CoreBackgroundWorkersRetrieveByNameOK) Code() int {
	return 200
}

func (o *CoreBackgroundWorkersRetrieveByNameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /core/background-workers/{name}/][%d] coreBackgroundWorkersRetrieveByNameOK %s", 200, payload)
}

func (o *CoreBackgroundWorkersRetrieveByNameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /core/background-workers/{name}/][%d] coreBackgroundWorkersRetrieveByNameOK %s", 200, payload)
}

func (o *CoreBackgroundWorkersRetrieveByNameOK) GetPayload() map[string]any {
	return o.Payload
}

func (o *CoreBackgroundWorkersRetrieveByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCoreBackgroundWorkersRetrieveByNameDefault creates a CoreBackgroundWorkersRetrieveByNameDefault with default headers values
func NewCoreBackgroundWorkersRetrieveByNameDefault(code int) *CoreBackgroundWorkersRetrieveByNameDefault {
	return &CoreBackgroundWorkersRetrieveByNameDefault{
		_statusCode: code,
	}
}

// CoreBackgroundWorkersRetrieveByNameDefault describes a response with status code -1, with default header values.
//
// CoreBackgroundWorkersRetrieveByNameDefault core background workers retrieve by name default
type CoreBackgroundWorkersRetrieveByNameDefault struct {
	_statusCode int

	Payload any
}

// IsSuccess returns true when this core background workers retrieve by name default response has a 2xx status code
func (o *CoreBackgroundWorkersRetrieveByNameDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this core background workers retrieve by name default response has a 3xx status code
func (o *CoreBackgroundWorkersRetrieveByNameDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this core background workers retrieve by name default response has a 4xx status code
func (o *CoreBackgroundWorkersRetrieveByNameDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this core background workers retrieve by name default response has a 5xx status code
func (o *CoreBackgroundWorkersRetrieveByNameDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this core background workers retrieve by name default response a status code equal to that given
func (o *CoreBackgroundWorkersRetrieveByNameDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the core background workers retrieve by name default response
func (o *CoreBackgroundWorkersRetrieveByNameDefault) Code() int {
	return o._statusCode
}

func (o *CoreBackgroundWorkersRetrieveByNameDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /core/background-workers/{name}/][%d] core_background_workers_retrieve_by_name default %s", o._statusCode, payload)
}

func (o *CoreBackgroundWorkersRetrieveByNameDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /core/background-workers/{name}/][%d] core_background_workers_retrieve_by_name default %s", o._statusCode, payload)
}

func (o *CoreBackgroundWorkersRetrieveByNameDefault) GetPayload() any {
	return o.Payload
}

func (o *CoreBackgroundWorkersRetrieveByNameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
