// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDcimModulesPartialUpdateParams creates a new DcimModulesPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDcimModulesPartialUpdateParams() *DcimModulesPartialUpdateParams {
	return NewDcimModulesPartialUpdateParamsWithTimeout(cr.DefaultTimeout)
}

// NewDcimModulesPartialUpdateParamsWithTimeout creates a new DcimModulesPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewDcimModulesPartialUpdateParamsWithTimeout(timeout time.Duration) *DcimModulesPartialUpdateParams {
	return &DcimModulesPartialUpdateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDcimModulesPartialUpdateParamsWithContext creates a new DcimModulesPartialUpdateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimModulesPartialUpdateParams].
func NewDcimModulesPartialUpdateParamsWithContext(ctx context.Context) *DcimModulesPartialUpdateParams {
	return &DcimModulesPartialUpdateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDcimModulesPartialUpdateParamsWithHTTPClient creates a new DcimModulesPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewDcimModulesPartialUpdateParamsWithHTTPClient(client *http.Client) *DcimModulesPartialUpdateParams {
	return &DcimModulesPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
DcimModulesPartialUpdateParams contains all the parameters to send to the API endpoint

	for the dcim modules partial update operation.

	Typically these are written to a http.Request.
*/
type DcimModulesPartialUpdateParams struct {

	// Data.
	Data *models.WritableModule

	// ID.
	//
	// A unique integer value identifying this module.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the dcim modules partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimModulesPartialUpdateParams) WithDefaults() *DcimModulesPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dcim modules partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimModulesPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dcim modules partial update params.
func (o *DcimModulesPartialUpdateParams) WithTimeout(timeout time.Duration) *DcimModulesPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim modules partial update params.
func (o *DcimModulesPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the dcim modules partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimModulesPartialUpdateParams].
func (o *DcimModulesPartialUpdateParams) WithContext(ctx context.Context) *DcimModulesPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim modules partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimModulesPartialUpdateParams].
func (o *DcimModulesPartialUpdateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim modules partial update params.
func (o *DcimModulesPartialUpdateParams) WithHTTPClient(client *http.Client) *DcimModulesPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim modules partial update params.
func (o *DcimModulesPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the dcim modules partial update params.
func (o *DcimModulesPartialUpdateParams) WithData(data *models.WritableModule) *DcimModulesPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the dcim modules partial update params.
func (o *DcimModulesPartialUpdateParams) SetData(data *models.WritableModule) {
	o.Data = data
}

// WithID adds the id to the dcim modules partial update params.
func (o *DcimModulesPartialUpdateParams) WithID(id int64) *DcimModulesPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim modules partial update params.
func (o *DcimModulesPartialUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DcimModulesPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
