// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDcimModuleBaysRetrieveParams creates a new DcimModuleBaysRetrieveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDcimModuleBaysRetrieveParams() *DcimModuleBaysRetrieveParams {
	return NewDcimModuleBaysRetrieveParamsWithTimeout(cr.DefaultTimeout)
}

// NewDcimModuleBaysRetrieveParamsWithTimeout creates a new DcimModuleBaysRetrieveParams object
// with the ability to set a timeout on a request.
func NewDcimModuleBaysRetrieveParamsWithTimeout(timeout time.Duration) *DcimModuleBaysRetrieveParams {
	return &DcimModuleBaysRetrieveParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDcimModuleBaysRetrieveParamsWithContext creates a new DcimModuleBaysRetrieveParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimModuleBaysRetrieveParams].
func NewDcimModuleBaysRetrieveParamsWithContext(ctx context.Context) *DcimModuleBaysRetrieveParams {
	return &DcimModuleBaysRetrieveParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDcimModuleBaysRetrieveParamsWithHTTPClient creates a new DcimModuleBaysRetrieveParams object
// with the ability to set a custom HTTPClient for a request.
func NewDcimModuleBaysRetrieveParamsWithHTTPClient(client *http.Client) *DcimModuleBaysRetrieveParams {
	return &DcimModuleBaysRetrieveParams{
		HTTPClient: client,
	}
}

/*
DcimModuleBaysRetrieveParams contains all the parameters to send to the API endpoint

	for the dcim module bays retrieve operation.

	Typically these are written to a http.Request.
*/
type DcimModuleBaysRetrieveParams struct {

	// ID.
	//
	// A unique integer value identifying this module bay.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the dcim module bays retrieve params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimModuleBaysRetrieveParams) WithDefaults() *DcimModuleBaysRetrieveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dcim module bays retrieve params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimModuleBaysRetrieveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dcim module bays retrieve params.
func (o *DcimModuleBaysRetrieveParams) WithTimeout(timeout time.Duration) *DcimModuleBaysRetrieveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim module bays retrieve params.
func (o *DcimModuleBaysRetrieveParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the dcim module bays retrieve params.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimModuleBaysRetrieveParams].
func (o *DcimModuleBaysRetrieveParams) WithContext(ctx context.Context) *DcimModuleBaysRetrieveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim module bays retrieve params.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimModuleBaysRetrieveParams].
func (o *DcimModuleBaysRetrieveParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim module bays retrieve params.
func (o *DcimModuleBaysRetrieveParams) WithHTTPClient(client *http.Client) *DcimModuleBaysRetrieveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim module bays retrieve params.
func (o *DcimModuleBaysRetrieveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the dcim module bays retrieve params.
func (o *DcimModuleBaysRetrieveParams) WithID(id int64) *DcimModuleBaysRetrieveParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim module bays retrieve params.
func (o *DcimModuleBaysRetrieveParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DcimModuleBaysRetrieveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
