// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DcimInterfaceTemplatesRetrieveReader is a Reader for the DcimInterfaceTemplatesRetrieve structure.
type DcimInterfaceTemplatesRetrieveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimInterfaceTemplatesRetrieveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDcimInterfaceTemplatesRetrieveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDcimInterfaceTemplatesRetrieveDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimInterfaceTemplatesRetrieveOK creates a DcimInterfaceTemplatesRetrieveOK with default headers values
func NewDcimInterfaceTemplatesRetrieveOK() *DcimInterfaceTemplatesRetrieveOK {
	return &DcimInterfaceTemplatesRetrieveOK{}
}

// DcimInterfaceTemplatesRetrieveOK describes a response with status code 200, with default header values.
//
// DcimInterfaceTemplatesRetrieveOK dcim interface templates retrieve o k
type DcimInterfaceTemplatesRetrieveOK struct {
	Payload *models.InterfaceTemplate
}

// IsSuccess returns true when this dcim interface templates retrieve o k response has a 2xx status code
func (o *DcimInterfaceTemplatesRetrieveOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim interface templates retrieve o k response has a 3xx status code
func (o *DcimInterfaceTemplatesRetrieveOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim interface templates retrieve o k response has a 4xx status code
func (o *DcimInterfaceTemplatesRetrieveOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim interface templates retrieve o k response has a 5xx status code
func (o *DcimInterfaceTemplatesRetrieveOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim interface templates retrieve o k response a status code equal to that given
func (o *DcimInterfaceTemplatesRetrieveOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim interface templates retrieve o k response
func (o *DcimInterfaceTemplatesRetrieveOK) Code() int {
	return 200
}

func (o *DcimInterfaceTemplatesRetrieveOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dcim/interface-templates/{id}/][%d] dcimInterfaceTemplatesRetrieveOK %s", 200, payload)
}

func (o *DcimInterfaceTemplatesRetrieveOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dcim/interface-templates/{id}/][%d] dcimInterfaceTemplatesRetrieveOK %s", 200, payload)
}

func (o *DcimInterfaceTemplatesRetrieveOK) GetPayload() *models.InterfaceTemplate {
	return o.Payload
}

func (o *DcimInterfaceTemplatesRetrieveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InterfaceTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDcimInterfaceTemplatesRetrieveDefault creates a DcimInterfaceTemplatesRetrieveDefault with default headers values
func NewDcimInterfaceTemplatesRetrieveDefault(code int) *DcimInterfaceTemplatesRetrieveDefault {
	return &DcimInterfaceTemplatesRetrieveDefault{
		_statusCode: code,
	}
}

// DcimInterfaceTemplatesRetrieveDefault describes a response with status code -1, with default header values.
//
// DcimInterfaceTemplatesRetrieveDefault dcim interface templates retrieve default
type DcimInterfaceTemplatesRetrieveDefault struct {
	_statusCode int

	Payload any
}

// IsSuccess returns true when this dcim interface templates retrieve default response has a 2xx status code
func (o *DcimInterfaceTemplatesRetrieveDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim interface templates retrieve default response has a 3xx status code
func (o *DcimInterfaceTemplatesRetrieveDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim interface templates retrieve default response has a 4xx status code
func (o *DcimInterfaceTemplatesRetrieveDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim interface templates retrieve default response has a 5xx status code
func (o *DcimInterfaceTemplatesRetrieveDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim interface templates retrieve default response a status code equal to that given
func (o *DcimInterfaceTemplatesRetrieveDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the dcim interface templates retrieve default response
func (o *DcimInterfaceTemplatesRetrieveDefault) Code() int {
	return o._statusCode
}

func (o *DcimInterfaceTemplatesRetrieveDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dcim/interface-templates/{id}/][%d] dcim_interface_templates_retrieve default %s", o._statusCode, payload)
}

func (o *DcimInterfaceTemplatesRetrieveDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dcim/interface-templates/{id}/][%d] dcim_interface_templates_retrieve default %s", o._statusCode, payload)
}

func (o *DcimInterfaceTemplatesRetrieveDefault) GetPayload() any {
	return o.Payload
}

func (o *DcimInterfaceTemplatesRetrieveDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
