// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DcimRackTypesDestroyReader is a Reader for the DcimRackTypesDestroy structure.
type DcimRackTypesDestroyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimRackTypesDestroyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDcimRackTypesDestroyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDcimRackTypesDestroyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimRackTypesDestroyNoContent creates a DcimRackTypesDestroyNoContent with default headers values
func NewDcimRackTypesDestroyNoContent() *DcimRackTypesDestroyNoContent {
	return &DcimRackTypesDestroyNoContent{}
}

// DcimRackTypesDestroyNoContent describes a response with status code 204, with default header values.
//
// DcimRackTypesDestroyNoContent dcim rack types destroy no content
type DcimRackTypesDestroyNoContent struct {
}

// IsSuccess returns true when this dcim rack types destroy no content response has a 2xx status code
func (o *DcimRackTypesDestroyNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim rack types destroy no content response has a 3xx status code
func (o *DcimRackTypesDestroyNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim rack types destroy no content response has a 4xx status code
func (o *DcimRackTypesDestroyNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim rack types destroy no content response has a 5xx status code
func (o *DcimRackTypesDestroyNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim rack types destroy no content response a status code equal to that given
func (o *DcimRackTypesDestroyNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the dcim rack types destroy no content response
func (o *DcimRackTypesDestroyNoContent) Code() int {
	return 204
}

func (o *DcimRackTypesDestroyNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dcim/rack-types/{id}/][%d] dcimRackTypesDestroyNoContent", 204)
}

func (o *DcimRackTypesDestroyNoContent) String() string {
	return fmt.Sprintf("[DELETE /dcim/rack-types/{id}/][%d] dcimRackTypesDestroyNoContent", 204)
}

func (o *DcimRackTypesDestroyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDcimRackTypesDestroyDefault creates a DcimRackTypesDestroyDefault with default headers values
func NewDcimRackTypesDestroyDefault(code int) *DcimRackTypesDestroyDefault {
	return &DcimRackTypesDestroyDefault{
		_statusCode: code,
	}
}

// DcimRackTypesDestroyDefault describes a response with status code -1, with default header values.
//
// DcimRackTypesDestroyDefault dcim rack types destroy default
type DcimRackTypesDestroyDefault struct {
	_statusCode int

	Payload any
}

// IsSuccess returns true when this dcim rack types destroy default response has a 2xx status code
func (o *DcimRackTypesDestroyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim rack types destroy default response has a 3xx status code
func (o *DcimRackTypesDestroyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim rack types destroy default response has a 4xx status code
func (o *DcimRackTypesDestroyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim rack types destroy default response has a 5xx status code
func (o *DcimRackTypesDestroyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim rack types destroy default response a status code equal to that given
func (o *DcimRackTypesDestroyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the dcim rack types destroy default response
func (o *DcimRackTypesDestroyDefault) Code() int {
	return o._statusCode
}

func (o *DcimRackTypesDestroyDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /dcim/rack-types/{id}/][%d] dcim_rack_types_destroy default %s", o._statusCode, payload)
}

func (o *DcimRackTypesDestroyDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /dcim/rack-types/{id}/][%d] dcim_rack_types_destroy default %s", o._statusCode, payload)
}

func (o *DcimRackTypesDestroyDefault) GetPayload() any {
	return o.Payload
}

func (o *DcimRackTypesDestroyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
