// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDcimRackReservationsPartialUpdateParams creates a new DcimRackReservationsPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDcimRackReservationsPartialUpdateParams() *DcimRackReservationsPartialUpdateParams {
	return NewDcimRackReservationsPartialUpdateParamsWithTimeout(cr.DefaultTimeout)
}

// NewDcimRackReservationsPartialUpdateParamsWithTimeout creates a new DcimRackReservationsPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewDcimRackReservationsPartialUpdateParamsWithTimeout(timeout time.Duration) *DcimRackReservationsPartialUpdateParams {
	return &DcimRackReservationsPartialUpdateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDcimRackReservationsPartialUpdateParamsWithContext creates a new DcimRackReservationsPartialUpdateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimRackReservationsPartialUpdateParams].
func NewDcimRackReservationsPartialUpdateParamsWithContext(ctx context.Context) *DcimRackReservationsPartialUpdateParams {
	return &DcimRackReservationsPartialUpdateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDcimRackReservationsPartialUpdateParamsWithHTTPClient creates a new DcimRackReservationsPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewDcimRackReservationsPartialUpdateParamsWithHTTPClient(client *http.Client) *DcimRackReservationsPartialUpdateParams {
	return &DcimRackReservationsPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
DcimRackReservationsPartialUpdateParams contains all the parameters to send to the API endpoint

	for the dcim rack reservations partial update operation.

	Typically these are written to a http.Request.
*/
type DcimRackReservationsPartialUpdateParams struct {

	// Data.
	Data *models.WritableRackReservation

	// ID.
	//
	// A unique integer value identifying this rack reservation.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the dcim rack reservations partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimRackReservationsPartialUpdateParams) WithDefaults() *DcimRackReservationsPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dcim rack reservations partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimRackReservationsPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dcim rack reservations partial update params.
func (o *DcimRackReservationsPartialUpdateParams) WithTimeout(timeout time.Duration) *DcimRackReservationsPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim rack reservations partial update params.
func (o *DcimRackReservationsPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the dcim rack reservations partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimRackReservationsPartialUpdateParams].
func (o *DcimRackReservationsPartialUpdateParams) WithContext(ctx context.Context) *DcimRackReservationsPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim rack reservations partial update params.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimRackReservationsPartialUpdateParams].
func (o *DcimRackReservationsPartialUpdateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim rack reservations partial update params.
func (o *DcimRackReservationsPartialUpdateParams) WithHTTPClient(client *http.Client) *DcimRackReservationsPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim rack reservations partial update params.
func (o *DcimRackReservationsPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the dcim rack reservations partial update params.
func (o *DcimRackReservationsPartialUpdateParams) WithData(data *models.WritableRackReservation) *DcimRackReservationsPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the dcim rack reservations partial update params.
func (o *DcimRackReservationsPartialUpdateParams) SetData(data *models.WritableRackReservation) {
	o.Data = data
}

// WithID adds the id to the dcim rack reservations partial update params.
func (o *DcimRackReservationsPartialUpdateParams) WithID(id int64) *DcimRackReservationsPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim rack reservations partial update params.
func (o *DcimRackReservationsPartialUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DcimRackReservationsPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
