// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DcimLocationsDestroyReader is a Reader for the DcimLocationsDestroy structure.
type DcimLocationsDestroyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimLocationsDestroyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDcimLocationsDestroyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDcimLocationsDestroyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimLocationsDestroyNoContent creates a DcimLocationsDestroyNoContent with default headers values
func NewDcimLocationsDestroyNoContent() *DcimLocationsDestroyNoContent {
	return &DcimLocationsDestroyNoContent{}
}

// DcimLocationsDestroyNoContent describes a response with status code 204, with default header values.
//
// DcimLocationsDestroyNoContent dcim locations destroy no content
type DcimLocationsDestroyNoContent struct {
}

// IsSuccess returns true when this dcim locations destroy no content response has a 2xx status code
func (o *DcimLocationsDestroyNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim locations destroy no content response has a 3xx status code
func (o *DcimLocationsDestroyNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim locations destroy no content response has a 4xx status code
func (o *DcimLocationsDestroyNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim locations destroy no content response has a 5xx status code
func (o *DcimLocationsDestroyNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim locations destroy no content response a status code equal to that given
func (o *DcimLocationsDestroyNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the dcim locations destroy no content response
func (o *DcimLocationsDestroyNoContent) Code() int {
	return 204
}

func (o *DcimLocationsDestroyNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dcim/locations/{id}/][%d] dcimLocationsDestroyNoContent", 204)
}

func (o *DcimLocationsDestroyNoContent) String() string {
	return fmt.Sprintf("[DELETE /dcim/locations/{id}/][%d] dcimLocationsDestroyNoContent", 204)
}

func (o *DcimLocationsDestroyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDcimLocationsDestroyDefault creates a DcimLocationsDestroyDefault with default headers values
func NewDcimLocationsDestroyDefault(code int) *DcimLocationsDestroyDefault {
	return &DcimLocationsDestroyDefault{
		_statusCode: code,
	}
}

// DcimLocationsDestroyDefault describes a response with status code -1, with default header values.
//
// DcimLocationsDestroyDefault dcim locations destroy default
type DcimLocationsDestroyDefault struct {
	_statusCode int

	Payload any
}

// IsSuccess returns true when this dcim locations destroy default response has a 2xx status code
func (o *DcimLocationsDestroyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim locations destroy default response has a 3xx status code
func (o *DcimLocationsDestroyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim locations destroy default response has a 4xx status code
func (o *DcimLocationsDestroyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim locations destroy default response has a 5xx status code
func (o *DcimLocationsDestroyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim locations destroy default response a status code equal to that given
func (o *DcimLocationsDestroyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the dcim locations destroy default response
func (o *DcimLocationsDestroyDefault) Code() int {
	return o._statusCode
}

func (o *DcimLocationsDestroyDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /dcim/locations/{id}/][%d] dcim_locations_destroy default %s", o._statusCode, payload)
}

func (o *DcimLocationsDestroyDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /dcim/locations/{id}/][%d] dcim_locations_destroy default %s", o._statusCode, payload)
}

func (o *DcimLocationsDestroyDefault) GetPayload() any {
	return o.Payload
}

func (o *DcimLocationsDestroyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
