// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDcimCableBundlesUpdateParams creates a new DcimCableBundlesUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDcimCableBundlesUpdateParams() *DcimCableBundlesUpdateParams {
	return NewDcimCableBundlesUpdateParamsWithTimeout(cr.DefaultTimeout)
}

// NewDcimCableBundlesUpdateParamsWithTimeout creates a new DcimCableBundlesUpdateParams object
// with the ability to set a timeout on a request.
func NewDcimCableBundlesUpdateParamsWithTimeout(timeout time.Duration) *DcimCableBundlesUpdateParams {
	return &DcimCableBundlesUpdateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDcimCableBundlesUpdateParamsWithContext creates a new DcimCableBundlesUpdateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimCableBundlesUpdateParams].
func NewDcimCableBundlesUpdateParamsWithContext(ctx context.Context) *DcimCableBundlesUpdateParams {
	return &DcimCableBundlesUpdateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDcimCableBundlesUpdateParamsWithHTTPClient creates a new DcimCableBundlesUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewDcimCableBundlesUpdateParamsWithHTTPClient(client *http.Client) *DcimCableBundlesUpdateParams {
	return &DcimCableBundlesUpdateParams{
		HTTPClient: client,
	}
}

/*
DcimCableBundlesUpdateParams contains all the parameters to send to the API endpoint

	for the dcim cable bundles update operation.

	Typically these are written to a http.Request.
*/
type DcimCableBundlesUpdateParams struct {

	// Data.
	Data *models.WritableCableBundle

	// ID.
	//
	// A unique integer value identifying this cable bundle.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the dcim cable bundles update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimCableBundlesUpdateParams) WithDefaults() *DcimCableBundlesUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dcim cable bundles update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimCableBundlesUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dcim cable bundles update params.
func (o *DcimCableBundlesUpdateParams) WithTimeout(timeout time.Duration) *DcimCableBundlesUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim cable bundles update params.
func (o *DcimCableBundlesUpdateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the dcim cable bundles update params.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimCableBundlesUpdateParams].
func (o *DcimCableBundlesUpdateParams) WithContext(ctx context.Context) *DcimCableBundlesUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim cable bundles update params.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimCableBundlesUpdateParams].
func (o *DcimCableBundlesUpdateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim cable bundles update params.
func (o *DcimCableBundlesUpdateParams) WithHTTPClient(client *http.Client) *DcimCableBundlesUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim cable bundles update params.
func (o *DcimCableBundlesUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the dcim cable bundles update params.
func (o *DcimCableBundlesUpdateParams) WithData(data *models.WritableCableBundle) *DcimCableBundlesUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the dcim cable bundles update params.
func (o *DcimCableBundlesUpdateParams) SetData(data *models.WritableCableBundle) {
	o.Data = data
}

// WithID adds the id to the dcim cable bundles update params.
func (o *DcimCableBundlesUpdateParams) WithID(id int64) *DcimCableBundlesUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim cable bundles update params.
func (o *DcimCableBundlesUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DcimCableBundlesUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
