// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDcimPowerOutletTemplatesRetrieveParams creates a new DcimPowerOutletTemplatesRetrieveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDcimPowerOutletTemplatesRetrieveParams() *DcimPowerOutletTemplatesRetrieveParams {
	return NewDcimPowerOutletTemplatesRetrieveParamsWithTimeout(cr.DefaultTimeout)
}

// NewDcimPowerOutletTemplatesRetrieveParamsWithTimeout creates a new DcimPowerOutletTemplatesRetrieveParams object
// with the ability to set a timeout on a request.
func NewDcimPowerOutletTemplatesRetrieveParamsWithTimeout(timeout time.Duration) *DcimPowerOutletTemplatesRetrieveParams {
	return &DcimPowerOutletTemplatesRetrieveParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDcimPowerOutletTemplatesRetrieveParamsWithContext creates a new DcimPowerOutletTemplatesRetrieveParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimPowerOutletTemplatesRetrieveParams].
func NewDcimPowerOutletTemplatesRetrieveParamsWithContext(ctx context.Context) *DcimPowerOutletTemplatesRetrieveParams {
	return &DcimPowerOutletTemplatesRetrieveParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDcimPowerOutletTemplatesRetrieveParamsWithHTTPClient creates a new DcimPowerOutletTemplatesRetrieveParams object
// with the ability to set a custom HTTPClient for a request.
func NewDcimPowerOutletTemplatesRetrieveParamsWithHTTPClient(client *http.Client) *DcimPowerOutletTemplatesRetrieveParams {
	return &DcimPowerOutletTemplatesRetrieveParams{
		HTTPClient: client,
	}
}

/*
DcimPowerOutletTemplatesRetrieveParams contains all the parameters to send to the API endpoint

	for the dcim power outlet templates retrieve operation.

	Typically these are written to a http.Request.
*/
type DcimPowerOutletTemplatesRetrieveParams struct {

	// ID.
	//
	// A unique integer value identifying this power outlet template.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the dcim power outlet templates retrieve params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimPowerOutletTemplatesRetrieveParams) WithDefaults() *DcimPowerOutletTemplatesRetrieveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dcim power outlet templates retrieve params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimPowerOutletTemplatesRetrieveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dcim power outlet templates retrieve params.
func (o *DcimPowerOutletTemplatesRetrieveParams) WithTimeout(timeout time.Duration) *DcimPowerOutletTemplatesRetrieveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim power outlet templates retrieve params.
func (o *DcimPowerOutletTemplatesRetrieveParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the dcim power outlet templates retrieve params.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimPowerOutletTemplatesRetrieveParams].
func (o *DcimPowerOutletTemplatesRetrieveParams) WithContext(ctx context.Context) *DcimPowerOutletTemplatesRetrieveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim power outlet templates retrieve params.
//
// Deprecated: use the operation call with context to pass the context instead of [DcimPowerOutletTemplatesRetrieveParams].
func (o *DcimPowerOutletTemplatesRetrieveParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim power outlet templates retrieve params.
func (o *DcimPowerOutletTemplatesRetrieveParams) WithHTTPClient(client *http.Client) *DcimPowerOutletTemplatesRetrieveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim power outlet templates retrieve params.
func (o *DcimPowerOutletTemplatesRetrieveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the dcim power outlet templates retrieve params.
func (o *DcimPowerOutletTemplatesRetrieveParams) WithID(id int64) *DcimPowerOutletTemplatesRetrieveParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim power outlet templates retrieve params.
func (o *DcimPowerOutletTemplatesRetrieveParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DcimPowerOutletTemplatesRetrieveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
