// Code generated by go-swagger; DO NOT EDIT.

// Copyright The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package users

import (
	"context"
	"net/http"
	"time"

	"github.com/fbreckle/go-netbox/netbox/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewUsersOwnersUpdateParams creates a new UsersOwnersUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUsersOwnersUpdateParams() *UsersOwnersUpdateParams {
	return NewUsersOwnersUpdateParamsWithTimeout(cr.DefaultTimeout)
}

// NewUsersOwnersUpdateParamsWithTimeout creates a new UsersOwnersUpdateParams object
// with the ability to set a timeout on a request.
func NewUsersOwnersUpdateParamsWithTimeout(timeout time.Duration) *UsersOwnersUpdateParams {
	return &UsersOwnersUpdateParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewUsersOwnersUpdateParamsWithContext creates a new UsersOwnersUpdateParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [UsersOwnersUpdateParams].
func NewUsersOwnersUpdateParamsWithContext(ctx context.Context) *UsersOwnersUpdateParams {
	return &UsersOwnersUpdateParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewUsersOwnersUpdateParamsWithHTTPClient creates a new UsersOwnersUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewUsersOwnersUpdateParamsWithHTTPClient(client *http.Client) *UsersOwnersUpdateParams {
	return &UsersOwnersUpdateParams{
		HTTPClient: client,
	}
}

/*
UsersOwnersUpdateParams contains all the parameters to send to the API endpoint

	for the users owners update operation.

	Typically these are written to a http.Request.
*/
type UsersOwnersUpdateParams struct {

	// Data.
	Data *models.WritableOwner

	// ID.
	//
	// A unique integer value identifying this owner.
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the users owners update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersOwnersUpdateParams) WithDefaults() *UsersOwnersUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the users owners update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersOwnersUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the users owners update params.
func (o *UsersOwnersUpdateParams) WithTimeout(timeout time.Duration) *UsersOwnersUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users owners update params.
func (o *UsersOwnersUpdateParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the users owners update params.
//
// Deprecated: use the operation call with context to pass the context instead of [UsersOwnersUpdateParams].
func (o *UsersOwnersUpdateParams) WithContext(ctx context.Context) *UsersOwnersUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users owners update params.
//
// Deprecated: use the operation call with context to pass the context instead of [UsersOwnersUpdateParams].
func (o *UsersOwnersUpdateParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the users owners update params.
func (o *UsersOwnersUpdateParams) WithHTTPClient(client *http.Client) *UsersOwnersUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users owners update params.
func (o *UsersOwnersUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the users owners update params.
func (o *UsersOwnersUpdateParams) WithData(data *models.WritableOwner) *UsersOwnersUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the users owners update params.
func (o *UsersOwnersUpdateParams) SetData(data *models.WritableOwner) {
	o.Data = data
}

// WithID adds the id to the users owners update params.
func (o *UsersOwnersUpdateParams) WithID(id int64) *UsersOwnersUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the users owners update params.
func (o *UsersOwnersUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *UsersOwnersUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
